### ISSUE TITLE
Problem with empty reactive ggvis

### ISSUE THREAD

**Issue by etheleon** [rstudio/rmarkdown#423] opened 2015-04-30 04:56 UTC
i'm writing an interactive `.rmd` document with embedded ggvis recieving a reactive
the ggvis is plotting a density plot using `layer_densities`.

I encountered the following error highlighted below 
when changing the parameters to a dropdown list which causes the input dataframe/reactive to change. 

I assume the error was because its an empty data.frame/reactive?

**PROBLEM**  Eversince, I've not able to get my Rmarkdown to compile. 

Its seems it is not able to access the `input` variable.
`Error in if (toLog) { : argument is of length zero` where `toLog` is `input$toLog`

```
Error: need at least 2 points to select a bandwidth automatically
Warning: Unhandled error in observer: invalid 'times' argument
observe({
    data_reactive <- data_table[[data_name]]
    session$sendCustomMessage("ggvis_data", list(plotId = id, 
        name = data_name, value = as.vega(data_reactive(), data_name)))
})
Warning: Unhandled error in observer: invalid 'envir' argument of type 'closure'
observe({
    data_reactive <- data_table[[data_name]]
    session$sendCustomMessage("ggvis_data", list(plotId = id, 
        name = data_name, value = as.vega(data_reactive(), data_name)))
})
Warning: Unhandled error in observer: invalid 'envir' argument of type 'closure'
observe({
    data_reactive <- data_table[[data_name]]
    session$sendCustomMessage("ggvis_data", list(plotId = id, 
        name = data_name, value = as.vega(data_reactive(), data_name)))
})
Warning: Unhandled error in observer: no applicable method for 'apply_props' applied to an object of class "function"
observe({
    data_reactive <- data_table[[data_name]]
    session$sendCustomMessage("ggvis_data", list(plotId = id, 
        name = data_name, value = as.vega(data_reactive(), data_name)))
})
Warning: Unhandled error in observer: no applicable method for 'apply_props' applied to an object of class "function"
observe({
    for (name in names(data_table)) {
        data_table[[name]]()
    }
    session$sendCustomMessage("ggvis_command", list(plotId = id, 
        command = "update"))
})
```

**Comment by etheleon** [comment] 2015-04-30 05:56
i can start rendering the document again if i do the following in sequence:

1. comment out ggvis code. 
2. add a static plot using ggplot wrapped inside renderPlot
3. run this from console R (not from Rstudio)

If i run this in Rstudio the problem persists and i cant form the document.

**Comment by jjallaire** [comment] 2015-04-30 09:30
@wch @jcheng5 @jmcphers Is this a limitation in interactive Rmd that doesn't exist in shiny?

**Comment by jcheng5** [comment] 2015-04-30 15:05
Can you create a reproducible example we can try? I'm sure we can get to the bottom of this. Thanks...

**Comment by etheleon** [comment] 2015-05-04 17:26
I've since overcome this by writing the reactive portion of this as a shinyapp embedded into rmd. 
ie. 

```{r}
shinapp(
server = ... 
ui = ... 
)
```

instead of putting the reactives outside of shinyapp. 
I'll write up a reproducible example over the weekend.

**Comment by Diegres** [comment] 2015-07-01 23:14
I am having a similar problem with the following code:
=============CODE===========
library(ggvis)
library(shiny)
#
ui <- fluidPage(
  headerPanel("ggvis Test"),
  ggvisOutput("hist"),
  uiOutput("hist_ui")  
)
#
server <- function(input, output) {
  mtcars %>%
    ggvis(~wt, ~mpg) %>%
    layer_points() %>%
    layer_smooths(span = input_slider(0,1)) %>%
    bind_shiny("hist", "hist_ui")  
}
#
shinyApp(ui = ui, server = server)
=======================================
it works for 1 - 5 min and then crashes with a similar err. msg.
Please let me know if a workaround exist
Thanks
Sergei

**Comment by Diegres** [comment] 2015-07-01 23:21
Wrapping the above code into the shinyApp(...) does not solve the problem either. Here is the complete error message:
Listening on http://127.0.0.1:6337
Error: NA/NaN/Inf in foreign function call (arg 5)
Warning in run(timeoutMs) :
  span too small.   fewer data values than degrees of freedom.
Warning in run(timeoutMs) : pseudoinverse used at 1.4934
Warning in run(timeoutMs) : neighborhood radius 0.34156
Warning in run(timeoutMs) : reciprocal condition number  0
Warning in run(timeoutMs) :
  There are other near singularities as well. 0.037464
Warning in run(timeoutMs) : zero-width neighborhood. make span bigger
Warning in run(timeoutMs) :
  Unhandled error in observer: invalid 'envir' argument of type 'closure'
observe({
    data_reactive <- data_table[[data_name]]
    session$sendCustomMessage("ggvis_data", list(plotId = id, 
        name = data_name, value = as.vega(data_reactive(), data_name)))
})
Warning in run(timeoutMs) :
  Unhandled error in observer: invalid 'envir' argument of type 'closure'
observe({
    data_reactive <- data_table[[data_name]]
    session$sendCustomMessage("ggvis_data", list(plotId = id, 
        name = data_name, value = as.vega(data_reactive(), data_name)))
})
Warning in run(timeoutMs) :
  Unhandled error in observer: no applicable method for 'apply_props' applied to an object of class "function"
observe({
    data_reactive <- data_table[[data_name]]
    session$sendCustomMessage("ggvis_data", list(plotId = id, 
        name = data_name, value = as.vega(data_reactive(), data_name)))
})
Warning in run(timeoutMs) :
  Unhandled error in observer: no applicable method for 'apply_props' applied to an object of class "function"
observe({
    for (name in names(data_table)) {
        data_table[[name]]()
    }
    session$sendCustomMessage("ggvis_command", list(plotId = id, 
        command = "update"))
})

**Comment by Diegres** [comment] 2015-07-01 23:38
I think I've found what caused the above error.. After I made the lower limit of the slider in
layer_smooths(span = input_slider(<strong>0.2</strong>,  1,  0.5,  0.05))
greater than zero (in this case = 0.2)  it did not crashed any more (so far)

**Comment by jjallaire** [comment] 2015-07-02 03:54
@wch

**Comment by etheleon** [comment] 2015-07-09 09:14
interesting..

**Comment by yihui** [comment] 2017-08-31 18:53
Closing since a minimal reproducible example has not been posted yet. Can be reopened once we are able to reproduce it.

**Closed by yihui** 2017-08-31 18:53 UTC
