### ISSUE TITLE
No reference in tufte html

### ISSUE THREAD

**Issue by xiaoouwang** [rstudio/rmarkdown#1479] opened 2018-11-13 20:10 UTC
A working example is here :   Note that according to the doc link-citations: no should be sufficient to put reference at the end but helas no. For the pdf render it does show a reference but for html nothing...

Note the same question has been asked 2 years ago : https://stackoverflow.com/questions/39053097/how-do-i-put-the-citations-at-the-end-of-a-document-in-a-tufte-handout

```

---
title: "Tufte Handout"
subtitle: "An implementation in R Markdown"
author: "JJ Allaire and Yihui Xie"
date: "`r Sys.Date()`"
output:
  tufte::tufte_html: default
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
bibliography: skeleton.bib
link-citations: no
---

```{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)```

# Introduction

The Tufte handout style is a style [@R-rmarkdown] that Edward Tufte uses in ^[doesn't work]

# References

```{r bib, include=FALSE}
# create a bib file for the R packages used in this document
knitr::write_bib(c('base', 'rmarkdown'), file = 'skeleton.bib')```   


```

**Comment by cderv** [comment] 2020-11-02 15:29
Hi, 
Thanks for the report. This works as expected: the bibliography is not in the margin but at the end when setting `link-citations: no`

Unfortunately, I can't reproduce this. I believe this should have been fixed here, or in tufte package. 

I'll close this, but feel free to reopen if you still have an issue with last versions of packages, 

Thank you.

**Closed by cderv** 2020-11-02 15:29 UTC
