### ISSUE TITLE
Plot not rendering in PowerPoint presentation

### ISSUE THREAD

**Issue by abalter** [rstudio/rmarkdown#2158] opened 2021-06-03 18:55 UTC
## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x ] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x ] included a minimal, self-contained, and reproducible example?
Attached

- [ x] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [ x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [ ] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")`? 

## Issue
My plots aren't rendering. I carved out a MRE from my full RMD. I also added a single plot using the `mpg` dataset. The `mpg` plot renders fine. However, the plot with data defined in the RMD does not. In the "real" RMD file, I load the data and process it. I hard-code the variable `graph_data` to create the MRE.

What is causing the plot of my data to not render?

## MRE
<pre>
---
title: "PPT Test 4"
author: "Ariel Balter"
output:
  powerpoint_presentation:
    reference_doc: theme1.pptx
  html_notebook:
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: yes
    theme: lumen
    fig_width: 8
    fig_height: 6
    fig_caption: yes
    code_folding: show
---

```{r, include=F}
knitr::opts_chunk$set(
  warning=F,
  message=F,
  echo=F,
  error=F,
  number_section=T,
  include=F
)
```

```{r}
# Load Libraries
library(tidyverse)
library(magrittr)
library(ggplot2)
library(ggbeeswarm)
library(ggtext)
library(knitr)
```

# graph data
```{r, include=T}
graph_data = tibble(
  
  "Set" = c("tso500_alt", "tso500_ref", "tst170_alt", "tst170_ref", "we_alt", "we_ref"),
  
  "N" = c(3174, 7402, 297, 288, 224397, 77265),
  
  "Type" = c("alt", "ref", "alt", "ref", "alt", "ref"), 
  
  "Base Set" = c("tso500", "tso500", "tst170", "tst170", "we", "we")
)

graph_data %>% kable()
```

# Ref and Alt called in different sets.
Are these statistically consistent with the number of bases covered?
```{r, a_plot, include=T}
graph_data %>% 
  ggplot(aes(x=Set, y=N, color=Type, fill=Type)) +
  geom_bar(stat="identity") +
  scale_y_log10() +
  ggtitle("Count of distinct allele words")
```

# A plot
```{r, cars, include=T}
mpg %>% 
  ggplot(aes(x = displ, y = hwy, color = class)) +
  geom_point() +
  scale_y_log10() +
  ggtitle("Count of distinct allele words")
```
</pre>

```
> xfun::session_info('rmarkdown')
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043), RStudio 1.4.1106

Locale:
  LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
  LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
  LC_TIME=English_United States.1252    

Package version:
  base64enc_0.1.3   digest_0.6.27     evaluate_0.14     glue_1.4.2       
  graphics_3.6.3    grDevices_3.6.3   highr_0.9         htmltools_0.5.1.1
  jsonlite_1.7.2    knitr_1.33        magrittr_2.0.1    markdown_1.1     
  methods_3.6.3     mime_0.10         rlang_0.4.11      rmarkdown_2.8    
  stats_3.6.3       stringi_1.6.2     stringr_1.4.0     tinytex_0.31     
  tools_3.6.3       utils_3.6.3       xfun_0.23         yaml_2.2.1       

Pandoc version: 2.14.0.1
```

**Comment by cderv** [comment] 2021-06-03 20:17
> ````
> # Ref and Alt called in different sets.
> Are these statistically consistent with the number of bases covered?
> ```{r, a_plot, include=T}
> ````
I would say you just need to add some new line to separate paragraph.

````
# Ref and Alt called in different sets.

Are these statistically consistent with the number of bases covered?

```{r, a_plot, include=T}
````

Markdown syntax is not considering going to newline as a new paragraph unless there is an empty line. This would be equivalent
```
Some text
on one line
```
```
Some text on one line
```

This means that without an empty line before the chunk, your graph will be inserting inline. The markdown generated before Pandoc conversion to PPTX 
````markdown
# Ref and Alt called in different sets.
Are these statistically consistent with the number of bases covered?  
![](test_files/figure-pptx/a_plot-1.png)<!-- -->
```` 

and I don't think that powerpoing format in Pandoc handles that well. 

I let you try with adding those empty lines. Thanks!

**Comment by abalter** [comment] 2021-06-03 20:26
Wow. That did fix it.

**Comment by yihui** [comment] 2021-06-03 21:00
I can't help cc'ing @shannonpileggi again, whose wisdom we should learn by heart: https://www.pipinghotdata.com/posts/2020-09-07-introducing-the-rstudio-ide-and-r-markdown/#layout-error

> Let your markdown **breathe**!

**Comment by abalter** [comment] 2021-06-03 21:14
U

**Comment by abalter** [comment] 2021-06-03 21:24
Apparently, can't do text and image either:

~~~
```
# Title
## Subtitle
* bullet 1
* bullet 2

![](https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Markdown-mark.svg/350px-Markdown-mark.svg.png)
```
~~~

**Comment by yihui** [comment] 2021-06-03 21:28
For now, that's by design. Documentation: https://bookdown.org/yihui/rmarkdown/powerpoint-presentation.html

> Please note that images and tables will always be placed on new slides. The only elements that can coexist with an image or table on a slide are the slide header and image/table caption.

This might change in a future version of Pandoc (we are currently trying to hire someone to improve PPT; if you have suggestions, please feel free to let @apreshill know).

**Comment by apreshill** [comment] 2021-06-03 21:33
yes, but this likely will not be able to behave differently. @abalter (Hi! Hope pandemic PDX is treating you well) the "way" is to do two column slides:

```
::: {.columns}

::: {.column}

Left column:



- Bullet

- Bullet

- Bullet

:::



::: {.column}

![](images/penguins_cran.png)

:::

:::

```

**Comment by abalter** [comment] 2021-06-03 21:35
@apreshill I'm ok--but parts of the world are still on fire! Hope you are well.

What would break if everything until the next slide just got crammed on the slide as well as possible? If there is text and an image, then use a standard text+image slide template.

**Comment by apreshill** [comment] 2021-06-03 21:43
The issue is that PPT operates with just notions of individual rectangles. You can either have an image, or text, but not both, coexisting inside the same rectangle. I wonder if you'd be less or more puzzled if we took your code provided, and said "oh would you like us to automatically create a two column slide?" That is really the only alternative- which I'm not sure is better?

**Comment by abalter** [comment] 2021-06-03 21:49
Maybe it's new, but this "slide master" template looks like it can handle text and images. 

![image](https://user-images.githubusercontent.com/5349876/120716472-f3c8a800-c47a-11eb-880e-aef9735ea54a.png)

**Comment by apreshill** [comment] 2021-06-03 21:59
If you close the master view there and try to use that slide template, you'd have to choose text or image.

**Comment by abalter** [comment] 2021-06-03 22:19
Darn. Well, it's a first-world problem.

**Comment by apreshill** [comment] 2021-06-03 22:40
Original issue duplicate of: https://github.com/rstudio/rmarkdown/issues/1363

**Closed** 2021-06-03 22:48 UTC
Labels: powerpoint :battery:, question

**Comment by shannonpileggi** [comment] 2021-06-03 23:51
> I can't help cc'ing @shannonpileggi again, whose wisdom we should learn by heart: https://www.pipinghotdata.com/posts/2020-09-07-introducing-the-rstudio-ide-and-r-markdown/#layout-error
> 
> > Let your markdown **breathe**!

@yihui  this warms my heart every time!

**Comment by shannonpileggi** [comment] 2021-06-03 23:56
I also saw this 

> For now, that's by design. Documentation: https://bookdown.org/yihui/rmarkdown/powerpoint-presentation.html
> 
> > Please note that images and tables will always be placed on new slides. The only elements that can coexist with an image or table on a slide are the slide header and image/table caption.
> 
> This might change in a future version of Pandoc (we are currently trying to hire someone to improve PPT; if you have suggestions, please feel free to let @apreshill know).

@apreshill  I don't knit directly to ppt b/c editable graphics are key for finishing touches in our deliverables. If we could knit to powerpoint with an [editable graphics option like in officer](https://www.pipinghotdata.com/posts/2020-09-22-exporting-editable-ggplot-graphics-to-powerpoint-with-officer-and-purrr/) that would be a great feature.

**Comment by apreshill** [comment] 2021-06-04 00:02
@shannonpileggi I think that is a great feature for officer- and one that the developer has really perfected. If that is a critical feature for you, I'd continue to use that method. Having said that, if there is another solution that would also meet your needs here other than one developed in officer, please feel free to file a feature request in a separate issue!

**Comment by cderv** [comment] 2021-06-04 07:34
@shannonpileggi officeverse has been extended with an **officedown** package. The aim is to leverage **officer** from within a Rmd document syntax. You would be able to get editable graphic quite easily by leveraging the `rvg::dml` that is described in the post you linked to. 

Obviously to have Plot + Text on the same slide, this would require a logic of column layout, or boxes placed on the side. **officer** also can do this with the logic behind `ph_location*()` functions. This could be used to place left or right, or even choose the position for the content. 

here is a simple example based on the above example from @abalter 

````markdown
---
title: "PPT Test 5"
output: officedown::rpptx_document
---


```{r}
# Load Libraries
library(ggplot2)
library(officedown)
```

# Plot with text

Text to go on the same  
page as the plot

```{r, echo = FALSE, ph = officer::ph_location_right() }
p <- ggplot(mpg, aes(x = displ, y = hwy, color = class)) +
  geom_point() +
  scale_y_log10() +
  ggtitle("Plot of some stuff")
# special officeverse utility for this to work
# the ggplot needs to be converted
rvg::dml(ggobj = p) # from rvg package - editable = TRUE by default
```

````

This will render as 
![image](https://user-images.githubusercontent.com/6791940/120763466-86b72000-c517-11eb-8130-395e19f61e99.png)

and by default you get also editable graphics
![image](https://user-images.githubusercontent.com/6791940/120763558-a2222b00-c517-11eb-8258-0566e8573d0a.png)

This is a special usage with a syntax that could be improved in my opinion but it has the benefit for **officer** user to do what they are used to quite easily with **rmarkdown**. 


> I don't knit directly to ppt b/c editable graphics are key for finishing touches in our deliverables. If we could knit to powerpoint with an editable graphics option like in officer that would be a great feature.

Curious if you knew about this ? Would that answer your need ?

**Comment by cderv** [comment] 2021-06-11 09:20
> Maybe time for another blog post :)

**officedown** does not get so much example content out there so I think it would be helpful for the community ! 😉
