### ISSUE TITLE
Latex engine recognizes a dollar sign within inline r code

### ISSUE THREAD

**Issue by KobaKhit** [rstudio/rmarkdown#602] opened 2016-01-25 04:50 UTC
Hello. I think I was able to isolate a strange behavior. Below is the Rmarkdown file that produces a pandoc error when I push "knit to pdf" button in Rstudio.

```r
---
title: "test"
output: pdf_document
---

# I used "\" so that github styles this as one code chunk 
\```{r} 
df2 = list(a=1.45e+10) 
\```

# this inline r code causes the error
Inline r code `r df2$a` 
```

The error itself.

```
output file: test.knit.md

! Missing $ inserted.
<inserted text> 
                $
l.122 1.45\times

pandoc.exe: Error producing PDF from TeX source
Error: pandoc document conversion failed with error 43
In addition: Warning message:
running command '"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS test.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output test.pdf --template "C:\Users\TimDz\Documents\R\win-library\3.2\rmarkdown\rmd\latex\default.tex" --highlight-style tango --latex-engine pdflatex --variable graphics=yes --variable "geometry:margin=1in"' had status 43 
Execution halted
```

So basically within `r df2$a` the dollar sign gets recognized by a latex engine and is expecting a closing dollar sign and hence the error. This only happens when the last character before the dollar sign is a number and the value to be displayed is a numeric of the form `14500`( `1.45e+4`) where the exponent is 4 and above. To clarify

```
{r code chunk}
df2 = list(a=1.45e+1)  # will not cause error
df2 = list(a=1.45e+2)  # will not cause error
...
df2 = list(a=1.45e+4)  # causes error
etc.
{r code  chunk}

# Error
Inline r code `r df2$a`  
```

At the end of this post is my session info. Both latex engines pdflatex and xelatex stop with an error mentioned above. I have full installation of miktex 2.9

```
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] corrplot_0.73  xtable_1.8-0   lpSolve_5.6.13 quantmod_0.4-5 TTR_0.23-0     xts_0.9-7      zoo_1.7-12    
[8] knitr_1.11    

loaded via a namespace (and not attached):
 [1] lattice_0.20-33 digest_0.6.8    grid_3.2.3      formatR_1.2.1   magrittr_1.5    evaluate_0.8    highr_0.5.1    
 [8] stringi_1.0-1   rmarkdown_0.9.2 tools_3.2.3     stringr_1.0.0   yaml_2.1.13     htmltools_0.2.6
```

**Comment by yihui** [comment] 2016-01-25 05:34
Duplicate of #385.

**Closed by yihui** 2016-01-25 05:34 UTC
Labels: duplicate

**Comment by KobaKhit** [comment] 2016-01-25 06:10
oh so the solution is just to enclose the inline r code in dollar signs like so $`r df$a`$. I see. Thanks.

**Comment by yihui** [comment] 2016-01-25 06:15
Exactly.
