### ISSUE TITLE
Knitting in R markdown issue

### ISSUE THREAD

**Issue by Rusik310** [rstudio/rmarkdown#1887] opened 2020-08-31 22:01 UTC
Hey guys, Can someone give a handl, please? 

I am not able to knit in HTML from R. Everything runs great in R markdown, but doesn't knit due to some mistake...

Please, find the screenshot attached.
![Screen Shot 2020-08-31 at 23 58 07](https://user-images.githubusercontent.com/70547411/91773054-50462080-ebe6-11ea-93d8-cefdc3153680.png)

**Comment by cderv** [comment] 2020-09-01 08:41
Hi, 

This type of question is more suited for the RStudio Community. https://community.rstudio.com/c/R-Markdown/10
You should asked there. 

Regarding your issue, the error says that Rnew is not found, and it is true. From your code Rnew is not define outside the function definition. So I think you need to call the function `corstars` on the `x` you want to calculate `Rnew`. 

Currently you are under the impression the code works because you may have a `Rnew` object already existing in your workspace. When you run code from the Rmd chunk, it will run in your workspace. Try to run the code in a new R session with a fresh empty global envionment and you will reproduce the error. 

I'll close this here because it is not a Rmarkdown issue, and you can open an issue on the community if you want further help on how R works.

**Closed by cderv** 2020-09-01 08:41 UTC
