### ISSUE TITLE
Error in rmarkdown:::pandoc_html_highlight_args(highlight, template = "default",  :    unused arguments (self_contained, lib_dir, output_dir)

### ISSUE THREAD

**Issue by adeschen** [rstudio/rmarkdown#886] opened 2016-11-23 21:53 UTC
Hi,

I am working on a Bioconductor package. 

Package on github: https://github.com/adeschen/RJMCMCNucleosomes
Travis: https://travis-ci.org/adeschen/RJMCMCNucleosomes/builds

The package used to compile correctly but is now generating an error on travis. To reproduce that error, I have updated RStudio and associated packages (RStudio 1.0.44, rmarkdown 1.2, R 3.3.0). I can now reproduce the error. Using debug option, I managed to find that the call of the specific function:

extra_args <- output_format$pre_processor(yaml_front_matter, 
                utf8_input, runtime, knit_meta, files_dir, output_dir)
line 538 of render.R

generates that error:

Error in rmarkdown:::pandoc_html_highlight_args(highlight, template = "default",  : 
  unused arguments (self_contained, lib_dir, output_dir)

I have seen that the parameters of the pandoc_html_highlight_args() function have been changed recently. So, I have the feeling that the vignette problem I have is related to the newest version of the rmarkdown package.

Thanks,

Astrid

**Comment by jjallaire** [comment] 2016-11-23 21:55
Yes, the problem is that the package was calling a private function of the
rmarkdown package (rmarkdown:::pandoc_html_highlight_args) and it's
arguments changed. This has been fixed in the development version of the
BiocStyle package but that fix will still need to propagate itself to Bioc
3.4 on CRAN, see
https://github.com/Bioconductor/BiocStyle/commit/6db4860f3aadc286809526dca80edfd0c32d2c7f#commitcomment-19941629

**Closed** 2016-11-23 21:57 UTC
