### ISSUE TITLE
RMarkdown overwrites images from python plots

### ISSUE THREAD

**Issue by TobiSonne** [rstudio/rmarkdown#2134] opened 2021-05-11 10:12 UTC
I've asked a question on stackoverflow, I think there is a bug:

https://stackoverflow.com/questions/67482838/rmarkdown-overwrites-images-from-python-plots

**Comment by TobiSonne** [comment] 2021-05-11 11:24
Thank you for your fast answer! Could I please share the original document via mail? I've made an minimal reproducible example but everything went fine there ... I really have no idea what was really different there.

**Comment by TobiSonne** [comment] 2021-05-11 12:31
Now I know what's the problem:
Markdown starts with 1 if there are any R chunks between two python chunks ...
My minimal example is attached.
As you will see there should be first two python plot, then an R plot, then another python plot.
When the third python plot is saved (after the r plot) it is named pysetup-1.pdf again and the first plot is overwritten.
Thank you so much for helping me, I'm really enjoying R Markdown and I would be so happy if python would be integrated perfectly!

[minimal.zip](https://github.com/rstudio/rmarkdown/files/6459071/minimal.zip)

**Comment by cderv** [comment] 2021-05-12 08:18
Unfortunately I am not able to run the document. I get weird python error not related to the one you described. This may require a specific setup or maybe specific version of Python package. 

As I think this is related to Python engine, you can also share your issue and example in **reticulate** repo and in https://community.rstudio.com in the Python category. 

I'll look further when I'll have to setup correctly the python environment. If you can sent a `requirement.txt`, or even adding the use of **renv** in your minimal project, that would help to be sure we have the same setup. 
(**renv** knows about Python: https://rstudio.github.io/renv/articles/python.html) 

Thanks

**Comment by bernardkaplan** [comment] 2021-06-23 08:59
Hi,

I managed to reproduce an issue that seems similar to the one described.
Each time an {r} chunk is inserted the python chunk count is reset and images get overwritten. Notice that an r chunk without the curly braces doesn't create the issue.

Here is a minimal example illustrating the issue (I suppose matplotlib is installed)

````
---
title: "demo"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, results = FALSE, fig.width = 4, fig.height = 3)
```

```{python include=FALSE}
import matplotlib.pyplot as plt
```

```{python}
plt.plot([0, 1])
plt.show()
```

```{r}
```

```{python}
plt.plot([1, 0])
plt.show()
```
````

Hope this helps.

**Comment by cderv** [comment] 2021-06-23 13:00
@bernardkaplan I believe this is related to https://github.com/rstudio/reticulate/issues/1010 and has been fixed in **reticulate**.

Can you try the dev version of **reticulate** ? I can't reproduce your issue on my side by installing it.

Same for your issue @TobiSonne , I believe this is now fixed with the dev version of reticulate. Can you confirm ? 

Thanks!

**Comment by bernardkaplan** [comment] 2021-06-23 17:24
Installing the development version of `reticulate` solved the problem indeed.

Thanks a lot for your lightspeed answer.

**Comment by cderv** [comment] 2021-06-24 08:18
@bernardkaplan Thanks for the confirmation. 

@TobiSonne I think the issue is fixed by dev version of reticulate. I'll close this. Please, reopen if there is still something not right. thanks!

**Closed by cderv** 2021-06-24 08:18 UTC
Labels: python / reticulate, question
