### ISSUE TITLE
Several ggplotly figures from within if block in rmarkdown

### ISSUE THREAD

**Issue by mocalvao** [rstudio/rmarkdown#983] opened 2017-02-28 12:02 UTC

**Comment by mocalvao** [comment] 2017-02-28 12:04
I am unable to generate an html file, from rmarkdown, which displays two or more ggplotly plots created inside an if block in a given code chunk.

My MWE rmarkdown source code follows:

---
title: Several ggplotly figures from within if block in rmarkdown
author: "Mauricio Calvao"
date: "February 27, 2017"
output:
    html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(plotly)
```


## Outside if block:

I can have rmarkdown generate an html document with two ggplotly plots, outside of an if block in a given chunk:

```{r}
ggplotly(qplot(data = pressure, x = temperature, y = pressure))
ggplotly(qplot(data = pressure, x = pressure, y = temperature))
```

## Inside if block:

However, when I try the same code inside an if block, only the last plot shows up in the html document:

```{r}
if (TRUE) {
ggplotly(qplot(data = pressure, x = temperature, y = pressure))
ggplotly(qplot(data = pressure, x = pressure, y = temperature))
}
```



**How do I print two (or more plots, for that matter) from within an if block in the html document???**

The above is a MWE, but, in fact, in a more general setting I would have a large number of plots to be printed depending on several if else blocks...

Any suggestions are welcome!!

**Comment by yihui** [comment] 2017-10-10 21:15
Duplicate of #1069.

And similar questions have been asked many times on StackOverflow, e.g.,

- https://stackoverflow.com/q/30509866/559676
- https://stackoverflow.com/q/35431926/559676
- https://stackoverflow.com/q/35193612/559676
- https://stackoverflow.com/q/35951270/559676

For future questions instead of bug reports or feature requests, so please do us a favor to [ask them on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) instead (with a reproducible example) and let us know the link if you don't get an answer in a few days. Thanks!

**Closed by yihui** 2017-10-10 21:15 UTC
Labels: question
