### ISSUE TITLE
Conversion error using intermediates_dir

### ISSUE THREAD

**Issue by Enchufa2** [rstudio/rmarkdown#1300] opened 2018-03-23 16:53 UTC
Probably related to #1190, but I'm not sure, because the error is different. Here is a minimal example:

````r
vignette <- '
---
title: "Simple vignette"
---

```{r}
plot(1:10)
```
'
write(vignette, file = "simple.Rmd")
rmarkdown::render("simple.Rmd", intermediates_dir = tempdir())
#> processing file: simple.Rmd
#> ...
#> output file: /tmp/RtmpqjfDqr/simple.knit.md
#> ...
#> pandoc: Could not fetch simple_files/figure-html/unnamed-chunk-1-1.png
#> simple_files/figure-html/unnamed-chunk-1-1.png: openBinaryFile: does not exist (No such file or directory)
#> Error: pandoc document conversion failed with error 67
#> Also: Warning message:
#> In file.rename(from, to) :
#>   cannot rename file 'simple_files/figure-html' to '/tmp/RtmpqjfDqr/simple_files/figure-html', reason 'Invalid cross-device link'
````

I had some of these issues using `pkgdown`. Then I saw that `pkgdown` [sets the `intermediates_dir` option](https://github.com/r-lib/pkgdown/blob/master/R/rmarkdown.R#L20), which seems like a reasonable use case to me, and I tracked the bug up to here.

**Comment by rich-iannone** [comment] 2018-07-24 20:44
When I run the minimal example in my system. I get a rendered HTML document with no error:

<img width="945" alt="simple_vignette" src="https://user-images.githubusercontent.com/5612024/43164920-58db6be0-8f47-11e8-9745-2eb73b284f77.png">

Perhaps this has been fixed somewhere else or it has to do with Pandoc 1 or 2.

@yihui is there anything that needs to be done here? I might be missing something obvious.

**Comment by yihui** [comment] 2018-07-24 20:56
From the OP's error message:

> cannot rename file 'simple_files/figure-html' to '/tmp/RtmpqjfDqr/simple_files/figure-html', reason 'Invalid cross-device link'

It sounds like his Rmd file and `/tmp` dir are on different devices. You may try to reproduce by mounting an external disk. His OS appears to be Linux, so you may also try to reproduce on a Linux distro.

If you cannot reproduce anyway, try to find out the possible offending `file.rename()`, and fall back to `file.copy()` if renaming fails, e.g., https://github.com/rstudio/blogdown/commit/866fce947e05e3ac3de67baf1272515d5c119fed

**Comment by Enchufa2** [comment] 2018-07-24 21:21
Reprex rerun with R 3.5.0, pandoc 2.2.1; same error. And

```r
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Fedora 28 (Twenty Eight)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=es_ES.UTF-8       LC_NUMERIC=C               LC_TIME=es_ES.UTF-8        LC_COLLATE=es_ES.UTF-8    
 [5] LC_MONETARY=es_ES.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=es_ES.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=es_ES.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.5.0  backports_1.1.2 magrittr_1.5    rprojroot_1.3-2 htmltools_0.3.6 tools_3.5.0     yaml_2.1.19    
 [8] Rcpp_0.12.17.4  stringi_1.2.4   rmarkdown_1.10  knitr_1.20.8    xfun_0.3        stringr_1.3.1   digest_0.6.15  
[15] evaluate_0.11
```

The `/tmp` dir is *not* in a different device, despite the "reason" shown in the output.

**Comment by rich-iannone** [comment] 2018-07-24 21:35
I'm going to try to reproduce this on a Linux VM. Thanks @Enchufa2 for providing this session info!

**Comment by rich-iannone** [comment] 2018-07-25 20:20
I just tested on Ubuntu 18.04 (64-bit). Slightly older version of R and obviously a different Linux distro. Still, the document did render to HTML and didn't produce an error.

I'll update to 3.5.1 and try again. I'll also get a Fedora VM and test this there too.

```
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rmarkdown_1.10.8

loaded via a namespace (and not attached):
 [1] compiler_3.4.4  magrittr_1.5    htmltools_0.3.6 tools_3.4.4     yaml_2.2.0      Rcpp_0.12.18   
 [7] stringi_1.2.4   knitr_1.20      htmldeps_0.1.1  digest_0.6.15   stringr_1.3.1   evaluate_0.11 
```

**Comment by Enchufa2** [comment] 2018-07-25 21:02
My previous run was with the CRAN version. I tried again with the development version (i.e., v1.10.8), and same error. I tried changing the locale, same error.

**Comment by Enchufa2** [comment] 2018-07-25 21:37
I tried on Debian (rocker/r-base) and the document renders ok. The only difference AFAIK is that, on Fedora, the `/tmp` dir is a `tmpfs` filesystem. Hope it helps.

**Comment by rich-iannone** [comment] 2018-07-25 21:50
That helps a lot! I'll try it out on Fedora. Thanks for the testing and the extra info.

**Comment by rich-iannone** [comment] 2018-08-01 15:32
I hadn't mentioned it yet but I was able to reproduce the issue on Fedora Linux. Will try the `file.copy()` in place of `file.rename()` where necessary.

**Comment by yihui** [comment] 2018-12-06 21:57
I have applied the `file.copy()` fix. This issue should be fixed now. Please test it with `remotes::install_github('rstudio/rmarkdown')`. Thanks for the report!

**Closed** 2018-12-06 21:56 UTC
