### ISSUE TITLE
mathjax in html_fragment

### ISSUE THREAD

**Issue by stla** [rstudio/rmarkdown#436] opened 2015-05-27 11:40 UTC
Hello,
In order to get a html fragment with appropriate Mathjax code I use the `output_format` 
```
html_fragment(mathjax="default", self_contained=FALSE)
```
*But* I had to modify the `html_fragment` function, because it forces `mathjax=NULL`.

**Comment by jjallaire** [comment] 2015-05-27 12:24
That is by design. If you are creating a fragment it implies that you are
including it within a larger page (e.g. a blog or content management
system) which makes it's own provision for including MathJax.

**Comment by stla** [comment] 2015-05-27 12:45
I don't follow you. This `Rmd` file:
```
Hello 
$$
\sum_{i=1}^n i^2.
$$

Hi $\sum_{i=1}^n i^2$. 
``` 
compiled with `render(Rmdfile, output_format="html_fragment")`, generates this `html` file:
```
<p>Hello</p>
<p><br /><span class="math">∑<sub><em>i</em> = 1</sub><sup><em>n</em></sup><em>i</em><sup>2</sup>.</span><br /></p>
<p>Hi <span class="math">∑<sub><em>i</em> = 1</sub><sup><em>n</em></sup><em>i</em><sup>2</sup></span>.</p>
```
It is absolutely not ready for Mathjax, is it ?

**Comment by stla** [comment] 2015-05-27 12:48
whereas using my way, I get: 
```
<p>Hello <span class="math">\[
\sum_{i=1}^n i^2.
\]</span></p>
<p>Hi <span class="math">\(\sum_{i=1}^n i^2\)</span>.</p>
```
which is ready for Mathjax.

**Comment by jjallaire** [comment] 2015-05-27 12:49
You are correct, there is an issue here. I'll try to resolve this soon!

**Comment by stla** [comment] 2015-05-27 12:50
:-) :+1:

**Comment by jjallaire** [comment] 2015-05-27 20:46
Fixed via: https://github.com/rstudio/rmarkdown/commit/72c3a1ec5ef0d5d0753fe8f7cea11fcedbd5891c

**Closed by jjallaire** 2015-05-27 20:46 UTC
