### ISSUE TITLE
Rmarkdown crash with dyn.load DLL

### ISSUE THREAD

**Issue by stla** [rstudio/rmarkdown#1080] opened 2017-06-09 21:15 UTC
Hello, 

 I can call some DLLs in R without any issue. But when I call them in a Rmarkdown document, the compilation crashes (with or without RStudio).

 Below are some examples of my calls to the DLLs:
```
> dyn.load("FloatExpansion1.dll")
> .C("HsStart")
list()
> .C("floatExpansion", base=2L, x=0.125, result="")$result
[1] "[0,0,1]"
> dyn.unload("FloatExpansion1.dll")
```

```
> dyn.load("FloatExpansion2.dll")
> .C("HsStart")
list()
> .C("floatExpansion", base=2L, x=0.125, result=list(0L))$result
[[1]]
[1] 0 0 1

> floatExpand <- function(x, base=2L){
+   .C("floatExpansion", base=as.integer(base), x=as.double(x), result=list(integer(1)))$result[[1]]  
+ }
> floatExpand(1/3+1/27, base=3)
[1] 1 0 1
> dyn.unload("FloatExpansion2.dll")
```

As you can see, there's no issue. The results are the expected ones, and there's no crash.

But when I run this Rmarkdown document, the compilation crashes (sometimes it totally crashes the R session):

![a1](https://user-images.githubusercontent.com/4466543/26994741-2b88062e-4d69-11e7-8392-8821a38360c4.png)
![a2](https://user-images.githubusercontent.com/4466543/26994743-323c430e-4d69-11e7-97f2-7871aefa3f47.png)
![a3](https://user-images.githubusercontent.com/4466543/26994748-36816c0a-4d69-11e7-85ef-4f2e38a8bd70.png)

Is it a known issue? Would it help if I share the `Rmd` and the DLLs ?

**Comment by stla** [comment] 2017-06-09 21:33
It seems that the problem is cause by `dyn.unload`. 
That's annoying in my case because I call two DLL containing the same function names, so I have to unload the first one.

**Comment by issactoast** [comment] 2017-08-03 12:20
Same here, anybody can solve this issue?

**Comment by stla** [comment] 2017-08-03 12:22
@issactoast 
As a workaround, you can use the `cache=TRUE` option and compile the document several times...

**Comment by issactoast** [comment] 2017-08-03 13:27
@stla thank you for the reply, still have some problem. 

I found a difference between your rmarkdown and mine. Do I have to use dyn.load and unload every time when I use function connected to '.so' file even in rmarkdown? I wrote the following rmarkdown and tried to run  the dpareto function in the chuck to check. It works for the first several times, in 3rd or 4th time the rstudio ends up with crash. Also I cannot knit them, but I can knit the document if I us dpareto function only one time in the chunk.

![screenshot_20170803_080847](https://user-images.githubusercontent.com/13303749/28923356-5ade16ea-7823-11e7-9776-5541e121f077.png)

**Comment by stla** [comment] 2017-08-03 16:46
Sorry I don't know. I only call the functions one time in my case. I put `cache=TRUE` in every chunk related to the call to the DLL (including dyn.load and dyn.unload). RStudio crashes but at the end the cache is done.

**Comment by issactoast** [comment] 2017-08-03 20:26
@stla  In my case, my C code had a bug, I used sizeof function to the array in the paretodens function which put me in a trouble. But it hard to see when I use Rstudio with C code since it does not say where the error occurred. Now I can knit without cache=TRUE option. work as an usual rmarkdown.

**Comment by yihui** [comment] 2017-10-10 04:09
It seems both of you have found solutions (at least workarounds), so I'm closing this issue. If you need us to investigate it, you will have to provide a complete reproducible example. Thanks!

**Closed by yihui** 2017-10-10 04:09 UTC

**Comment by stla** [comment] 2017-10-10 10:05
Hello @yihui ,

 If you want to investigate, here is a minimal reproducible example.

The DLL is [here](https://www.dropbox.com/s/nubysmniymjbeww/smallDLL.dll?dl=0).

The `Rmd` file is [here](https://gist.githubusercontent.com/stla/8926d42cf18e71dcac0f03705d55cff0/raw/b2442819a93911db5bdda9d8fa354e7add0265c5/bugDLL.Rmd).

**Comment by yihui** [comment] 2017-10-10 13:39
Thanks @stla! That is very helpful. I'm afraid this won't be of high priority, though, given that there are still a large number of other issues to solve.

**Comment by stla** [comment] 2017-12-18 19:13
I've just tried with some DLLs generated from a more recent version of `gcc`, and there's no issue. Looks like the issue depends on the DLLs. I think it's not worth spending much time on this issue.

**Comment by yihui** [comment] 2017-12-18 19:20
Okay, thanks!
