### ISSUE TITLE
web hosted css files not loading anymore in ioslides

### ISSUE THREAD

**Issue by ShKlinkenberg** [rstudio/rmarkdown#1636] opened 2019-09-02 07:28 UTC
@yihui In a recent update to rmarkdown ioslides the ability to host css files externally in the YAML header disappeared. 

I posted the question on [stackoverflow here](https://stackoverflow.com/questions/57071064/github-hosted-css-files-not-loading-anymore-in-ioslides) to no avail.

I'm really missing the feature. Is it coming back or do I have to do without?

**Comment by atusy** [comment] 2019-09-02 22:18
It seems to be a Chrome's issue. Working fine with Firefox.

**Comment by yutannihilation** [comment] 2019-09-03 02:27
Not sure what change causes this (I don't know if this used to work before), but I got this diff between `css: https://shklinkenberg.github.io/uva_style/ioslides_style.css` (web hosted) and `css: /path/to/ioslides_style.css` (local):

``` diff
--- ioslides.html	2019-09-03 11:20:01.000000000 +0900
+++ ioslides_local.html	2019-09-03 11:19:56.000000000 +0900
@@ -3109,7 +3109,7 @@
     }
   </style>
 
-  <style type="text/css; charset=utf-8">slides > slide { border-radius: 30px; border: solid 3px white; }
+  <style type="text/css">slides > slide { border-radius: 30px; border: solid 3px white; }
 slide.fill.nobackground.current { border-radius: 30px; border: solid 3px white; }
 .segue.nobackground.level1.fill.current { border-radius: 30px; }
 slides > slide.dark {
```

**Comment by atusy** [comment] 2019-09-03 03:05
@yutannihilation Good point!

Chromium applies CSS correctly when `; charset=utf-8` is removed.

**Comment by atusy** [comment] 2019-09-03 03:48
I manually converted markdown file with a following line in the body.

```html
<link rel="stylesheet" href="https://shklinkenberg.github.io/uva_style/ioslides_style.css" type="text/css" />
```

The conversion is done by:

```bash
/usr/bin/pandoc +RTS -K512m -RTS test.md --to html4 --output test.html --email-obfuscation none --self-contained --metadata pagetitle=test
```

As a result, I confimed that self contained stylesheet starts from

```html
<style type="text/css; charset=utf-8">slides >
```

This means the issue is partly caused by Pandoc in addition to browsers.

**Comment by yutannihilation** [comment] 2019-09-03 04:00
According to the [Mozilla's document](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style#Specifications):

> This attribute defines the styling language as a MIME type (charset should not be specified).

So, I think Chrome does the right thing (while Firefox's tolerant behavior is also OK, probably).

IIRC, pandoc respects the MINE type that the server returned. I guess it's the cause of the problem here.

``` console
$ curl -s -I https://shklinkenberg.github.io/uva_style/ioslides_style.css | grep 'content-type'
content-type: text/css; charset=utf-8
```

**Comment by atusy** [comment] 2019-09-03 04:14
Hmm... so is there anything we can do?
One thing I come up with is to remove charset by post processor.
However, in this case, it is difficult to determine whether the charset is inserted by user or by rendering.

I wish if Pandoc does not specify the type attribute because Mozilla's document says "there is very little reason to include this in modern web documents", though I do not know a minor case which requires MIME type.

**Comment by yutannihilation** [comment] 2019-09-03 05:34
> is there anything we can do?

*If* this used to work, I think you might be able to restore the behavior before. But, I doubt it; probably this is caused not by "a recent update to rmarkdown," but by an update to RStudio, more precisely, the update to pandoc at this commit:

https://github.com/jgm/pandoc/commit/8d4fbe6a2a50d93bff0e9c7ada73774ff1bc17c6#diff-e4142091d8b82884f712082e419341b0L128

**Comment by cderv** [comment] 2019-09-03 06:08
So this may be a pandoc issue to report ? I don't find one open yet on this.  🤔

**Comment by yutannihilation** [comment] 2019-09-03 07:19
Yes, I will!

Now I confirmed the value `text/css; charset=utf-8` violates [the specification of HTML Standard](https://html.spec.whatwg.org/multipage/semantics.html#the-style-element) as it notes ("return early" means "doesn't create a CSS style sheet" here):

> In particular, a type value with parameters, such as "text/css; charset=utf-8", will cause this algorithm to return early.

(So, I might need to report to Firefox as well...?)

**Comment by atusy** [comment] 2019-09-03 07:32
Thanks a lot!

**Comment by yutannihilation** [comment] 2019-09-04 01:08
This is fixed on Pandoc's side (so quick!), though I'm afraid it might take a year or so until the version (>= 2.8) of Pandoc is released and is bundled with RStudio...

**Comment by cderv** [comment] 2019-09-04 05:55
> I'm afraid it might take a year or so until the version (>= 2.8) of Pandoc is released
release schedule seems quicker. https://pandoc.org/releases.html
last is from June and, previous was April.

> and is bundled with RStudio. 
There, I don't know the schedule for RStudio IDE. It may be useful to open an issue in rstudio ide repository to ask for 2.8 bundled when it will go out, don't you think ?

**Comment by ShKlinkenberg** [comment] 2019-09-04 08:15
Thanks, everyone for jumping on this. I can confirm that firefox on a MAC also works. for now, I will use Firefox. Thanks a lot. It would be great if the Rstudio IDE would integrate the updated pandoc.

**Comment by yihui** [comment] 2019-09-04 15:40
@ShKlinkenberg As @yutannihilation said, it usually takes long for RStudio to upgrade its bundled Pandoc. However, you can choose to install Pandoc by yourself once the new version is released, and **rmarkdown** will automatically pick the newer version.

Since there isn't anything else we could do on our side, I'm going to close this issue. Thanks everyone for the help!

**Closed by yihui** 2019-09-04 15:40 UTC
