### ISSUE TITLE
Fail with mathjax, files are not compiling

### ISSUE THREAD

**Issue by mynameislaure** [rstudio/rmarkdown#1009] opened 2017-03-30 00:06 UTC
I'm not able to compile my rmd's for html. It seems the problem is with mathjax.
I tried the YAML options self_contained: no and mathjax: local but they did not work.

I think the problem is with the last update, since Travis is giving failing.

**Comment by jjallaire** [comment] 2017-03-30 01:16
The build was failing due to some documentation that had not been regenerated (should be fixed now). All the tests are passing and the new version has been on CRAN for over a week with thousands of downloads so I don't think there is a general issue here. 

In order to sort out what's going on in your configuration we'll need a simple reproducible case.

**Closed** 2017-04-06 23:58 UTC
