### ISSUE TITLE
[WARNING] This document format requires a nonempty <title> element.

### ISSUE THREAD

**Issue by slowkow** [rstudio/rmarkdown#1424] opened 2018-08-08 02:07 UTC
It seems that the table of contents is broken. This always worked for me in the past, but today it failed.

The content of the Rmd file does not seem to matter, but I included my document below anyway.

The metadata YAML in my document looks like this:

````
---
title: "Habits"
output:
  html_document:
    toc: yes
pagetitle: Habits
---
````

If I include the `toc: yes` in the metadata YAML, then it fails like this:

![43811869-bf63f8be-9a8c-11e8-883d-d9fbc8f12384](https://user-images.githubusercontent.com/209714/43812046-6e692960-9a8d-11e8-83d0-ec751a428e85.png)

Here is the output in the RStudio `R Markdown` tab:

```
/usr/local/bin/pandoc +RTS -K512m -RTS Untitled.utf8.md --to html4 --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash+smart --output /private/var/folders/k5/ynx90ngs6_7f7pcdkb77tp088qtqn4/T/Rtmp2q8yMc/preview-24ad4796ce27.dir/Untitled.html --email-obfuscation none --self-contained --standalone --section-divs --table-of-contents --toc-depth 3 --template /Library/Frameworks/R.framework/Versions/3.5/Resources/library/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --variable 'theme:bootstrap' --include-in-header /var/folders/k5/ynx90ngs6_7f7pcdkb77tp088qtqn4/T//Rtmpb4eU1A/rmarkdown-str41ba5503d07b.html --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' 
output file: Untitled.knit.md

[WARNING] This document format requires a nonempty <title> element.
  Please specify either 'title' or 'pagetitle' in the metadata.
  Falling back to 'Untitled.utf8'

Output created: /private/var/folders/k5/ynx90ngs6_7f7pcdkb77tp088qtqn4/T/Rtmp2q8yMc/preview-24ad4796ce27.dir/Untitled.html
```

If I omit the `toc: yes` from the metadata YAML, then the document renders correctly like this:

![image](https://user-images.githubusercontent.com/209714/43811920-fd7d6428-9a8c-11e8-805b-c392e1633cc9.png)

## System information

```
$ /usr/local/bin/pandoc --version
pandoc 2.2.3
Compiled with pandoc-types 1.17.5.1, texmath 0.11.0.1, skylighting 0.7.2
Default user data directory: /Users/slowikow/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

```
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.18      packrat_0.4.9-3   digest_0.6.15     withr_2.1.2      
 [5] rprojroot_1.3-2   R6_2.2.2          backports_1.1.2   git2r_0.23.0     
 [9] magrittr_1.5      evaluate_0.11     httr_1.3.1        stringi_1.2.4    
[13] curl_3.2          rmarkdown_1.10.11 devtools_1.13.6   tools_3.5.1      
[17] stringr_1.3.1     yaml_2.2.0        compiler_3.5.1    memoise_1.1.0    
[21] htmltools_0.3.6   knitr_1.20       
```

## Document

````
---
title: "Habits"
output:
  html_document:
    toc: yes
pagetitle: Habits
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.

When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:

```{r cars}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
````

**Comment by yihui** [comment] 2018-08-08 03:02
Duplicate of #1423

**Closed by yihui** 2018-08-08 03:02 UTC
