### ISSUE TITLE
YAML with more than one level of indentation incorrectly parsed, printed

### ISSUE THREAD

**Issue by genos** [rstudio/rmarkdown#1423] opened 2018-08-06 18:46 UTC
First off, thank you _very_ much for `rmarkdown`; it's really made my work a lot easier.

As for my issue, after a recent update, `rmarkdown` seems to incorrectly parse YAML headers with more than one level of indentation, specifically if the `output` argument has further arguments itself. Instead of setting those arguments and using them, they're showing up as a table in both PDF and LaTeX documents.

Here are my attempts at minimal examples.

```Rmd
---
title: "Minimal failing example"
author: "Me"
output:
  pdf_document:
    df_print: kable
    latex_engine: xelatex
---

`r suppressMessages(library(tidyverse)); data_frame(x = rnorm(5), y = rbeta(5, pi, pi))`
```

produces the following PDF (screenshotted here):

<img width="911" alt="screen shot 2018-08-06 at 2 41 31 pm" src="https://user-images.githubusercontent.com/884550/43734809-eaa5605a-9986-11e8-9760-6b55fa0e8f23.png">

The same issues persist when trying to make a LaTeX document:

```Rmd
---
title: "Minimal failing example"
author: "Me"
output:
  latex_document:
    df_print: kable
    latex_engine: xelatex
---

`r suppressMessages(library(tidyverse)); data_frame(x = rnorm(5), y = rbeta(5, pi, pi))`
```

Creates the following tex output (clipped):

```tex

  \title{}
    \pretitle{\vspace{\droptitle}}
  \posttitle{}
    \author{}
    \preauthor{}\postauthor{}
    \date{}
    \predate{}\postdate{}
  

\begin{document}

\begin{longtable}[]{@{}l@{}}
\toprule
\endhead
title: ``Minimal failing example''\tabularnewline
author: ``Me''\tabularnewline
output:\tabularnewline
latex\_document:\tabularnewline
df\_print: kable\tabularnewline
latex\_engine: xelatex\tabularnewline
\bottomrule
\end{longtable}

\begin{longtable}[]{@{}rr@{}}
\toprule
x & y\tabularnewline
\midrule
\endhead
1.8603112 & 0.4759930\tabularnewline
-2.3347380 & 0.3936435\tabularnewline
0.9475931 & 0.5313417\tabularnewline
1.0003588 & 0.3140955\tabularnewline
-2.5464222 & 0.7279063\tabularnewline
\bottomrule
\end{longtable}


\end{document}
```

I've also attached a [`.zip` of all the files](https://github.com/rstudio/rmarkdown/files/2263679/err.zip). My session info:
```
> sessioninfo::session_info("rmarkdown")
─ Session info ───────────────────────────────────────────────────────────────
 setting  value
 version  R version 3.5.1 (2018-07-02)
 os       macOS High Sierra 10.13.6
 system   x86_64, darwin17.6.0
 ui       unknown
 language (EN)
 collate  en_US.UTF-8
 tz       America/New_York
 date     2018-08-06

─ Packages ───────────────────────────────────────────────────────────────────
 package   * version date       source
 base64enc   0.1-3   2015-07-28 CRAN (R 3.5.0)
 digest      0.6.15  2018-01-28 CRAN (R 3.5.0)
 evaluate    0.11    2018-07-17 cran (@0.11)
 glue        1.3.0   2018-08-06 Github (tidyverse/glue@a292148)
 highr       0.7     2018-06-09 cran (@0.7)
 htmldeps    0.1.1   2018-08-06 Github (rstudio/htmldeps@c1023e0)
 htmltools   0.3.6   2017-04-28 CRAN (R 3.5.0)
 jsonlite    1.5     2017-06-01 CRAN (R 3.5.0)
 knitr       1.20    2018-02-20 CRAN (R 3.5.0)
 magrittr    1.5     2014-11-22 CRAN (R 3.5.0)
 markdown    0.8     2017-04-20 CRAN (R 3.5.0)
 mime        0.5     2016-07-07 CRAN (R 3.5.0)
 Rcpp        0.12.18 2018-07-23 cran (@0.12.18)
 rmarkdown   1.10.10 2018-08-06 github (rstudio/rmarkdown)
 stringi     1.2.4   2018-07-20 cran (@1.2.4)
 stringr   * 1.3.1   2018-05-10 CRAN (R 3.5.0)
 tinytex     0.6     2018-07-07 cran (@0.6)
 xfun        0.3     2018-07-06 cran (@0.3)
 yaml        2.2.0   2018-07-25 cran (@2.2.0)
```

Thank you very much for your help!

**Comment by yihui** [comment] 2018-08-07 03:39
What is your `rmarkdown::pandoc_version()`? I cannot reproduce your issue with Pandoc 2.2.1 (which is the version that the current preview version of RStudio ships).

**Comment by eorn** [comment] 2018-08-07 10:10
Same problem for me with `pandoc 2.2.3`. With `pandoc 2.2.1`, everything is fine.

**Comment by jjallaire** [comment] 2018-08-07 11:30
It looks like this was a regression in pandoc v2.2.3 which has subsequently been fixed by this patch release: https://github.com/jgm/pandoc/releases/tag/2.2.3.1

**Comment by genos** [comment] 2018-08-07 15:07
Thanks for the speedy replies! Looking at my `pandoc` version:
```r
> rmarkdown::pandoc_version()
[1] ‘2.2.3’
```
I had installed `pandoc` system-wide via `brew`, which means I do indeed have `2.2.3` installed everywhere. Upgrading my `pandoc` installation via `brew unlink pandoc; brew install pandoc --HEAD` means I now have 2.2.3.1:
```zsh
$ pandoc --version
pandoc 2.2.3.1
```

And everything seems to work as expected!

 I'm not sure the best next step for this issue; should we close it as fixed by updating `pandoc`? Thanks again for everyone's time and help with this, I really appreciate it.

**Comment by yihui** [comment] 2018-08-07 20:33
Yes, I think we can close it, since it is an upstream bug that has been fixed. Thanks for the report!

**Closed by yihui** 2018-08-07 20:33 UTC
Labels: Difficulty: Intermediate, Effort: Medium, Priority: High

**Comment by cucumberry** [comment] 2018-12-12 13:40
I also have this issue with Pandoc 2.5, for what it's worth

**Comment by yihui** [comment] 2018-12-12 14:35
@cucumberry Reprex please. I cannot reproduce it with Pandoc 2.5.

**Comment by bjhufstetler** [comment] 2020-08-24 17:16
I just had this same issue with a deployment that worked fine just hours before. The problem was that my local machine didn't have enough spare memory to support the deployment. I freed up some space and it worked just fine afterwards.
