### ISSUE TITLE
rmarkdown::render issue when calling render interacitvely

### ISSUE THREAD

**Issue by mkirzon** [rstudio/rmarkdown#1614] opened 2019-08-02 17:49 UTC
I found an issue where dataframes are not printing when calling `rmarkdown::render` from a chunk. 

To reproduce, create an RMarkdown file `test.Rmd` with the following contents and open it in RStudio: 

````
---
title: "Render Issue"
author: "Mark Kirzon"
date: "8/2/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache=FALSE)
library(tidyverse)   
```

This prints fine when the document is knit with the 'Knit' button or Ctrl+Shift+K
```{r}
a = data.frame(A = c(1:5), B = head(LETTERS, 5), stringsAsFactors = F)
print(a)
```

If this chunk is executed, the above dataframe is not displayed in the output html. I expected the behavior to be the same. 
```{r, eval=FALSE, include=FALSE}
rmarkdown::render("test.Rmd")
```
````

This is what it looks like when knit using the button/keyboard shortcut:
![image](https://user-images.githubusercontent.com/5666220/62388599-9c6def80-b512-11e9-8788-47ab60642585.png)

This is what it looks like when executing the block: 
![image](https://user-images.githubusercontent.com/5666220/62388584-92e48780-b512-11e9-88ef-e478b2014949.png)

I think this is a bug as I am unable to print a normal dataframe when executing a chunk with the `rmarkdown::render` call. Note that it works fine if the same `rmarkdown::render` is run from the command line, rather than executed as a chunk. 

### Why I need to be able to execute from a chunk 
I like to include a chunk at the end of my analyses that has the various parametrization configurations that I frequently need to loop over. I've found it's really convenient and organized when all parametrizations are stored with the analysis. Here's the template that I include at the end of my analyses, which loops over N parameter configurations and updates the N html files. 
````
```{r looped_render, include=FALSE, eval=FALSE}
# Run this chunk interactively to render this document with custom parameters, to a custom destination

# Configure Output and parameters
path_out      = "" # If empty, current directory
output_prefix = tools::file_path_sans_ext(basename(rstudioapi::getSourceEditorContext()$path)) # Output filename, needs to be non-empty
list_params = list(list()) # This is a list of lists. Leave as is if the document has no parameters

for (params_tmp in list_params) {
  print(params_tmp)
  
  output_fn = sprintf("%s%s.html", output_prefix, paste(names(params_tmp), unname(params_tmp), sep= "_", collapse = "&"))
  
  rmarkdown::render(
    input         = basename(rstudioapi::getSourceEditorContext()$path),
    output_file   = file.path(path_out, output_fn),
    params        = params_tmp)
}
```
````

**Comment by mkirzon** [comment] 2019-08-02 17:50
```
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] forcats_0.2.0   stringr_1.2.0   dplyr_0.8.0.1   purrr_0.3.2     readr_1.1.1     tidyr_0.8.1     tibble_2.1.1    ggplot2_3.1.0   tidyverse_1.2.1

loaded via a namespace (and not attached):
 [1] tidyselect_0.2.5      xfun_0.7              reshape2_1.4.3        haven_2.0.0           lattice_0.20-35       colorspace_1.3-2     
 [7] htmltools_0.3.6       yaml_2.2.0            rlang_0.3.4           pillar_1.3.1          foreign_0.8-69        glue_1.3.1           
[13] withr_2.1.0           lambda.r_1.2          modelr_0.1.1          readxl_1.0.0          plyr_1.8.4            munsell_0.5.0        
[19] gtable_0.2.0          futile.logger_1.4.3   cellranger_1.1.0      rvest_0.3.2           psych_1.7.8           evaluate_0.14        
[25] knitr_1.23            parallel_3.4.2        broom_0.4.3           Rcpp_1.0.1            scales_1.0.0          jsonlite_1.5         
[31] mnormt_1.5-5          digest_0.6.15         hms_0.4.2             stringi_1.1.6         grid_3.4.2            cli_1.1.0            
[37] tools_3.4.2           magrittr_1.5          lazyeval_0.2.1        futile.options_1.0.0  crayon_1.3.4          pkgconfig_2.0.2      
[43] Matrix_1.2-11         xml2_1.1.1            lubridate_1.7.1       assertthat_0.2.1      rmarkdown_1.14        httr_1.3.1           
[49] rstudioapi_0.7.0-9000 R6_2.4.0              nlme_3.1-131          compiler_3.4.2       
```

**Comment by mkirzon** [comment] 2019-08-02 17:58
My current workaround is to use `formattable`

**Comment by cderv** [comment] 2019-12-28 21:13
Hi @mkirzon , 

I tried to reproduce without success. I don't know what is inside your test.Rmd file I guess.

You seem to have `rmarkdown_1.14`  and `knitr_1.23`in your session info. Can you try again after updating ? CRAN version are 2.0 for rmarkdown and 1.26 for knitr. 

Thank you.

**Comment by mkirzon** [comment] 2020-01-02 22:41
Hi @cderv,
I just reran with those updated packages and am still seeing the same issue. I reproduced the error on a 2nd machine as well. 

Latest sessionInfo: 
```
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] forcats_0.2.0   stringr_1.4.0   dplyr_0.8.0.1   purrr_0.3.2     readr_1.1.1     tidyr_0.8.3     tibble_2.1.1    ggplot2_3.1.0   tidyverse_1.2.1

loaded via a namespace (and not attached):
 [1] tidyselect_0.2.5      xfun_0.7              reshape2_1.4.3        haven_2.0.0           lattice_0.20-35       colorspace_1.3-2     
 [7] htmltools_0.3.6       yaml_2.2.0            rlang_0.4.2           pillar_1.3.1          foreign_0.8-69        glue_1.3.1           
[13] withr_2.1.2           modelr_0.1.1          readxl_1.0.0          plyr_1.8.4            munsell_0.5.0         gtable_0.2.0         
[19] cellranger_1.1.0      rvest_0.3.2           psych_1.7.8           evaluate_0.14         knitr_1.26            parallel_3.4.2       
[25] broom_0.4.3           Rcpp_1.0.1            scales_1.0.0          jsonlite_1.5          mnormt_1.5-5          hms_0.4.2            
[31] digest_0.6.15         stringi_1.4.3         grid_3.4.2            cli_1.1.0             tools_3.4.2           magrittr_1.5         
[37] lazyeval_0.2.1        crayon_1.3.4          pkgconfig_2.0.2       xml2_1.1.1            lubridate_1.7.1       assertthat_0.2.1     
[43] rmarkdown_2.0         httr_1.4.1            rstudioapi_0.7.0-9000 R6_2.4.0              nlme_3.1-131          compiler_3.4.2 
```

**Comment by cderv** [comment] 2020-01-03 06:25
OK. Can you help me reproduce ? What is inside `test.Rmd` that you render at the end in your last chunk ?

**Comment by mkirzon** [comment] 2020-01-07 21:41
The code block in my original post is that very same `test.Rmd`. Sorry for that confusion!

**Comment by mkirzon** [comment] 2020-03-27 00:49
Hi @cderv , I can confirm we have other folks on different laptops running into this same issue. Any thoughts on what may be going on?

**Comment by cderv** [comment] 2020-03-27 07:43
Ok I can reproduce now. This is odd. 
as it works at command line in console 
```r
knitr::opts_chunk$set(echo = TRUE, cache=FALSE)
library(tidyverse)
rmarkdown::render("test.Rmd")
```
but not when run from a chunk, I suspect something related to Rstudio IDE, where some general context options must be change when executing code from a chunk. 
RStudio IDE has a default behavior with Rmd to output chunk result under the chunk. You can change this to output the chunk result to console by using the menu in IDE or adding yourself this in yaml
```yaml
editor_options: 
  chunk_output_type: console
```
If you add this, it seems to work fine. Can you try ? 

This would confirm for me that this is an issue related to RStudio IDE.

**Comment by kevinushey** [comment] 2020-03-27 19:03
As a workaround, I would recommend executing `render()` within a sub-process, e.g.

`````
```{r, eval=FALSE, include=FALSE}
callr::r(function() {
  rmarkdown::render("test.Rmd")
})
```
`````

**Comment by mkirzon** [comment] 2020-03-27 20:48
@cderv That actually didn't work for me either. It's still rendering without the table. 
@kevinushey that workaround looks like it's working. I never even knew about `callr` :)

Does this seem like it's an issue to escalate to RStudio?

**Comment by cderv** [comment] 2020-03-27 21:19
@mkirzon I forget to precise but I ran the code with RStudio preview version 1.3.911. 
With RStudio version 1.2.5033 it does not work for me either.

**Comment by yihui** [comment] 2020-05-29 04:41
@mkirzon I also strongly recommend that if you need to `render()` one Rmd file within another Rmd file, you do it in a separate R process, because `render()` has a lot of side-effects while running (you can blame us for this problem...). Besides `callr::r()`, you could also try `xfun::Rscript_call()`, e.g.,

```r
xfun::Rscript_call(
  rmarkdown::render,
  list(input         = basename(rstudioapi::getSourceEditorContext()$path),
       output_file   = file.path(path_out, output_fn),
       params        = params_tmp)
)
```

The very minor advantage is that the **xfun** package is already a dependency of **rmarkdown** so you don't need to install it, and `Rscript_call()` doesn't have other dependencies (i.e., it is fairly lightweight).

**Comment by cderv** [comment] 2021-01-14 15:57
I believe this happens because the IDE is overriding some method for printing when `chunk_output_type` is set to inline. One of them is `print.data.frame`. This will impact the call to `render` done in in the chunk executed from the IDE. 

If you render from a background process this won't happen. 

So I'll close this issue as the recommended way of doing that is to run the document in another clean process. and because you can also set the `chunk_output_type` to be the console and then it will work as is the code is executed directly in the console with no modification on output. 

If you want this to be considered this would be an issue to open in the RStudio IDE. It is not something that can be change in **rmarkdown** itself.

**Closed by cderv** 2021-01-14 15:57 UTC
Labels: RStudio IDE
