### ISSUE TITLE
ioslides render blank slides with shiny runtime

### ISSUE THREAD

**Issue by xlai** [rstudio/rmarkdown#862] opened 2016-11-08 16:17 UTC
slidy works fine, so does html document with runtime set to shiny. Shiny app runs fine in console.

shiny version: 0.14.2
rmarkdown version: 1.1.9014
pandoc version: 1.18

This can be reproduced by creating a new shiny presentation with Rstudio.

Is there anyway I can find out where the problem is? Thank you

**Comment by jjallaire** [comment] 2016-11-08 16:33
Did you find a solution? I am able to reproduce the problem locally but haven't yet discovered what is going wrong.

**Comment by jjallaire** [comment] 2016-11-08 17:11
@jmcphers This is the commit that broke it: https://github.com/rstudio/rmarkdown/commit/6d6b24d8

This was part of my making the transition to using html dependencies rather than ad-hoc file copying for ioslides js and css. As a result of HTML dependencies the ioslides JS is now run in the head tag (rather than at the end of the document). This caused the problem that `document.body` is not yet defined, so I changed the code to trigger on `DOMContentLoaded`. My guess is that this messes with `runtime: shiny` since the `DOMContentLoaded` event has already been triggered by the time these dependencies are injected.

Note that as part of this change I actually eliminated the classList polyfill entirely (since we aren't really targeting older versions of IE with ioslides).

I think you'll have a better idea for how to get the initialization semantics right for both static and `runtime: shiny` cases. Let me know what you think.

**Comment by xlai** [comment] 2016-11-08 18:00
@jjallaire No but when I reinstalled `rmarkdown` package through RStudio, it was downgraded to ver 1.1 and everything is fine for now. I thought it was my own problem hence closing of case.

**Comment by jmcphers** [comment] 2016-11-08 18:04
@jjallaire I'll take a look.

**Comment by jjallaire** [comment] 2016-11-08 18:51
Thanks!

**Comment by jmcphers** [comment] 2016-11-08 19:17
Addressed in https://github.com/rstudio/rmarkdown/pull/863.

**Closed** 2016-11-08 19:40 UTC
