### ISSUE TITLE
MAC users: R markdown does not knit PDF beamer

### ISSUE THREAD

**Issue by ga122493** [rstudio/rmarkdown#1360] opened 2018-05-29 23:48 UTC
Hello,

I am trying to knit pdf slides (pdf beamer) but R markdown does not work... However, regular pdf knitting and html slides knitting work fine. 

The first part of my code is 
```{r}
---
title: "xxx"
author: "xxx"
date: "`r Sys.Date()`"
output:
  beamer_presentation:
    includes:
      after_body: ~/Dropbox/Lecture 3/table-of-contents.txt
      in_header: ~/Dropbox/Lecture 3/Example-header-simple.txt
    slide_level: 3
  ioslides_presentation: default
  slidy_presentation: default
fontsize: 9pt
---
### Texts
xxxxx
```

Based on this post https://github.com/rstudio/rmarkdown/issues/1285, I tried
1.  downgrade to RMarkdown v1.8
```{r}
devtools::install_version("rmarkdown", version = "1.8", repos = "http://cran.us.r-project.org")
```
    then the error was 
```{r}
Error producing PDF.

Error: pandoc document conversion failed with error 43
Execution halted
```

2. install rmarkdown and tinytex from cran
```{r}
install.packages(c('rmarkdown', 'tinytex'))
```
    then the error was 
```{r}
Output created: Lecture3_slides-flight.pdf
Error in tools::file_path_as_absolute(output_file) : 
  file 'Lecture3_slides-flight.pdf' does not exist
Calls: <Anonymous> -> <Anonymous>
In addition: Warning message:
In file.rename(file_with_ext(texfile, "pdf"), output_file) :
  cannot rename file 'Lecture3_slides-flight.pdf' to 'Lecture3_slides-flight.pdf', reason 'No such file or directory'
Execution halted
```

Please help!!!!
Thank you very much

**Comment by NMarkgraf** [comment] 2018-06-12 12:13
Please try the following:

1. Change your YAML to:

```
---
title: "xxx"
author: "xxx"
date: "`r Sys.Date()`"
output:
  beamer_presentation:
    includes:
      after_body: "~/Dropbox/Lecture 3/table-of-contents.txt"
      in_header: "~/Dropbox/Lecture 3/DOROS-beamer-header-simple.txt"
    slide_level: 3
  ioslides_presentation: default
  slidy_presentation: default
fontsize: 9pt
---
### Texts
xxxxx
```

2. If that won't fix it, please rename for diretory from "Lecture 3" to something without a space, like "Lecture_3" oder "Lecture3"

3. A good adwise at last:

NEVER USE A DROPBOX OR ANY OTHER CLOUD DIRECTORY FOR KNITR OR RMARKDOWN!


Latex don't like it! ;-)

**Comment by NMarkgraf** [comment] 2018-06-13 15:40
Sorry, the 2. suggestioon was renaming Lecture 3 to Lecture3 to get rid of the spaces! Not to add the full path! ;-)

**Comment by ga122493** [comment] 2018-06-13 18:11
Oops, Sorry I did try that too but didn't work

**Comment by ga122493** [comment] 2018-06-13 22:03
Also already tried this and didn't work

```{r}
---
title: "BS854 Bayesian Approach"
author: "Gheorghe Doros"
date: "`r Sys.Date()`"
output:
  beamer_presentation:
    includes:
      after_body: table-of-contents.txt
      in_header: DOROS-beamer-header-simple.txt
    slide_level: 3
  ioslides_presentation: default
  slidy_presentation: default
fontsize: 9pt
---
```

**Comment by yihui** [comment] 2018-06-13 22:17
@ga122493 Could you provide [a minimal, self-contained, and reproducible example](https://yihui.name/en/2017/09/the-minimal-reprex-paradox/)? Please also include your session info:

```r
devtools::session_info('rmarkdown')
```

Your example was not self-contained (I don't have access to your Dropbox folder so I have no idea what those files are).

I suggest that you [upgrade packages](https://yihui.name/en/2017/05/when-in-doubt-upgrade/) instead of downgrading packages when running into problems, e.g. try `update.packages(ask = FALSE, checkBuilt = TRUE)`.

Anyway, without a reproducible example, it is hard to tell what went wrong.

@NMarkgraf I don't think the double quotes or spaces in the file paths really matter in this case, because 1) YAML does not require quotes unless there are special characters in the values; 2) the file paths will not be passed to LaTeX (typically spaces only cause problems in LaTeX).

**Comment by ga122493** [comment] 2018-06-13 22:53
@yihui Thank you for your time and suggestions! An example is attached here with all of the necessary files :). Hopefully you will be able to reproduce the issue.

The session info:
```{r}
Session info ------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.1 (2015-06-18)
 system   x86_64, darwin13.4.0        
 ui       RStudio (1.1.383)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2018-06-13   
Packages ----------------------------------------------------------------------------------------------
 package   * version date       source                        
 backports   1.1.2   2017-12-13 CRAN (R 3.2.5)                
 base64enc   0.1-3   2015-07-28 CRAN (R 3.2.0)                
 digest      0.6.15  2018-01-28 CRAN (R 3.2.1)                
 evaluate    0.10.1  2017-06-24 CRAN (R 3.2.5)                
 glue        1.2.0   2017-10-29 CRAN (R 3.2.5)                
 highr       0.7     2018-06-09 CRAN (R 3.2.1)                
 htmltools   0.3.6   2017-04-28 CRAN (R 3.2.5)                
 jsonlite    1.5     2017-06-01 CRAN (R 3.2.5)                
 knitr       1.20    2018-02-20 CRAN (R 3.2.1)                
 magrittr    1.5     2014-11-22 CRAN (R 3.2.0)                
 markdown    0.8     2017-04-20 CRAN (R 3.2.5)                
 methods   * 3.2.1   2015-06-18 local                         
 mime        0.5     2016-07-07 CRAN (R 3.2.5)                
 Rcpp        0.12.17 2018-05-18 CRAN (R 3.2.1)                
 rmarkdown   1.10    2018-06-11 CRAN (R 3.2.1)                
 rprojroot   1.3-2   2018-01-03 CRAN (R 3.2.1)                
 stats     * 3.2.1   2015-06-18 local                         
 stringi     1.2.3   2018-06-12 CRAN (R 3.2.1)                
 stringr     1.3.1   2018-05-10 CRAN (R 3.2.1)                
 tinytex     0.5.6   2018-06-13 Github (yihui/tinytex@16cc9fa)
 tools       3.2.1   2015-06-18 local                         
 utils     * 3.2.1   2015-06-18 local                         
 yaml        2.1.19  2018-05-01 CRAN (R 3.2.1)   
```

I also upgraded packages, but the issue persists. Just realize that tinytex probably would not help for my Mac, but even in Window it does not work, not sure why. 

On a different note, I really enjoy your blog. Been thinking a lot about phd in stat and reading about some of your experience

**Comment by ga122493** [comment] 2018-06-13 22:55
@yihui Thank you for your time and suggestions! An example is attached here with all of the necessary files :). Hopefully you will be able to reproduce the issue.
Test PDF Beamer.zip
/Users/TuyenTran/Desktop/Test/Test PDF Beamer.zip

The session info:

Session info ------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.1 (2015-06-18)
 system   x86_64, darwin13.4.0        
 ui       RStudio (1.1.383)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2018-06-13   
Packages ----------------------------------------------------------------------------------------------
 package   * version date       source                        
 backports   1.1.2   2017-12-13 CRAN (R 3.2.5)                
 base64enc   0.1-3   2015-07-28 CRAN (R 3.2.0)                
 digest      0.6.15  2018-01-28 CRAN (R 3.2.1)                
 evaluate    0.10.1  2017-06-24 CRAN (R 3.2.5)                
 glue        1.2.0   2017-10-29 CRAN (R 3.2.5)                
 highr       0.7     2018-06-09 CRAN (R 3.2.1)                
 htmltools   0.3.6   2017-04-28 CRAN (R 3.2.5)                
 jsonlite    1.5     2017-06-01 CRAN (R 3.2.5)                
 knitr       1.20    2018-02-20 CRAN (R 3.2.1)                
 magrittr    1.5     2014-11-22 CRAN (R 3.2.0)                
 markdown    0.8     2017-04-20 CRAN (R 3.2.5)                
 methods   * 3.2.1   2015-06-18 local                         
 mime        0.5     2016-07-07 CRAN (R 3.2.5)                
 Rcpp        0.12.17 2018-05-18 CRAN (R 3.2.1)                
 rmarkdown   1.10    2018-06-11 CRAN (R 3.2.1)                
 rprojroot   1.3-2   2018-01-03 CRAN (R 3.2.1)                
 stats     * 3.2.1   2015-06-18 local                         
 stringi     1.2.3   2018-06-12 CRAN (R 3.2.1)                
 stringr     1.3.1   2018-05-10 CRAN (R 3.2.1)                
 tinytex     0.5.6   2018-06-13 Github (yihui/tinytex@16cc9fa)
 tools       3.2.1   2015-06-18 local                         
 utils     * 3.2.1   2015-06-18 local                         
 yaml        2.1.19  2018-05-01 CRAN (R 3.2.1)   
I also upgraded packages, but the issue persists. Just realize that tinytex probably would not help for my Mac, but even in Window it does not work, not sure why.

On a different note, I really enjoy your blog. Been thinking a lot about phd in stat and reading about some of your experience

**Comment by ga122493** [comment] 2018-06-13 22:57
@yihui Thank you for your time and suggestions! An example is attached here with all of the necessary files :). Hopefully you will be able to reproduce the issue.


The session info:

Session info ------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.1 (2015-06-18)
 system   x86_64, darwin13.4.0        
 ui       RStudio (1.1.383)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2018-06-13   
Packages ----------------------------------------------------------------------------------------------
 package   * version date       source                        
 backports   1.1.2   2017-12-13 CRAN (R 3.2.5)                
 base64enc   0.1-3   2015-07-28 CRAN (R 3.2.0)                
 digest      0.6.15  2018-01-28 CRAN (R 3.2.1)                
 evaluate    0.10.1  2017-06-24 CRAN (R 3.2.5)                
 glue        1.2.0   2017-10-29 CRAN (R 3.2.5)                
 highr       0.7     2018-06-09 CRAN (R 3.2.1)                
 htmltools   0.3.6   2017-04-28 CRAN (R 3.2.5)                
 jsonlite    1.5     2017-06-01 CRAN (R 3.2.5)                
 knitr       1.20    2018-02-20 CRAN (R 3.2.1)                
 magrittr    1.5     2014-11-22 CRAN (R 3.2.0)                
 markdown    0.8     2017-04-20 CRAN (R 3.2.5)                
 methods   * 3.2.1   2015-06-18 local                         
 mime        0.5     2016-07-07 CRAN (R 3.2.5)                
 Rcpp        0.12.17 2018-05-18 CRAN (R 3.2.1)                
 rmarkdown   1.10    2018-06-11 CRAN (R 3.2.1)                
 rprojroot   1.3-2   2018-01-03 CRAN (R 3.2.1)                
 stats     * 3.2.1   2015-06-18 local                         
 stringi     1.2.3   2018-06-12 CRAN (R 3.2.1)                
 stringr     1.3.1   2018-05-10 CRAN (R 3.2.1)                
 tinytex     0.5.6   2018-06-13 Github (yihui/tinytex@16cc9fa)
 tools       3.2.1   2015-06-18 local                         
 utils     * 3.2.1   2015-06-18 local                         
 yaml        2.1.19  2018-05-01 CRAN (R 3.2.1)   
I also upgraded packages, but the issue persists. Just realize that tinytex probably would not help for my Mac, but even in Window it does not work, not sure why.

On a different note, I really enjoy your blog. Been thinking a lot about phd in stat and reading about some of your experience

**Comment by ga122493** [comment] 2018-06-13 23:03
@yihui Thank you for your time and suggestions! An example is attached here with all of the necessary files :). Hopefully you will be able to reproduce the issue.




The session info:

Session info ------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.1 (2015-06-18)
 system   x86_64, darwin13.4.0        
 ui       RStudio (1.1.383)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2018-06-13   
Packages ----------------------------------------------------------------------------------------------
 package   * version date       source                        
 backports   1.1.2   2017-12-13 CRAN (R 3.2.5)                
 base64enc   0.1-3   2015-07-28 CRAN (R 3.2.0)                
 digest      0.6.15  2018-01-28 CRAN (R 3.2.1)                
 evaluate    0.10.1  2017-06-24 CRAN (R 3.2.5)                
 glue        1.2.0   2017-10-29 CRAN (R 3.2.5)                
 highr       0.7     2018-06-09 CRAN (R 3.2.1)                
 htmltools   0.3.6   2017-04-28 CRAN (R 3.2.5)                
 jsonlite    1.5     2017-06-01 CRAN (R 3.2.5)                
 knitr       1.20    2018-02-20 CRAN (R 3.2.1)                
 magrittr    1.5     2014-11-22 CRAN (R 3.2.0)                
 markdown    0.8     2017-04-20 CRAN (R 3.2.5)                
 methods   * 3.2.1   2015-06-18 local                         
 mime        0.5     2016-07-07 CRAN (R 3.2.5)                
 Rcpp        0.12.17 2018-05-18 CRAN (R 3.2.1)                
 rmarkdown   1.10    2018-06-11 CRAN (R 3.2.1)                
 rprojroot   1.3-2   2018-01-03 CRAN (R 3.2.1)                
 stats     * 3.2.1   2015-06-18 local                         
 stringi     1.2.3   2018-06-12 CRAN (R 3.2.1)                
 stringr     1.3.1   2018-05-10 CRAN (R 3.2.1)                
 tinytex     0.5.6   2018-06-13 Github (yihui/tinytex@16cc9fa)
 tools       3.2.1   2015-06-18 local                         
 utils     * 3.2.1   2015-06-18 local                         
 yaml        2.1.19  2018-05-01 CRAN (R 3.2.1)   
I also upgraded packages, but the issue persists. Just realize that tinytex probably would not help for my Mac, but even in Window it does not work, not sure why.

On a different note, I really enjoy your blog. Been thinking a lot about phd in stat and reading about some of your experience

[Test PDF Beamer.zip](https://github.com/rstudio/rmarkdown/files/2100247/Test.PDF.Beamer.zip)

**Comment by NMarkgraf** [comment] 2018-06-14 06:48
@yihui you are right, that wasn't the problem. - But rmarkdown isn't it too. -

@ga122493 and @yihui:

 If you take a look at the produced tex file you will notice, that that does not produce a pdf document, there is no pdf to move. so the error message is not a bug, but correct!

@ga122493: Please try to fix the LaTeX Errors first. - Thank you.

**Comment by ga122493** [comment] 2018-06-14 13:58
@NMarkgraf Thank you for following up on this! I am (very) oblivious to the LaTeX error you mentioned, would you mind clarifying?

**Comment by NMarkgraf** [comment] 2018-06-20 16:27
Sorry, currently no time for that … :-(

**Comment by ga122493** [comment] 2018-06-23 02:36
@yihui @Nmarkgraf Thank you both for offering such generous help. I will take these .txt files back to their creator and hopefully figure something out. Will comment back once I have any news.

**Comment by mlatif71** [comment] 2018-08-13 01:48
I found adding [format = "latex", booktabs = T,   escape = F] in kable() work fine and does not show the error

! Undefined control sequence.
<argument> \@@magyar@captionfix

**Closed** 2018-12-04 23:19 UTC
Labels: Question
