### ISSUE TITLE
create a widget without an R package

### ISSUE THREAD

**Issue by Liripo** [rstudio/rmarkdown#2147] opened 2021-05-25 05:16 UTC
Follow [https://bookdown.org/yihui/rmarkdown/htmlwidgets-advanced.html#create-a-widget-without-an-r-package](https://bookdown.org/yihui/rmarkdown/htmlwidgets-advanced.html#create-a-widget-without-an-r-package)

the test.Rmd as follows：
````R
---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,error = T)
```

## R Markdown

```{r}
library(htmlwidgets)
blink = function(text, interval = 1) {
  htmlwidgets::createWidget(
    'blink', 
    list(text = text, interval = interval),
    dependencies = htmltools::htmlDependency(
      'blink', '0.1', src = c(href = ''), head = '
<script>
HTMLWidgets.widget({
  name: "blink",
  type: "output",
  factory: function(el, width, height) {
    return {
      renderValue: function(x) {
        setInterval(function() {
          el.innerText = el.innerText == "" ? x.text : "";
        }, x.interval * 1000);
      },
      resize: function(width, height) {}
    };
  }
});
</script>'
    ),
  )
}

blink('Hello htmlwidgets!', .5)
````
when I use `render("test.Rmd")`,An error occurred：`Error: path for html_dependency not provided`
<details>
  <summary>xfun::session_info()</summary>
  
```R
R version 4.1.0 (2021-05-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS, RStudio 1.4.1106

Locale:
  LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
  LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
  LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
  LC_PAPER=en_US.UTF-8       LC_NAME=C                 
  LC_ADDRESS=C               LC_TELEPHONE=C            
  LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

Package version:
  base64enc_0.1.3   bslib_0.2.5.1     compiler_4.1.0   
  digest_0.6.27     evaluate_0.14     fs_1.5.0         
  glue_1.4.2        graphics_4.1.0    grDevices_4.1.0  
  highr_0.9         htmltools_0.5.1.1 htmlwidgets_1.5.3
  jquerylib_0.1.4   jsonlite_1.7.2    knitr_1.33       
  magrittr_2.0.1    markdown_1.1      methods_4.1.0    
  mime_0.10         R6_2.5.0          rappdirs_0.3.3   
  rlang_0.4.11      rmarkdown_2.8     sass_0.4.0       
  stats_4.1.0       stringi_1.6.2     stringr_1.4.0    
  tinytex_0.31      tools_4.1.0       utils_4.1.0      
  xfun_0.23         yaml_2.2.1 
```
</details>

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

- [x] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [ ] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")`?

**Comment by yihui** [comment] 2021-05-25 14:02
I'm able to reproduce the problem. It sounds like our validation of HTML dependencies is too strict in this case, or at least has become stricter after the book was published, since it has definitely worked in 2018 when I wrote this section. Thanks for the report!

**Comment by cderv** [comment] 2021-05-27 16:40
This is related to other issue on HTML dependency validation: https://github.com/rstudio/rmarkdown/issues/2021 and https://github.com/rstudio/rmarkdown/issues/1842 

Hopefully #1948 will fix this 

Thanks for the report.

**Comment by cderv** [comment] 2021-06-01 10:11
Hopefully this should be fixed in **rmarkdown** dev version 

```r
remotes::install_github("rstudio/rmarkdown")
```

Thanks for the report

**Closed** 2021-06-01 10:10 UTC
Labels: bug
