### ISSUE TITLE
v1.7 breaks input/output in runtime:shiny

### ISSUE THREAD

**Issue by titaniumtroop** [rstudio/rmarkdown#1194] opened 2017-11-10 21:40 UTC
v1.7 appears to break the use of input and output variables in shiny runtime. I've been using these variables to update input values and to output tables in tabsets. This functionality is now broken. Toy code below works as expected with v1.6, not with v1.7.

---
title: "Toy Example"
author: "Toy Soldier"
date: "11/10/2017"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
libraries <- c("plotly")
lapply(libraries, require, character.only = TRUE)
```

```{r output, echo=F}
fluidPage(
  sidebarLayout(
    sidebarPanel(
      width = 3,
      fluidRow(selectInput(
        "type",
        "Type",
        choices = seq(1:10),
        selected = seq(1:10),
        multiple = TRUE,
        selectize = TRUE)
      ),
      fluidRow(selectInput(
        "subtype",
        "Sub-Type",
        choices = seq(1:10),
        selected = seq(1:10),
        multiple = TRUE,
        selectize = TRUE
      ))
    ), 
    mainPanel(
      width = 9,
      tabsetPanel(
        tabPanel("Summary Table", DT::dataTableOutput("DT.example"))
      )
    )
  )  
)

```

```{r reactive filters}
DT.example <- reactive({
  data.frame(input$type, input$subtype)
})
output$DT.example <- DT::renderDataTable({
  DT.example()
})
```

v1.7 yields the following error:
```
processing file: toyExample.Rmd
  |...........                                                      |  17%
  ordinary text without R code

  |......................                                           |  33%
label: setup (with options) 
List of 1
 $ include: logi FALSE

  |................................                                 |  50%
  ordinary text without R code

  |...........................................                      |  67%
label: output (with options) 
List of 1
 $ echo: symbol F

  |......................................................           |  83%
  ordinary text without R code

  |.................................................................| 100%
label: reactive filters

Quitting from lines 53-64 (toyExample.Rmd) 
Warning: Error in <-: object 'output' not found
Stack trace (innermost first):
    115: eval
    114: eval
    113: withVisible
    112: withCallingHandlers
    111: handle
    110: timing_fn
    109: evaluate_call
    108: evaluate::evaluate
    107: evaluate
    106: in_dir
    105: block_exec
    104: call_block
    103: process_group.block
    102: process_group
    101: withCallingHandlers
    100: process_file
     99: knitr::knit
     98: <Anonymous>
     97: do.call
     96: contextFunc
     95: .getReactiveEnvironment()$runWith
     94: shiny::maskReactiveContext
     93: <reactive>
     82: doc
     81: shiny::renderUI
     80: func
     79: origRenderFunc
     78: output$__reactivedoc__
      3: <Anonymous>
      2: do.call
      1: rmarkdown::run 
```

**Comment by yihui** [comment] 2017-11-10 22:43
Duplicate of #1193

**Closed** 2017-11-10 22:50 UTC
Labels: bug
