### ISSUE TITLE
Error in specifying bibliography path in Windows

### ISSUE THREAD

**Issue by sammo3182** [rstudio/rmarkdown#875] opened 2016-11-17 15:00 UTC
I'm using Win10 and Rstudio 1.0.44. Here's an issue I encountered when using .bib file with rmarkdown: every time I tried to specify the path of the bib file, such as `bibliography: E:/MEGAsync/Dropbox/Jabref.bib`, I got an error message like this:
> ! Undefined control sequence.
><write> \string \bibdata {E:\MEGAsync 
>                                      \Dropbox \Jabref }
>l.677 \bibliography{E:\MEGAsync\Dropbox\Jabref}

I've tried various ways to specify the path, e.g., 
`bibliography: E:/MEGAsync/Dropbox/Jabref.bib`;
`bibliography: "E:/MEGAsync/Dropbox/Jabref.bib"`;
`bibliography: E:\MEGAsync\Dropbox\Jabref.bib` with or without quotations;
and `bibliography: E:\\MEGAsync\\Dropbox\\Jabref.bib` with or without quotations.
None of them work. So, I have to leave a copy of my bib file in the working directory of every project to let rmarkdown read the bibs correctly.  

How can I solved the problem? 

Thank you,

**Comment by yihui** [comment] 2016-11-17 18:27
Does the `../` notation work? The number of `../` depends on the relative positions of your Rmd and bib files (e.g. `../../../MEGAsync/Dropbox/Jabref.bib` if you need to go up three levels from the Rmd directory). See the first two answers at http://tex.stackexchange.com/q/38287/9128 The second answer is helpful if you only need LaTeX/PDF output.

**Comment by sammo3182** [comment] 2016-11-17 19:20
No, I tried that, too, and it doesn't work. My rmd is in the following path:
`"E:\MEGAsync\Dropbox\01_Instruction\Research\MyProject\paper\draft.Rmd"`and the .bib file is in 
`E:\MEGAsync\Dropbox\Jabref.bib`. 
So I did 
`bibliography: ../../../../Dropbox/Jabref.bib`, 
and I got the same error.

```
! Undefined control sequence.
<write> \string \bibdata {..\..\..\..\Dropbox 
                                             \Jabref }
l.677 \bibliography{..\..\..\..\Dropbox\Jabref}"
```



I did the check with the `file.exists` function, and it shows that's the correct path:
```R
file.exists("../../../../Dropbox/Jabref.bib")
[1] TRUE
```

**Comment by yihui** [comment] 2016-11-17 19:52
I see. I just pushed a fix #876. You can test it by

```r
devtools::install_github('yihui/rmarkdown@bugfix/bib-slashes')
```

**Comment by sammo3182** [comment] 2016-11-17 19:59
The file compiled, but all the citations are shown as question marks, `(????)`

**Comment by yihui** [comment] 2016-11-17 20:21
I cannot reproduce it on Windows. Could you provide a minimal, self-contained, and reproducible example? Please also tell me the output of `shell('latexmk -v')`.

**Closed** 2016-11-17 21:49 UTC
Labels: bug

**Comment by sammo3182** [comment] 2016-11-18 02:37
Sorry, but how could I create such an example? The problem is about the bib path. `shell('latexmk -v')` returns the following output:
```
latexmk: The script engine could not be found.
latexmk: Data: scriptEngine="perl.exe"
Warning messages:
1: running command 'C:\Windows\system32\cmd.exe /c latexmk -v' had status 1 
2: In shell("latexmk -v") :
  'latexmk -v' execution failed with error code 1
```
But the script does produce a decent pdf when the .bib is located in the file with the Rmd file.

**Comment by yihui** [comment] 2016-11-18 03:13
@sammo3182 Create such an example by deleting everything in your Rmd that is irrelevant to the issue, e.g. delete title, author, date, fontfamily, biblio-style, and so on; delete the document body (perhaps only leave the citation there `@something`); replace `bookdown::pdf_document2` with the standard `pdf_document` output format; delete all unused bib entries in the .bib file. Then paste the absolutely minimal reproducible example here.

**Comment by sammo3182** [comment] 2016-11-18 14:20
Here's the example.
The path of neither the bib and rmd files includes space. In my laptop, they are:
"E:\MEGAsync\Dropbox\01_Instruction\Research\PoliDe\paper\minimalSample.bib" and 
"E:\MEGAsync\Dropbox\MinimalBib.bib"
```R
> file.exists("../../../../Dropbox/MinimalBib.bib")
[1] TRUE
```

In the Rmd file:
```
---
output:
  pdf_document: # using bookdown version to refer tables and figures
    citation_package: natbib
bibliography: ../../../../Dropbox/MinimalBib.bib
---

[@Berinsky1999].
```

The bibliography:

```
@Article{Berinsky1999,
  author    = {Berinsky, Adam J},
  title     = {The Two Faces of Public Opinion},
  year      = {1999},
  pages     = {1209--1230},
  groups    = {Sensitive question skills},
  journal   = {American Journal of Political Science},
  publisher = {JSTOR},
}
```

The output in PDF is:

>[?].
>**Reference**


The problem disappeared as long as I used a .bib at the folder where the .rmd locates.
Here's the output of `system('pdflatex --version')`


```R
MiKTeX-pdfTeX 2.9.6050 (1.40.17) (MiKTeX 2.9 64-bit)
Copyright (C) 1982 D. E. Knuth, (C) 1996-2016 Han The Thanh
TeX is a trademark of the American Mathematical Society.
compiled with zlib version 1.2.8; using 1.2.8
compiled with libpng version 1.6.24; using 1.6.24
compiled with poppler version 0.46.0
compiled with jpeg version 8.4
```

**Comment by yihui** [comment] 2016-11-18 20:50
I still cannot reproduce your issue. I get the PDF as expected: [test.pdf](https://github.com/rstudio/rmarkdown/files/600913/test.pdf)

**Comment by sammo3182** [comment] 2016-11-18 21:50
Ok, I will keep the copy in the working folder for now. May it relate to the output of `shell('latexmk -v')`, though? I got this:
```
latexmk: The script engine could not be found.
latexmk: Data: scriptEngine="perl.exe"
Warning messages:
1: running command 'C:\Windows\system32\cmd.exe /c latexmk -v' had status 1 
2: In shell("latexmk -v") :
  'latexmk -v' execution failed with error code 1
```

**Comment by yihui** [comment] 2016-11-18 22:02
That is fine. It only tells you that your `latexmk` does not really work (you need to install a version of Perl), so `pdflatex` will be called directly.
