### ISSUE TITLE
&emsp is printed as is instead of producing a tab when knitting to PDF even with pdf_document2

### ISSUE THREAD

**Issue by avi-kluger** [rstudio/rmarkdown#2529] opened 2023-11-14 17:15 UTC
Hi,

I successfully use  &emsp in kable to produce tabs when creating either HTML or Word document. When creating a PDF with pdf_document2 it prints &emsp, with pdf_document it fails with 

```
! LaTeX Error: Unicode character   (U+2003)
               not set up for use with LaTeX.
```

Here is a minimal YAML and code to reproduce the problem

````
---
output:
  bookdown::pdf_document2:
    latex_engine: lualatex
---

# Text with a tab

```{r}
library("knitr")
x <-  cars
row.names(x)[2:4] <- paste0("&emsp;", row.names(x)[2:4])
kable(head(x))
```
````

````
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22621), RStudio 2023.6.1.524

Locale:
  LC_COLLATE=English_Israel.utf8  LC_CTYPE=English_Israel.utf8    LC_MONETARY=English_Israel.utf8
  LC_NUMERIC=C                    LC_TIME=English_Israel.utf8    

Package version:
  base64enc_0.1.3   bslib_0.5.1       cachem_1.0.8      cli_3.6.1         digest_0.6.33     ellipsis_0.3.2   
  evaluate_0.23     fastmap_1.1.1     fontawesome_0.5.2 fs_1.6.3          glue_1.6.2        graphics_4.3.1   
  grDevices_4.3.1   highr_0.10        htmltools_0.5.7   jquerylib_0.1.4   jsonlite_1.8.7    knitr_1.45       
  lifecycle_1.0.4   magrittr_2.0.3    memoise_2.0.1     methods_4.3.1     mime_0.12         R6_2.5.1         
  rappdirs_0.3.3    rlang_1.1.2       rmarkdown_2.25.2  sass_0.4.7        stats_4.3.1       stringi_1.8.1    
  stringr_1.5.0     tinytex_0.48      tools_4.3.1       utils_4.3.1       vctrs_0.6.4       xfun_0.41        
  yaml_2.3.7       

Pandoc version: 3.1.1
````

Thanks  for  your consideration.

**Comment by cderv** [comment] 2023-11-15 14:45
I can't reproduce with your example - the document renders to PDF for me. 

I am using this LaTeX version if that matters
````
> tinytex::tlmgr_version()
tlmgr revision 66798 (2023-04-08 02:15:21 +0200)
tlmgr using installation: C:/Users/chris/AppData/Roaming/TinyTeX
TeX Live (https://tug.org/texlive) version 2023
````

**Comment by yihui** [comment] 2023-11-15 14:49
I can't reproduce on macOS, either.

**Comment by avi-kluger** [comment] 2023-11-16 05:29
````
I reproduced the problem on a different machine, this time with Windows 10. It creates a PDF, but the content of the table needs to be corrected (see the attachment with the example).
[TEST.pdf](https://github.com/rstudio/rmarkdown/files/13372646/TEST.pdf)
For verification, below is the version info on my machine.
```r
tinytex::tlmgr_version()
```
tlmgr revision 66798 (2023-04-08 02:15:21 +0200)
tlmgr using installation: C:/Users/owner/AppData/Roaming/TinyTeX
TeX Live (https://tug.org/texlive) version 2023
````

**Comment by cderv** [comment] 2023-11-16 10:22
> When creating a PDF with pdf_document2 it prints &emsp, with pdf_document it fails with

This was the original problem you shared. Here you know share 
> It creates a PDF, but the content of the table needs to be corrected

This is different. You are using a HTML entity character which is `&emsp` - this has no meaning in LaTeX. And here you are producing a LaTeX table using `kable()`.  I believe you need to use [`\quad` command](https://latexref.xyz/_005censpace-_0026-_005cquad-_0026-_005cqquad.html) to get equivalent spacing. 

````r
```{r}
library("knitr")
x <-  cars
row.names(x)[2:4] <- paste0("\\quad", row.names(x)[2:4])
kable(head(x), escape = FALSE)
```
````

![image](https://github.com/rstudio/rmarkdown/assets/6791940/7a16ba4d-b9bd-46cc-bca1-f9f9e7c95c38)


Or you need to output a Markdown table with HTML in it, as Pandoc should be able to convert. 

````markdown
```{r}
library("knitr")
x <-  cars
row.names(x)[2:4] <- paste0("&emsp;", row.names(x)[2:4])
kable(head(x), format = "pipe")
```
````

but it seems the spacing won't be exactly the same as Pandoc convert to non breaking space which is `&nbsp;` in HTML entity. 

So probably the first solution is the right one. 

Hope it helps understand

**Comment by avi-kluger** [comment] 2023-11-16 13:42
Thank you Christophe @cderv , 
The solution with "\\quad" worked only with the simple example, but produced an error in a more complex table. Specifically, with the following kable call
```r
kable(newRes, row.names = FALSE, digits = 2, booktabs = TRUE, caption = caption,
      align = "lrrrr", escape = FALSE)
```
I got
! Extra alignment tab has been changed to \cr.
<recently read> \endtemplate 

But with the second solution, keeping `&emsp;` it worked perfectly:

```r
kable(newRes, row.names = FALSE, digits = 2, booktabs = TRUE, caption = caption,
      align = "lrrrr", format = "pipe")
```

Thanks again for the prompt attention

Avi

**Comment by cderv** [comment] 2023-11-16 14:41
> The solution with "\quad" worked only with the simple example, but produced an error in a more complex table. Specifically, with the following kable call

I don't think that the problem is with `\quad` but probably with `escape = FALSE`. If you table contains some content that should have been escaped, then `escape = FALSE` will not it for you, and you would need to pre process `newRes` for such content. 

Try with using `&emsp;` in the table and running with `escape = FALSE`
````
kable(newRes, row.names = FALSE, digits = 2, booktabs = TRUE, caption = caption,
      align = "lrrrr", escape = FALSE)
````

The simple example we discuseed here works even with this more complex call 

````markdown
---
output:
  bookdown::pdf_document2:
    latex_engine: lualatex
    keep_md: true
---

# Text with a tab

```{r}
library("knitr")
x <-  cars
row.names(x)[2:4] <- paste0("\\quad", row.names(x)[2:4])
kable(x, row.names = FALSE, digits = 2, booktabs = TRUE, caption = "test",
      align = "lrrrr", escape = FALSE)
```

````

That is why I think this is your table data that could impact. 

Anyhow, I'll close this now. Thanks for reaching out!

**Closed by cderv** 2023-11-16 14:41 UTC
Labels: question
