### ISSUE TITLE
rmarkdown produces bad latex: escaped \times for scientific notation

### ISSUE THREAD

**Issue by maxheld83** [rstudio/rmarkdown#406] opened 2015-03-23 21:13 UTC
This seems to be an odd bug (?) and I am unfortunately not sure where along the rmarkdown - knitr - pandoc toolchain this goes wrong, so I'm just posting it here.

```
factorial(77) / factorial(2) * factorial(77-2)
````

evaluates just fine in R (it's a lot).

Inside an RMarkdown file, however, 

```
---
title: "test"
author: "Maximilian Held"
date: "23 Mar 2015"
output: pdf_document
---

This is an R Markdown document. 
`r factorial(77) / factorial(2) * factorial(77-2)`
```

It fails with: 

```

! Missing $ inserted.
<inserted text> 
                $
l.74 ...is an R Markdown document. 1.8009339\times

pandoc: Error producing PDF from TeX source
Error: pandoc document conversion failed with error 43
Execution halted
```

On closer inspection, the `.tex` source reveals that the above R code is knit into:

```
1.8\times 10\^{}\{222\}
```
Which fails with (different filenames, same errors):

```
E: /Users/Max/Github/tax-democracy.tex:1064 Missing $ inserted ...vely high number for 77 items (1.8\times
E: /Users/Max/Github/tax-democracy.tex:1064 Please use \mathaccent for accents in math mode ...gh number for 77 items (1.8\times 10\^{}
E: /Users/Max/Github/tax-democracy.tex:1064 Missing { inserted ...gh number for 77 items (1.8\times 10\^{}
E: /Users/Max/Github/tax-democracy.tex:1064 You can't use `\spacefactor' in math mode ...gh number for 77 items (1.8\times 10\^{}
E: /Users/Max/Github/tax-democracy.tex:1065 Missing $ inserted
E: /Users/Max/Github/tax-democracy.tex:1065 Missing } inserted
```

**The problem seems to be the escaped `\times`.**

**Comment by yihui** [comment] 2015-03-26 20:55
Duplicate of #385. Sorry.

**Closed by yihui** 2015-03-26 20:55 UTC
