### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by jzen188** [rstudio/rmarkdown#195] opened 2014-07-29 03:03 UTC
Hi Rstudio team, 
I have a question about background image.

I have included this in my 7th slides when I am trying to use ioslide.presentation option.
slide > slide [data-slide-num="7"]
{
background-color: "black";
background-image: url("figures/xx.jpg");
}

The document I build would be black color but CANT FIND THE PATH of the xx.jpg...
Unlike shiny, we can set a www/ directory and put the things inside.
What can I do to find the figure/xx.jpg like calling it in the document itself?
Thank you.

**Comment by daftmath** [comment] 2016-10-03 15:34
Since this issue has been open for 2 years and doesn't have any easy fix...here is a **reckless and irresponsible**, but working solution for anyone trying to use a background img but rmarkdown can't find the path.

1) Create a dummy image in your rmarkdown file using regular <img> but set width and height to 0 px like so:
`<img src='bg.jpg' style='width:0px;height:0px;'>`

2) Run app and open in chrome. Right click webpage. Select "Inspect". Hit the "Sources tab.

3) Locate the temporary folder with a weird name. Your dummy image will be inside this folder.

![image](https://cloud.githubusercontent.com/assets/12780936/19042831/40b45e2e-8953-11e6-9b54-0b3d41915315.png)

4) Right click your dummy image and select "Copy Link Address"

5) Use the dummy image's address as your css url background image link. Example below, but your file address and name might be different than mine so follow the steps and don't just copy mine.

```
body {
    background-image: url(file1d1027701f9b_files/bg.jpg);
    background-size: 100% auto;
    background-repeat: no-repeat;
}
```

6. Run the application and rmarkdown will now find your background image. This solution might not be stable or easily reproducible, but it works for me.

**Comment by ShKlinkenberg** [comment] 2017-09-03 15:52
Jared had a solution but... well see for yourself. See [here](https://www.jaredlander.com/2017/07/fullscreen-background-images-in-ioslides-presentations/).

**Comment by yihui** [comment] 2017-09-03 21:14
@ShKlinkenberg Yeah, I have seen @jaredlander's solution before. I think once we merge #687, this will be much more straightforward and you don't have to hack at it by yourself any more.

**Comment by jaredlander** [comment] 2017-09-05 00:24
I look forward to not using my workaround and it looks like #687 even keeps the file self-contained. Plus we won't have to worry about loading in jquery and having it make changes at runtime.

**Closed** 2017-09-06 04:04 UTC
Labels: enhancement

**Comment by yihui** [comment] 2017-09-06 04:27
Just merged #687, and you can add the attribute `{data-background=???}` after a slide title, e.g.

```
## One Slide {data-background=#ffff00}

blah blah

## Another Slide {data-background=foo/bar.png}
```

**Comment by ShKlinkenberg** [comment] 2017-09-06 07:39
Thanks!

_____

Universiteit van Amsterdam

Sharon Klinkenberg

Bezoek | Nieuwe Achtergracht 129B<https://mapkit.io/embed/cq4eoa> | Kamer REC-G -1.12 (Souterrain)
Post | Postbus 15943 | 1001 NK Amsterdam
Pakketpost | Valckenierstraat 59 | 1018 XE Amsterdam
T: +31 (0)20 525 6904 | S.Klinkenberg@uva.nl

**Comment by jaredlander** [comment] 2017-09-06 15:09
Can't wait to try it.

**Comment by ShKlinkenberg** [comment] 2017-09-06 15:36
Tried it and it worked like a charm.

The new release did break some other things though.

@Yihui Xie: Images of child imports did not load anymore.



```{r child = "bla/bla/bla.Rmd"}

```


_____

Universiteit van Amsterdam

Sharon Klinkenberg

Bezoek | Nieuwe Achtergracht 129B<https://mapkit.io/embed/cq4eoa> | Kamer REC-G -1.12 (Souterrain)
Post | Postbus 15943 | 1001 NK Amsterdam
Pakketpost | Valckenierstraat 59 | 1018 XE Amsterdam
T: +31 (0)20 525 6904 | S.Klinkenberg@uva.nl

**Comment by yihui** [comment] 2017-09-06 15:52
@ShKlinkenberg I just tested it, and I could not reproduce it. Could you provide a minimal, self-contained, and reproducible example? You can upload a zip file on Github.

**Comment by jaredlander** [comment] 2017-09-10 02:23
When viewing in the RStudio window my images are not displayed when built as such:

```{r show-image,echo=FALSE,fig.align='center',out.width='95%'}
knitr::include_graphics(file.path(imageDir, "this_image.png"))
```

However, it does display when the presentation is opened in Chrome.

But, it works fine in the rstudio window if the image file is in the same directory as the Rmd file.

```{r show-image-local,echo=FALSE,fig.align='center',out.width='95%'}
knitr::include_graphics(imageDir, "this_image.png")
```

**Comment by lxgould** [comment] 2017-09-11 15:20
Nice!  The data-background attribute works like a charm.  I was ready to try Jared's solution when I found this.  Thanks, @jaredlander and @yihui
