### ISSUE TITLE
Is there any way to automate nested sections in Rmds which include text, maps and tables?

### ISSUE THREAD

**Issue by Christoph999** [rstudio/rmarkdown#1920] opened 2020-10-13 12:50 UTC
I asked this question some time ago on [SO here](https://stackoverflow.com/q/56983105/5784831) but without success.
I also tried [this](https://stackoverflow.com/q/50467457/5784831) and [this](https://stackoverflow.com/q/56986638/5784831) to improve on what I have, but I was again not successful. (Both questions are linked in [SO here](https://stackoverflow.com/q/56983105/5784831).)

It would be great, if you can comment, if this is possible or not.
(rmarkdown version 2.4 and knitr version 1.30 are up to date.)

Thank you very much and let me know if you need further information.

Reproducible examples and a reference can be found in the linked [question on Stackoverflow](https://stackoverflow.com/q/56983105/5784831). The "reference" shows what it should look like, if this is unclear.

**Comment by atusy** [comment] 2020-10-19 12:28
As I answered on SO, I'd recommend take a look at https://stackoverflow.com/questions/63534247/recommended-way-to-initialize-js-renderer-in-asis-markdown-chunck/63557622?noredirect=1#comment112417672_63557622

**Comment by atusy** [comment] 2020-10-19 12:33
I took a lookt at the link again, and I remembered this is a duplicate of https://github.com/rstudio/rmarkdown/issues/1877

**Closed** 2020-10-19 16:12 UTC
