### ISSUE TITLE
Can't knit to Pdf in RStudio Mac version 1.4.1103

### ISSUE THREAD

**Issue by pleasehelpmeeee** [rstudio/rmarkdown#2143] opened 2021-05-20 21:18 UTC
**I'm having troubles with knitting to pdf. i get the following errors:**

This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2021) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
tlmgr search --file --global '/multirow.sty'
Trying to automatically install missing LaTeX packages...
tlmgr install multirow
tlmgr: package repository https://ctan.math.illinois.edu/systems/texlive/tlnet (not verified: gpg unavailable)
[1/1, ??:??/??:??] install: multirow [3k]
TLPDB::_install_data: unsupported container format xz for https://ctan.math.illinois.edu/systems/texlive/tlnet/archive/multirow.tar.xz
tlmgr: package log updated: /Users/name/Library/TinyTeX/texmf-var/web2c/tlmgr.log
tlmgr update --self
tlmgr install multirow
tlmgr: package repository https://ctan.math.illinois.edu/systems/texlive/tlnet (not verified: gpg unavailable)
[1/1, ??:??/??:??] install: multirow [3k]
tlmgr: package log updated: /Users/name/Library/TinyTeX/texmf-var/web2c/tlmgr.log
TLPDB::_install_data: unsupported container format xz for https://ctan.math.illinois.edu/systems/texlive/tlnet/archive/multirow.tar.xz
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2021) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
tlmgr search --file --global '/multirow.sty'
! LaTeX Error: File `multirow.sty' not found.

! Emergency stop.
<read *> 

Error: LaTeX failed to compile vignettes.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See vignettes.log for more info.
Execution halted

**When i check out the vignettes.log file, it says:**

! LaTeX Error: File `multirow.sty' not found.

**I tried installing it by running this code:**
```{r}
install.packages("http://mirrors.ctan.org/macros/latex/contrib/multirow.zip")
```

**But i get the following error:**
Warning in install.packages :
  package ‘http://mirrors.ctan.org/macros/latex/contrib/multirow.zip’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**I also went through the steps outlined in https://yihui.org/tinytex/r/#debugging but it still doesnt work.** 

**I appreciate any help that anyone can offer!**

**Added info:**

```{r}
xfun::session_info('rmarkdown')
```

R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS High Sierra 10.13.6, RStudio 1.4.1103

Locale: en_CA.UTF-8 / en_CA.UTF-8 / en_CA.UTF-8 / C / en_CA.UTF-8 / en_CA.UTF-8

Package version:
  base64enc_0.1.3   digest_0.6.27     evaluate_0.14    
  glue_1.4.2        graphics_4.0.3    grDevices_4.0.3  
  highr_0.9         htmltools_0.5.1.1 jsonlite_1.7.2   
  knitr_1.33        magrittr_2.0.1    markdown_1.1     
  methods_4.0.3     mime_0.10         rlang_0.4.11     
  rmarkdown_2.8     stats_4.0.3       stringi_1.6.2    
  stringr_1.4.0     tinytex_0.31      tools_4.0.3      
  utils_4.0.3       xfun_0.23         yaml_2.2.1       

Pandoc version: 2.11.2

I also tried downloading multirows from this website https://ctan.org/tex-archive/macros/latex/contrib/multirow?lang=en and then moving the folder into the appropriate destination and it didnt work. 

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [ X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [X ] included a minimal, self-contained, and reproducible example?

- [X ] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [X ] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [X ] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")`?

**Comment by yihui** [comment] 2021-05-20 22:25
Please do not omit the checklist in the issue guide when filing issues: https://github.com/rstudio/rmarkdown/issues/new?assignees=&labels=&template=bug-report.md&title= Could you add all the info required by the issue guide? Without the info, it's hard to tell what the problem is.

BTW, `multirows` is a LaTeX package, not an R package. You can't use `install.packages()` to install LaTeX packages. Again, we need a reprex and session info as required by the issue guide so we can investigate.

**Comment by pleasehelpmeeee** [comment] 2021-05-20 22:42
> Please do not omit the checklist in the issue guide when filing issues: https://github.com/rstudio/rmarkdown/issues/new?assignees=&labels=&template=bug-report.md&title= Could you add all the info required by the issue guide? Without the info, it's hard to tell what the problem is.
> 
> BTW, `multirows` is a LaTeX package, not an R package. You can't use `install.packages()` to install LaTeX packages. Again, we need a reprex and session info as required by the issue guide so we can investigate.

Thanks, yihui. I updated my post. this is my first time posting, so thank you for your patience!

**Comment by yihui** [comment] 2021-05-21 01:32
> this is my first time posting

That's okay. If you open the issue guide I mentioned above, you will find the checklist (which requires a minimal reproducible example, which I also asked for above but didn't get):

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [ ] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [ ] included a minimal, self-contained, and reproducible example?

- [ ] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [ ] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [ ] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")` ?

**Comment by pleasehelpmeeee** [comment] 2021-05-21 02:17
> > this is my first time posting
> 
> That's okay. If you open the issue guide I mentioned above, you will find the checklist (which requires a minimal reproducible example, which I also asked for above but didn't get):
> 
> ## Checklist
> When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:
> 
> * [ ]  [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
> * [ ]  included a minimal, self-contained, and reproducible example?
> * [ ]  pasted the output from `xfun::session_info('rmarkdown')` in your issue?
> * [ ]  upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?
> * [ ]  installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")` ?

Is this what you mean??? adding the checklist at the bottom and checking it off?

**Comment by yihui** [comment] 2021-05-21 02:50
Yes, but if you are really busy or don't understand what the checklist means, the most important item is the second one:

> include a minimal, self-contained, and reproducible example

It's often very hard to help users if we are not told how to reproduce the problem.

**Comment by cderv** [comment] 2021-05-21 08:08
Just to give some context regarding your error. 

* Knitting to PDF will knit to `.tex` file then convert to PDF using LaTeX. That is why you need a distribution like TinyTeX
* LaTeX is different from R and works with packages too. They are required based on what is used in the document. TinyTeX distribution helps you with this because it will try to install automatically missing packages
* Here `multirow` is missing, hence the installation try. But you cannot try to install manually using `install.packages()` as you did because this function is for R 📦 only. 

So here it is an issue with installation a package from CTAN to use with LaTeX. Sometimes these error can be related to the mirror used and can be solved by themselves with time. 

To install a package from CTAN manually you can do
````r
tinytex::tlmgr_install("multirow")
````

You may retry in case it was a mirror issue.

**Comment by yihui** [comment] 2021-05-21 13:32
Since this is not the first time I have seen this issue (e.g. https://github.com/yihui/tinytex/issues/81#issuecomment-815013443), I'd really like to figure out why it happens, hence I need to know how to reproduce the problem, but so far no one has provided a reproducible example.

**Comment by cderv** [comment] 2021-05-21 13:49
Yeah I tried to reproduce by changing the CTAN repo but I can't reproduce. If it is related to CTAN mirror and temporary (during sync ?), it will not be easy to reproduce. 

The error message does not get me much luck on the web, except for xz format not being a supported one on Windows for example. But I have no issue downloading the multirow and installing

**Comment by pleasehelpmeeee** [comment] 2021-05-21 18:19
I created a fake dataset and tried running it again and it still doesn't work. This is my code:

date: "21/05/2021"
output:
  pdf_document: default
  html_document: default
---
```{r data set up}

setwd("~/Desktop/School")

data<-read.csv("Testdata.csv")

```

```{r icc}

library(lme4)
model1<-lmer(Estability~ 1+(1|Supervisor_ID), data=data)
library(jtools)
summ(model1)
```

This is what the RMarkdown tab says:
processing file: Untitled.Rmd
  |..............                                                        |  20%
  ordinary text without R code

  |............................                                          |  40%
label: data set up
  |..........................................                            |  60%
  ordinary text without R code

  |........................................................              |  80%
label: icc
  |......................................................................| 100%
  ordinary text without R code

/Applications/RStudio.app/Contents/MacOS/pandoc/pandoc +RTS -K512m -RTS Untitled.knit.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output Untitled.tex --lua-filter /Users/name/Library/R/4.0/library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /Users/name/Library/R/4.0/library/rmarkdown/rmarkdown/lua/latex-div.lua --self-contained --highlight-style tango --pdf-engine pdflatex --variable graphics --variable 'geometry:margin=1in' --include-in-header /var/folders/w1/b523f8l940l7xgngkhzymzgh0000gn/T//Rtmp02YvI0/rmarkdown-str9c007dcd654.html 
output file: Untitled.knit.md

tlmgr: package repository https://ctan.math.illinois.edu/systems/texlive/tlnet (not verified: gpg unavailable)
[1/1, ??:??/??:??] install: multirow [3k]
TLPDB::_install_data: unsupported container format xz for https://ctan.math.illinois.edu/systems/texlive/tlnet/archive/multirow.tar.xz
tlmgr: package log updated: /Users/name/Library/TinyTeX/texmf-var/web2c/tlmgr.log
tlmgr update --self
sh: fmtutil-sys: command not found
tlmgr: package repository https://ctan.math.illinois.edu/systems/texlive/tlnet (not verified: gpg unavailable)
[1/1, ??:??/??:??] install: multirow [3k]
TLPDB::_install_data: unsupported container format xz for https://ctan.math.illinois.edu/systems/texlive/tlnet/archive/multirow.tar.xz
tlmgr: package log updated: /Users/name/Library/TinyTeX/texmf-var/web2c/tlmgr.log
! LaTeX Error: File `multirow.sty' not found.

! Emergency stop.
<read *> 

Error: LaTeX failed to compile Untitled.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See Untitled.log for more info.
In addition: Warning message:
In system2(if (usermode) "fmtutil-user" else "fmtutil-sys", "--all",  :
 ​error in running command
Execution halted


After i have failed knitting, it still gives me 2 files:

![image](https://user-images.githubusercontent.com/84544406/119181439-9b87b400-ba3f-11eb-9fcf-0810cd92f7ac.png)

**Comment by yihui** [comment] 2021-05-25 18:32
We don't have your `~/Desktop/School` folder or `Testdata.csv` (in other words, your example is not self-contained). If the problem occurs for any `lmer()` models, could you use an example dataset in the **lme4** package?

**Comment by pleasehelpmeeee** [comment] 2021-05-26 15:18
Here is an example using the dataset called "cake" in the lme4 package. 

```{r icc}

library(lme4)
model1<-lmer(angle~ recipe + temperature +(1|recipe:replicate),cake)
library(jtools)
summ(model1)
```

This is what the RMarkdown tab says when i try knitting to PDF:
````
 

processing file: Untitled.Rmd
  |.......................                                               |  33%
  ordinary text without R code

  |...............................................                       |  67%
label: icc
  |......................................................................| 100%
  ordinary text without R code


output file: Untitled.knit.md

/Applications/RStudio.app/Contents/MacOS/pandoc/pandoc +RTS -K512m -RTS Untitled.knit.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output Untitled.tex --lua-filter /Users/name/Library/R/4.0/library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /Users/name/Library/R/4.0/library/rmarkdown/rmarkdown/lua/latex-div.lua --self-contained --highlight-style tango --pdf-engine pdflatex --variable graphics --variable 'geometry:margin=1in' --include-in-header /var/folders/w1/b523f8l940l7xgngkhzymzgh0000gn/T//RtmpmHtyAR/rmarkdown-strd23774c26c5.html 
tlmgr: package repository https://ctan.math.illinois.edu/systems/texlive/tlnet (not verified: gpg unavailable)
[1/1, ??:??/??:??] install: multirow [3k]
TLPDB::_install_data: unsupported container format xz for https://ctan.math.illinois.edu/systems/texlive/tlnet/archive/multirow.tar.xz
tlmgr: package log updated: /Users/name/Library/TinyTeX/texmf-var/web2c/tlmgr.log
tlmgr update --self
sh: fmtutil-sys: command not found
tlmgr: package repository https://ctan.math.illinois.edu/systems/texlive/tlnet (not verified: gpg unavailable)
[1/1, ??:??/??:??] install: multirow [3k]
TLPDB::_install_data: unsupported container format xz for https://ctan.math.illinois.edu/systems/texlive/tlnet/archive/multirow.tar.xz
tlmgr: package log updated: /Users/name/Library/TinyTeX/texmf-var/web2c/tlmgr.log
! LaTeX Error: File `multirow.sty' not found.

! Emergency stop.
<read *> 

Error: LaTeX failed to compile Untitled.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See Untitled.log for more info.
In addition: Warning message:
In system2(if (usermode) "fmtutil-user" else "fmtutil-sys", "--all",  :
  error in running command
Execution halted

````

**Comment by pleasehelpmeeee** [comment] 2021-06-12 18:16
Given your non-response, I assume there’s no solution?

**Comment by pleasehelpmeeee** [comment] 2021-06-12 18:17
> We don't have your `~/Desktop/School` folder or `Testdata.csv` (in other words, your example is not self-contained). If the problem occurs for any `lmer()` models, could you use an example dataset in the **lme4** package?

given your non-response, I assume there’s no solution?

**Comment by yihui** [comment] 2021-06-13 02:54
@pleasehelpmeeee I'm still unable to reproduce your problem. Have you tried the debugging steps at https://yihui.org/tinytex/r/#debugging? In particular, did you try to reinstall TinyTeX?

```r
tinytex::reinstall_tinytex()
```

I suspect that this is a temporary issue, but I'm not able to reproduce it, and it's often hard to fix issues that are not reproducible.

**Comment by pleasehelpmeeee** [comment] 2021-06-13 13:51
> @pleasehelpmeeee I'm still unable to reproduce your problem. Have you tried the debugging steps at https://yihui.org/tinytex/r/#debugging? In particular, did you try to reinstall TinyTeX?
> 
> ```r
> tinytex::reinstall_tinytex()
> ```
> 
> I suspect that this is a temporary issue, but I'm not able to reproduce it, and it's often hard to fix issues that are not reproducible.

Yes I’ve already tried that. Have you tried reproducing it on a Mac computer?

**Comment by yihui** [comment] 2021-06-14 15:15
Yes, I'm on a Macbook. Do you have this file?

```sh
ls -lh ~/Library/TinyTeX/tlpkg/installer/xz/

-rwxr-xr-x  1 user  staff   425K Feb 25 12:01 xz.universal-darwin
```

**Comment by pleasehelpmeeee** [comment] 2021-06-14 17:43
> Yes, I'm on a Macbook. Do you have this file?
> 
> ```shell
> ls -lh ~/Library/TinyTeX/tlpkg/installer/xz/
> 
> -rwxr-xr-x  1 user  staff   425K Feb 25 12:01 xz.universal-darwin
> ```

No i do not. This is all that's in that folder:<img width="1211" alt="Screen Shot 2021-06-14 at 1 41 51 PM" src="https://user-images.githubusercontent.com/84544406/121935405-66a50f00-cd16-11eb-83b1-d26b8840cfb8.png">

**Comment by yihui** [comment] 2021-06-14 18:19
You were looking at the R package folder, but I meant the TinyTeX folder, i.e., you run the command in your terminal:

```sh
ls -lh ~/Library/TinyTeX/tlpkg/installer/xz/
```

**Comment by pleasehelpmeeee** [comment] 2021-06-14 18:32
> You were looking at the R package folder, but I meant the TinyTeX folder, i.e., you run the command in your terminal:
> 
> ```shell
> ls -lh ~/Library/TinyTeX/tlpkg/installer/xz/
> ```

When i run that in the terminal app, it says, "total 856".

**Comment by yihui** [comment] 2021-06-14 19:08
Your TinyTeX installation seems to be broken, but I don't know why.

I'm using macOS Big Sur 11.4, but it should not matter which version of macOS you use.

What's your output of `tinytex::reinstall_tinytex()`?

**Comment by pleasehelpmeeee** [comment] 2021-06-14 19:50
> Your TinyTeX installation seems to be broken, but I don't know why.
> 
> I'm using macOS Big Sur 11.4, but it should not matter which version of macOS you use.
> 
> What's your output of `tinytex::reinstall_tinytex()`?

nothing happens when i run that. it just starts a new line and has '>'

**Comment by yihui** [comment] 2021-06-14 21:49
That's really odd. Are you able to run any R code at all in your R console?

**Comment by pleasehelpmeeee** [comment] 2021-06-14 21:57
> That's really odd. Are you able to run any R code at all in your R console?

Yes i'm able to run R code. 

<img width="488" alt="Screen Shot 2021-06-14 at 5 56 33 PM" src="https://user-images.githubusercontent.com/84544406/121964704-f27c6280-cd39-11eb-866e-5fc7e1294728.png">

**Comment by yihui** [comment] 2021-06-15 03:24
Anything happens when you run `tinytex::install_tinytex()`?

**Comment by PythonCoderUnicorn** [comment] 2021-06-26 02:53
## Hello, I have this issue and will try my best to check off each box.

### Device: Mac 10.15.7, running Rstudio

### what I did to make a Rmd file: 
>` file > new markdown > Document > test.Rmd `

### xfun::session_info
> `xfun::session_info('rmarkdown')
  R version 4.0.5 (2021-03-31)
  Platform: x86_64-apple-darwin17.0 (64-bit)
  Running under: macOS Catalina 10.15.7, RStudio 1.4.1106

> Locale: en_CA.UTF-8 / en_CA.UTF-8 / en_CA.UTF-8 / C / en_CA.UTF-8 / en_CA.UTF-8
> Package version:
    base64enc_0.1.3      digest_0.6.27       
    evaluate_0.14        fastmap_1.1.0       
    glue_1.4.2           graphics_4.0.5      
    grDevices_4.0.5      highr_0.8           
    htmltools_0.5.1.9005 jsonlite_1.7.2      
    knitr_1.33           magrittr_2.0.1      
    markdown_1.1         methods_4.0.5       
    mime_0.10            rlang_0.4.11        
    rmarkdown_2.9        stats_4.0.5         
    stringi_1.5.3        stringr_1.4.0       
    tinytex_0.32         tools_4.0.5         
    utils_4.0.5          xfun_0.24           
    yaml_2.2.1          
`

### the constant error message in the terminal
  > `sh: rmarkdown::render: command not found
  Warning message:
  In system(paste0("rmarkdown::render '", input, "'")) :
    error in running command
  `

### tinytex 
  >`tinytex::reinstall_tinytex()
  sh: tlmgr: command not found
  Error in system2("tlmgr", args, ...) : error in running command
  '

### the remotes
 > `remotes::install_github("rstudio/rmarkdown")
    Downloading GitHub repo rstudio/rmarkdown@HEAD
    These packages have more recent versions available.
    It is recommended to update all of them.
    Which would you like to update?
  
   >  1: All                            
    2: CRAN packages only             
    3: None                           
    4: stringi (1.5.3 -> 1.6.2) [CRAN]
    5: mime    (0.10  -> 0.11 ) [CRAN]
    6: highr   (0.8   -> 0.9  ) [CRAN]
    
 >  Enter one or more numbers, or an empty line to skip updates: 1
    stringi (1.5.3 -> 1.6.2) [CRAN]
    mime    (0.10  -> 0.11 ) [CRAN]
    highr   (0.8   -> 0.9  ) [CRAN]
    Installing 3 packages: stringi, mime, highr
    trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/stringi_1.6.2.tgz'
    Content type 'application/x-gzip' length 14597551 bytes (13.9 MB)
    ==================================================
    downloaded 13.9 MB
    
  > trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/mime_0.11.tgz'
    Content type 'application/x-gzip' length 34862 bytes (34 KB)
    ==================================================
    downloaded 34 KB
    
  > trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/highr_0.9.tgz'
    Content type 'application/x-gzip' length 39027 bytes (38 KB)
    ==================================================
    downloaded 38 KB
    
  
 > The downloaded binary packages are in
	  /var/folders/1g/ylfgpc813936cj34f1zs1h1h0000gn/T//RtmpK78Sf1/downloaded_packages
   ✓  checking for file 
>  ‘/private/var/folders/1g/ylfgpc813936cj34f1zs1h1h0000gn/T/RtmpK78Sf1/remotes91d053c406a1/rstudio- rmarkdown-bafed5e/DESCRIPTION’ (436ms)
  ─  preparing ‘rmarkdown’: (671ms)
  ✓  checking DESCRIPTION meta-information ...
  ─  checking for LF line-endings in source and make files and shell scripts (355ms)
  ─  checking for empty or unneeded directories
     Removed empty directory ‘rmarkdown/tools’
  ─  building ‘rmarkdown_2.9.1.tar.gz’
     
  > * installing *source* package ‘rmarkdown’ ...
    ** using staged installation
    ** R
    ** inst
    ** byte-compile and prepare package for lazy loading
    Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
      namespace ‘rlang’ 0.4.11 is being loaded, but >= 0.4.11.9000 is required
    Calls: <Anonymous> ... asNamespace -> loadNamespace -> namespaceImport -> loadNamespace
    Execution halted
  > ERROR: lazy loading failed for package ‘rmarkdown’
  > * removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown’
    * restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown’
    Warning message:
    In i.p(...) :
      installation of package ‘/var/folders/1g/ylfgpc813936cj34f1zs1h1h0000gn/T//RtmpK78Sf1/file91d03eb8f092/rmarkdown_2.9.1.tar.gz’ had non-zero exit status
`
### I have looked on other forums for help, Rstudio closed this issue, I tried to uninstall/reinstall `rlang` and `rmarkdown`. I installed `Shiny, Flexdashboard, Rmarkdown, Pagedown.`

The test.Rmd file runs the code just fine inside the document but fails to knit, that too I did install.packages() for. This issue remains. Hope I checked all the boxes to help.

**Comment by dcaud** [comment] 2021-07-10 04:35
I was getting a similar error and was unable to output to PDF.

`tinytex::install_tinytex()` didn't fix it.

But `tinytex::reinstall_tinytex()` fixed it.

**Comment by cderv** [comment] 2021-12-23 15:23
@pleasehelpmeeee is this still an issue ? Can we close this otherwise ? 

Thanks.

**Closed** 2022-02-09 16:54 UTC
