### ISSUE TITLE
Rmarkdown with Python and plotnine

### ISSUE THREAD

**Issue by Courvoisier13** [rstudio/rmarkdown#2175] opened 2021-06-28 22:45 UTC
I am having the same issue as in https://community.rstudio.com/t/knitting-python-code-in-r-markdown-file-crashes-if-calling-plotnine-or-deploy/87011 (reported a year ago).
The below Rmd gives the following error only with plotnine. matplotlib and seaborn do not give the same error.

```
---
title: "test plotnine"
author: ""
date: "6/28/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{python}
from plotnine import ggplot, geom_point, aes, stat_smooth, facet_wrap, geom_line, theme_light
from plotnine.data import mtcars as mtcars
import matplotlib.pyplot as plt
p = ggplot(data = mtcars, mapping=aes(x='mpg', y='hp')) + geom_point()
print(p)
```

After reaching 100% I get the error:
```
processing file: testplotnine.Rmd
  |.........................................                                                                                                                           |  25%
  ordinary text without R code

  |..................................................................................                                                                                  |  50%
label: setup (with options) 
List of 1
 $ include: logi FALSE

  |...........................................................................................................................                                         |  75%
  ordinary text without R code

  |....................................................................................................................................................................| 100%
label: unnamed-chunk-1 (with options) 
List of 1
 $ engine: chr "python"

Quitting from lines 17-22 (testplotnine.Rmd) 
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  RuntimeError: Evaluation error: TypeError: type object got multiple values for keyword argument 'visible'

Detailed traceback:
  File "C:\ANACON~1\envs\R-RETI~1\lib\site-packages\matplotlib\pyplot.py", line 821, in clf
    gcf().clf()
  File "C:\ANACON~1\envs\R-RETI~1\lib\site-packages\matplotlib\figure.py", line 1795, in clf
    ax.cla()
  File "C:\ANACON~1\envs\R-RETI~1\lib\site-packages\matplotlib\axes\_base.py", line 1056, in cla
    self.xaxis.cla()
  File "C:\ANACON~1\envs\R-RETI~1\lib\site-packages\matplotlib\axis.py", line 788, in cla
    self.reset_ticks()
  File "C:\ANACON~1\envs\R-RETI~1\lib\site-packages\matplotlib\axis.py", line 811, in reset_ticks
    self.set_clip_path(self.axes.patch)
  File "C:\ANACON~1\envs\R-RETI~1\lib\site-packages\matplotlib\axis.py", line 901, in set_clip_path
    for child in self.majorTicks + self.minorTicks:
  File "C:\ANACON~1\envs\R-RETI~1\lib\site-packages\matplotlib\axis.py", line 618, in __get__
    tick = instance._get_tick(majo
```

```
> xfun::session_info('rmarkdown')
R version 4.0.5 (2021-03-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043), RStudio 1.4.1717

Locale:
  LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
  LC_TIME=English_United States.1252    

Package version:
  base64enc_0.1.3   digest_0.6.27     evaluate_0.14     glue_1.4.2        graphics_4.0.5    grDevices_4.0.5   highr_0.9         htmltools_0.5.1.1 jsonlite_1.7.2   
  knitr_1.33        magrittr_2.0.1    markdown_1.1      methods_4.0.5     mime_0.11         rlang_0.4.10      rmarkdown_2.9.1   stats_4.0.5       stringi_1.6.2    
  stringr_1.4.0     tinytex_0.32      tools_4.0.5       utils_4.0.5       xfun_0.24         yaml_2.2.1       

Pandoc version: 2.11.4
```

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [ x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [ x] included a minimal, self-contained, and reproducible example?

- [ x] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [ x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [ x] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")`?

**Comment by cderv** [comment] 2021-06-29 08:24
Can you try with last dev version of **reticulate** ? 

I can't reproduce: the above Rmd file in working well for me with dev version of reticulate and using python 3.9.5.

**Comment by Courvoisier13** [comment] 2021-06-29 09:15
I updated reticulate using `remotes::install_github('rstudio/reticulate')` -> that did not help. So I moved on to the python version.

I was using an `r-reticulate` conda environment . `reticulate` recommends creating a miniconda environment and adding packages as needed, and I stuck with it for `reticulate`. Also, to my knowledge, conda only goes to python 3.8 at the moment, so I can't upgrade it to 3.9.

```
> reticulate::conda_python()
[1] "C:\\Anaconda3\\envs\\r-reticulate\\python.exe"
```

But my system python is the 3.9 one (not anaconda):

```
> Sys.which("python")
                                                                    python 
"C:\\Users\\xxxx\\AppData\\Local\\Programs\\Python\\Python39\\python.exe" 
```

So I added `RETICULATE_PYTHON` environment variable and pointed it to `Sys.which("python")`, making `reticulate` use that version.

And Rmarkdown with Plotnine is working now :) - thank you.
If you think there are any issues in using the system python for `reticulate`  please let me know. Otherwise, I will just leave it like that.

**Comment by cderv** [comment] 2021-06-29 09:22
Oh thanks for all this. So this is an issue with conda. 🤔 

I don't think there is much to report or do. Python on Windows is now way better ! I don't there is need anymore to advice for using miniconda in reticulate, but I think they will switch. 

It could just be an issue in reticulate if your system python is not found. I think **reticulate** will use r-reticulate conda env in priority unless you tell it otherwise as you have done. Which is a great way of doing it. 

I'll close this now.

Feel free to report in reticulate anyway if you feel that the user experience could be improved.

**Closed by cderv** 2021-06-29 09:22 UTC
Labels: python / reticulate, reprex

**Comment by Courvoisier13** [comment] 2021-06-29 09:52
Ok, thanks. Yes, I've been noticing that python on windows is better than anaconda and been switching to it slowly on my projects. Happy to see you think that as well. I should accelerate my transition. I'll report on `reticulate` just for their FYI.
