### ISSUE TITLE
knitr::include_graphics generates HTML instead of markdown code (for local JPEG images)

### ISSUE THREAD

**Issue by littprivatliv** [rstudio/rmarkdown#1386] opened 2018-06-26 13:46 UTC
I need the markdown output of an R Markdown file to convert it with pandoc manually. But when I use `knitr::include_graphics` to include local JPEG images and knit to HTML with `keep_md` (or to markdown), these JPEG images are embedded in HTML code instead of markdown code.

This does not happen when I embed PNG, SVG or PDF images with `knitr::include_graphics`, nor when the path to the JPEG image is a URL. Embedding the same image with normal markdown syntax (`![caption](file.jpg)`) works as intended.

On the other hand, in the temporary `$FILENAME.knit.md` generated when knitting to Word, all images are embedded correctly (in markdown). When knitting to HTML or markdown, local JPEG images are embedded in HTML in the temporary markdown file. When knitting to PDF, the same images are embedded in LaTeX code (while the rest are in markdown).

This bug might be related to the one that forced me to convert markdown output from knitr manually with pandoc in the first place: #1338. Labels for cross-referencing are included in most examples below, but as the minimal example without caption or reference shows, they are independent from this bug.

This problem with `include_graphics` and local JPEG files is fairly recent. The person I'm helping ran into it after updating their R packages, but I don't know from which versions. I can reproduce it with the newest packages installed.

Attempted fixes that did not work:

* rename the file from .jpg to .jpeg
* use absolute local path to file: `C:/` etc.
* use `file://` for local path (not accepted by pandoc)
* not using opts_chunk `results='asis'` (which is necessary for cross-references to work

The only fix I can think of is to grap the temporary markdown file when knitting to Word, but the original document is much more complex than this MWE and it would entail other limitations, e.g. with `include_before`. Also, that would be the second time I have to hack my way around a problem because because of a bug, not a missing feature, in rmarkdown/knitr,

MWE:

	---
	output:
	  html_document:
	    df_print: paged
	    keep_md: yes
	  md_document:
	    variant: markdown
	  pdf_document:
	    keep_tex: yes
	  word_document: default
	---

	```{r, echo = FALSE}
	knitr::opts_chunk$set(echo=FALSE,results='asis')
	```

	```{r, echo=FALSE, fig.cap="Works: Code chunk, JPEG image, https:// file path"}
	knitr::include_graphics("https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Lichtenstein.jpg/487px-Lichtenstein.jpg")
	cat("{#fig:1st_reference}")
	```

	Markdown output:

	```
	![Works: Code chunk, JPEG image, https:// file path](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Lichtenstein.jpg/487px-Lichtenstein.jpg){#fig:1st_reference}
	```

	```{r, echo=FALSE, fig.cap="Does not work: Code chunk, JPEG image, relative local file path"}
	knitr::include_graphics("Lichtenstein.jpg")
	cat("{#fig:2nd_reference}")
	```

	Markdown output:

	```
	<div class="figure">
	<img src="Lichtenstein.jpg" alt="Does not work: Code chunk, JPEG image, relative local file path" width="487" />
	<p class="caption">Does not work: Code chunk, JPEG image, relative local file path</p>
	</div>{#fig:2nd_reference}
	```

	Does not work: Code chunk, JPEG image, relative local file path, without caption or reference

	```{r, echo=FALSE}
	knitr::include_graphics("Lichtenstein.jpg")
	```

	```{r, echo=FALSE, fig.cap="Works: Code chunk, PNG image, relative local file path"}
	knitr::include_graphics("Felis_silvestris_silvestris_small_gradual_decrease_of_quality.png")
	cat("{#fig:3rd_reference}")
	```

	```{r, echo=FALSE, fig.cap="Works: Code chunk, PNG image, https:// file path"}
	knitr::include_graphics("https://upload.wikimedia.org/wikipedia/commons/e/e9/Felis_silvestris_silvestris_small_gradual_decrease_of_quality.png")
	cat("{#fig:4th_reference}")
	```

	![Does work: Markdown, JPEG image, relative local file path](Lichtenstein.jpg){#fig:5th_reference}

```
> devtools::session_info("rmarkdown")
Session info ------------------------------------------------------------------------------------------------------------
 setting  value                        
 version  R version 3.5.0 (2018-04-23) 
 system   x86_64, mingw32              
 ui       RStudio (1.1.447)            
 language (EN)                         
 collate  Norwegian-Nynorsk_Norway.1252
 tz       Europe/Berlin                
 date     2018-06-26                   

Packages ----------------------------------------------------------------------------------------------------------------
 package   * version date       source                            
 backports   1.1.2   2017-12-13 CRAN (R 3.5.0)                    
 base64enc   0.1-3   2015-07-28 CRAN (R 3.5.0)                    
 digest      0.6.15  2018-01-28 CRAN (R 3.5.0)                    
 evaluate    0.10.1  2017-06-24 CRAN (R 3.5.0)                    
 glue        1.2.0   2017-10-29 CRAN (R 3.5.0)                    
 graphics  * 3.5.0   2018-04-23 local                             
 grDevices * 3.5.0   2018-04-23 local                             
 highr       0.7     2018-06-09 CRAN (R 3.5.0)                    
 htmltools   0.3.6   2017-04-28 CRAN (R 3.5.0)                    
 jsonlite    1.5     2017-06-01 CRAN (R 3.5.0)                    
 knitr     * 1.20    2018-02-20 CRAN (R 3.5.0)                    
 magrittr    1.5     2014-11-22 CRAN (R 3.5.0)                    
 markdown    0.8     2017-04-20 CRAN (R 3.5.0)                    
 methods   * 3.5.0   2018-04-23 local                             
 mime        0.5     2016-07-07 CRAN (R 3.5.0)                    
 Rcpp        0.12.17 2018-05-18 CRAN (R 3.5.0)                    
 rmarkdown   1.10.2  2018-06-26 Github (rstudio/rmarkdown@1f5b299)
 rprojroot   1.3-2   2018-01-03 CRAN (R 3.5.0)                    
 stats     * 3.5.0   2018-04-23 local                             
 stringi     1.1.7   2018-03-12 CRAN (R 3.5.0)                    
 stringr     1.3.1   2018-05-10 CRAN (R 3.5.0)                    
 tinytex     0.5     2018-04-16 CRAN (R 3.5.0)                    
 tools       3.5.0   2018-04-23 local                             
 utils     * 3.5.0   2018-04-23 local                             
 yaml        2.1.19  2018-05-01 CRAN (R 3.5.0)

**Comment by tallguyjenks** [comment] 2019-08-15 00:28
@littprivatliv 
shot in the dark here, for some of the file path references, instead of forward slashes, try escaped backward slashes? `![test](C:\\user\\desktop\\img.png)`

**Comment by cderv** [comment] 2020-10-27 16:52
Hi @littprivatliv , 

Thanks for the report. 

The example you provide is also not reproducible (because I don't have the files and url is not working) so I can't check myself. 

Is it still an issue for you ?  `include_graphics` is in **knitr** and it has evolved since 2018.

Thank you

**Comment by cderv** [comment] 2022-01-12 10:53
As there has not been any activity since last comment some time ago now, I'll close this issue. 

Please reopen if this is still an issue for you. Thank you!

**Closed by cderv** 2022-01-12 10:53 UTC
Labels: reprex
