### ISSUE TITLE
tidy=TRUE not being picked up

### ISSUE THREAD

**Issue by AlexIoannides** [rstudio/rmarkdown#790] opened 2016-08-31 15:24 UTC
Hello, 

Within a `html_notebook`, I am trying to use the `tidy=TRUE` option to retain blank spaces in the following code chunk,

```r
{r load_packages, echo=TRUE, message=FALSE, warning=FALSE, tidy=TRUE}
# load packages
library(sparklyr)
library(dplyr)
library(DBI)
library(DT)

# configure and connect to Spark cluster
config <- spark_config()
config[['spark.executor.memory']] <- "8g"

sc <- spark_connect(master = "spark://localhost:7077", 
                    spark_home = "/applications/spark-2.0.0",
                    config = config, app_name = "common-context")
```

When I check the Viewer, however, the blank lines have been removed,

![screen shot 2016-08-31 at 16 21 06](https://cloud.githubusercontent.com/assets/5968486/18134639/00c1eab4-6f97-11e6-95f2-d89b9d782442.png)

If I copy the code to the clipboard and run `tidy_source()` from the command line, then I get the output I would expect.

Any help would be greatly appreciated.

I am running R Studio v0.99.1273, R 3.3.0 and rmarkdown v1.0.9001.

**Comment by yihui** [comment] 2016-08-31 15:51
I cannot reproduce this issue. Can you provide `devtools::session_info('rmarkdown')`?

**Comment by AlexIoannides** [comment] 2016-08-31 16:41
Sure:

```
Session info ---------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.0 (2016-05-03)
 system   x86_64, darwin13.4.0        
 ui       RStudio (0.99.1273)         
 language (EN)                        
 collate  en_GB.UTF-8                 
 tz       Europe/London               
 date     2016-08-31                  

Packages -------------------------------------------------------------------------------------------------------------------------
 package   * version  date       source                            
 base64enc   0.1-3    2015-07-28 CRAN (R 3.2.0)                    
 bitops      1.0-6    2013-08-17 CRAN (R 3.1.2)                    
 caTools     1.17.1   2014-09-10 CRAN (R 3.1.2)                    
 digest      0.6.10   2016-08-02 CRAN (R 3.3.0)                    
 evaluate    0.9      2016-04-29 CRAN (R 3.3.0)                    
 formatR     1.4      2016-05-09 CRAN (R 3.3.0)                    
 highr       0.6      2016-05-09 CRAN (R 3.3.0)                    
 htmltools   0.3.5    2016-03-21 CRAN (R 3.2.4)                    
 jsonlite    1.0      2016-07-01 CRAN (R 3.3.0)                    
 knitr       1.14     2016-08-13 CRAN (R 3.3.0)                    
 magrittr    1.5      2014-11-22 CRAN (R 3.1.2)                    
 markdown    0.7.7    2015-04-22 CRAN (R 3.2.0)                    
 mime        0.5      2016-07-07 CRAN (R 3.3.0)                    
 Rcpp        0.12.6   2016-07-19 CRAN (R 3.3.0)                    
 rmarkdown   1.0.9001 2016-08-02 Github (rstudio/rmarkdown@c5f8411)
 stringi     1.1.1    2016-05-27 CRAN (R 3.3.0)                    
 stringr     1.1.0    2016-08-19 CRAN (R 3.3.0)                    
 yaml        2.1.13   2014-06-12 CRAN (R 3.1.2)   
```

Thanks for the quick reply.

**Comment by yihui** [comment] 2016-09-03 05:03
I do not see anything particularly suspicious, but you can try to upgrade your RStudio to its current preview version: https://www.rstudio.com/products/rstudio/download/preview/

I'm using R 3.3.1, but I don't think that is the reason why I cannot reproduce your issue. You probably also need to reinstall the development version of rmarkdown (c5f8411 is no longer the latest).

**Comment by AlexIoannides** [comment] 2016-09-05 09:30
That has appeared to do the trick. Thanks.

**Comment by AlexIoannides** [comment] 2016-09-07 20:44
Okay, I've just realised what is happening and when.

If I clear all output and preview the notebook, then I get blank lines as expected. 

But after I run the chunks, then I loose blank lines.

**Comment by yihui** [comment] 2016-09-07 21:15
Okay, I can reproduce what you described now.

@jmcphers I guess you might be the right person to solve this problem. A minimal example:

    ---
    output: html_notebook
    ---
    
    ```{r tidy=TRUE}
    x=1
    
    1+1
    ```

**Comment by jmcphers** [comment] 2016-09-07 21:29
Yes, I think a fix for this would need to happen on the IDE side since it's emitting the unformatted code. I've opened a case on our end.

**Closed by jmcphers** 2016-09-07 21:29 UTC

**Comment by smbache** [comment] 2016-11-07 21:07
I have the same experience in the newest Rstudio when previewing Notebooks.

**Comment by xhudik** [comment] 2017-07-26 12:25
same with me: https://stackoverflow.com/questions/45306837/rmarkdown-preserve-source-code-formatting-in-code-cell

@jmcphers - pls.  where is the info about the bug in RStudio side?

**Comment by jmcphers** [comment] 2017-07-26 15:28
Sorry, we don't currently have a public bug tracker (working on it!).

**Comment by xhudik** [comment] 2017-07-27 05:58
@jmcphers - the bug is open in your system - and it is not solved yet - correct? Thanks

**Comment by jmcphers** [comment] 2017-07-27 16:22
Yes, that's correct.
