### ISSUE TITLE
Pandoc 2.0 command line changes

### ISSUE THREAD

**Issue by nverno** [rstudio/rmarkdown#1188] opened 2017-11-08 01:50 UTC
I ran into some trouble trying to `spin` some R documents to html. It seems that pandoc changed its command line arguments in the [recent version](https://pandoc.org/releases.html#pandoc-2.0.1.1-04-november-2017). Notably, I'm getting the error 

> --smart/-S has been removed.  Use +smart or -smart extension instead.

Also, `--latex-engine` is changed to `--pdf-engine`.

**Comment by yihui** [comment] 2017-11-08 05:19
Duplicate of #1120

**Closed by yihui** 2017-11-08 05:19 UTC
