### ISSUE TITLE
find_external_resources errs with variable chunk eval

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rmarkdown#1247] opened 2018-01-17 19:44 UTC
This test document was trimmed from a much larger one. It shows that a variable used to allow / prohibit the evaluation of a chunk produces an error (which appears to be ignored).

````
---
output: html_document
---

```{r setup,echo=FALSE}
hasNotes <- FALSE
```

Here is some text in a document.

```{r echo = FALSE, results = 'asis', eval = hasNotes}
cat("**We have notes!**\n")
```
````

Run the following in the R console:
```
rmarkdown::find_external_resources("error.Rmd")
```

Here's the output:
```
Error in eval(x, envir = envir) : object 'hasNotes' not found
[1] path     explicit web     
<0 rows> (or 0-length row.names)
```

The `find_external_resources` function is used by `rsconnect` to discover files referenced by an Rmd that need to be included in a deployment bundle:
https://github.com/rstudio/rsconnect/blob/def0d46c806588af4b3c45853489eb997c97158d/R/deployDoc.R#L54

We don't really want to execute the document when analyzing it for resources. I was surprised to see this error about `hasNotes`. The `find_external_resources` function is supposed to be making "best effort" to identify resources. 

I do not know if this error is preventing resource discovery; it appears to be working fine. The error in my deploy console made me question it.

**Comment by yihui** [comment] 2018-01-17 19:56
Duplicate of #1154

**Comment by aronatkins** [comment] 2018-01-17 20:44
@yihui Is there a way to suppress that `purl` error? It's ugly when appearing in an `rsconnect` deploy stream and gives the impression that things aren't quite right. Maybe `rsconnect` just needs to silence it somehow?

```
Preparing to deploy document...DONE
Uploading bundle for document: 3...Error in eval(x, envir = envir) : object 'hasNotes' not found
DONE
Deploying bundle: 8 for document: 3 ...
```

**Comment by yihui** [comment] 2018-01-17 20:54
I guess it will require a change in **knitr**. I'll see how difficult it is.

**Comment by yihui** [comment] 2018-01-25 22:04
Should be fixed now. Thanks for the report!

**Closed** 2018-01-25 22:03 UTC
