### ISSUE TITLE
Strange font size changes in code blocks of package vignettes in mobile device browsers

### ISSUE THREAD

**Issue by IndrajeetPatil** [rstudio/rmarkdown#2216] opened 2021-09-17 07:55 UTC
# Description of the issue

While reading package vignettes on my **iPhone** (I can't verify if the same holds true for android devices), I realized this strange behaviour where **only in code blocks** the font size changes haphazardly. I could reproduce similar behaviour across Safari and Chrome browsers, multiple package vignettes, and screen orientations (see attached examples).

I do **not** observe the same behaviour when I read the exact same vignettes on a laptop or on when these vignettes are rendered on `{pkgdown}` websites.

Given the extremely specific circumstances under which this behaviour is observed, I am not sure if this is an issue with `{knitr}`, `{rmarkdown}`, `pandoc`, CRAN, mobile device browsers, or just my iPhone. If you can't reproduce any of this, feel free to close this issue. 

# Examples

This is just a random sampling I did while creating this issue and this is likely observed for many other vignettes

- ggside: https://cran.r-project.org/web/packages/ggside/vignettes/ggside_aes_mapping.html

![IMG_7812](https://user-images.githubusercontent.com/11330453/133744257-50b2a1fa-7801-49e6-8a04-6a53859d3210.jpg)

- ggmosaic: https://cran.r-project.org/web/packages/ggmosaic/vignettes/ggmosaic.html

![IMG_7810](https://user-images.githubusercontent.com/11330453/133744266-9a0507e8-1cf2-48e5-af52-d52e0ddcfd60.jpg)

- treemapify: https://cran.r-project.org/web/packages/treemapify/vignettes/introduction-to-treemapify.html

![IMG_7811](https://user-images.githubusercontent.com/11330453/133744270-bbbd8b1a-f704-463a-97e2-6ce608df251b.jpg)

- dplyr: https://cran.r-project.org/web/packages/dplyr/vignettes/compatibility.html

![IMG_7813](https://user-images.githubusercontent.com/11330453/133744272-b1ad5110-d3f7-46c0-be1c-42ff33c76b2e.jpg)

**Comment by cderv** [comment] 2021-09-17 08:02
Duplicate of #1504

**Comment by cderv** [comment] 2021-09-17 08:03
Thanks for the report @IndrajeetPatil ! 

It has already been reported and we don't really where it comes from unfortunately. It requires difficult investigation as it happens only on phones it seems. 

I'll close this one and keep the other one to track this. 

Thanks!

**Closed by cderv** 2021-09-17 08:03 UTC

**Comment by IndrajeetPatil** [comment] 2021-09-17 08:08
Good to know that this is a known issue and, indeed, seems like a super tricky issue to resolve.
