### ISSUE TITLE
Can't execute multiple lines in console from file created from R Markdown template

### ISSUE THREAD

**Issue by jgellar** [rstudio/rmarkdown#622] opened 2016-02-18 21:02 UTC
I have created an R Markdown template, which users an output format we created, following the instructions [here](http://rmarkdown.rstudio.com/developer_document_templates.html). I have created a new R Markdown document from this template, and entered a few code chunks which I would like to execute in the Console. However, when I highlight more than one line of code and try to execute them together, I get the following error:

```
> x <- 1 + 1
> y <- x + x
"rror: unexpected input in "y <- x + x
```

In the above, `x <- 1 + 1` was a line that I executed on its own, and `y <- x + x` was the first line of a two-line execution. Note how the opening `E` is cut off in the error message, and how the parentheses don't seem to be in the right place. This error also occurs if I use the new "Play" button to run the current R chunk.

What's weird is that if I save the file, close it, and re-open it, the bug goes away. Also if I copy the text into another text editor, and then copy it back into RStudio, the bug goes away. However, if I copy and paste the text from one R script to another within RStudio, I get the error message (even if I only copy the actual R code and leave off the text outside the chunks).

I have created a video showing all of this strange behavior, which you can access [here](https://www.dropbox.com/s/wlx54vkkg2d8ux6/BugDemo_JEG.mp4?oref=e&n=526479647). The video does not show this, but I do not get this error if I do all the same steps in an R Markdown file created using the default HTML template.

Unfortunately I cannot share my package due to my company's policies, but hopefully this is enough to go on for someone to suggest a solution. My feeling is that there has to be something in my `skeleton.Rmd` file that is triggering the error, I just have no idea what it could be.

Here is my session info:

```
> devtools::session_info()
Session info -------------------------------------------------------
 setting  value                       
 version  R version 3.2.3 (2015-12-10)
 system   x86_64, mingw32             
 ui       RStudio (0.99.878)          
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2016-02-18                  

Packages -----------------------------------------------------------
 package  * version date       source        
 devtools   1.10.0  2016-01-23 CRAN (R 3.2.3)
 digest     0.6.9   2016-01-08 CRAN (R 3.2.3)
 knitr      1.12.3  2016-01-22 CRAN (R 3.2.3)
 memoise    0.2.1   2014-04-22 CRAN (R 3.2.3)
 yaml       2.1.13  2014-06-12 CRAN (R 3.2.3)
```

Any guidance would be appreciated.

**Comment by yihui** [comment] 2016-02-18 21:45
Thanks a lot for the detailed bug report (especially for the video to demonstrate the issue)! It appears that either there is a weird invisible character after `y + y`, or RStudio IDE added such a character after `y + y`. This is probably not an rmarkdown issue, but an RStudio IDE issue instead. Hopefully someone from the IDE team will investigate it.

**Comment by jgellar** [comment] 2016-02-18 22:42
I agree that it is probably a bug with the IDE, but it only happens when I start a file from this R markdown template. Will someone from the IDE team see the issue here, or is there somewhere else I should post it? I was surprised that there does not seem to be an issue tracker at https://github.com/rstudio/rstudio .

**Comment by jjallaire** [comment] 2016-02-18 22:44
@kevinushey Could you take a look at this?

**Comment by kevinushey** [comment] 2016-02-18 22:59
@jgellar, does the `mprtemplates` package live online anywhere?

**Comment by kevinushey** [comment] 2016-02-18 23:09
@jgellar, can you try running this code in the R console and let me know what the output is? (Be sure to set `path` to the location of your skeleton Rmd file)

```R
path <- "<path to your file>"
contents <- readChar(path, file.info(path)$size, TRUE)
raw <- charToRaw(contents)
unique(raw[raw < 32])
```

**Comment by jgellar** [comment] 2016-02-19 00:57
@kevinushey, unfortunately the package is not online anywhere, as I work for a private company and we like to keep all software internal. I may be able to send you the tarball in an email or something like that, but I am not allowed to post it publicly.

Here's what happened when I tried your code:
```
> path <- "bugtest.Rmd"
> contents <- readChar(path, file.info(path)$size, TRUE)
> raw <- charToRaw(contents)
> unique(raw[raw < 32])
[1] 0d 0a
```

Recall though that the bug doesn't occur if I save the file, close it, and open it. Above, I didn't even close and open the file (so as I mention in the email, it still does result in an error message if I run the code from the file). However, the process of "saving" might change something.

I also tried running your code on the skeleton.Rmd file for the rmarkdown template, but got the same result:
```
> path <- "../mprtemplates/inst/rmarkdown/templates/mpr_report/skeleton/skeleton.Rmd"
> contents <- readChar(path, file.info(path)$size, TRUE)
> raw <- charToRaw(contents)
> unique(raw[raw < 32])
[1] 0d 0a
```

**Comment by kevinushey** [comment] 2016-02-19 01:12
Hi @jgellar,

Thanks -- I think we've narrowed down this problem being due to the documents having a mix of line endings, with some lines ending with only a carriage return (0d) and some ending with a mix of CR + LF (0d 0a) or just plain LF (0a). RStudio is likely fixing up these line feeds behind the scenes when it saves the document (hence why the error does not persist beyond saving, closing, and reopening the document), so my suspicion is that the line endings need to be fixed in your template files.

(Of course, RStudio should also do a better job of handling this on its own!)

**Comment by jgellar** [comment] 2016-02-19 02:12
`0d 0a` is the same result that I get when I run this code on any R script, even one that doesn't cause an error. In fact, if I run that last line without wrapping it in `unique()`, it appears that every line ends with CR + LF (0d 0a):

```
raw[raw<32]
 [1] 0d 0a 0d 0a 0d 0a 0d 0a 0d 0a 0d 0a 0d 0a 0d 0a 0d 0a 0d 0a 0d
[22] 0a 0d 0a 0d 0a 0d 0a 0d 0a 0d 0a 0d 0a 0d 0a 0d 0a 0d 0a 0d 0a
[43] 0d 0a 0d 0a
> as.numeric(raw[raw<32] == "0d")
 [1] 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0
[33] 1 0 1 0 1 0 1 0 1 0 1 0 1 0
```
(note that they alternate). Also, if I look at `raw` for the `skeleton.Rmd` file, every 0d is followed by a 0a:
```
> path <- "../mprtemplates/inst/rmarkdown/templates/mpr_report/skeleton/skeleton.Rmd"
> contents <- readChar(path, file.info(path)$size, TRUE)
> raw <- charToRaw(contents)
> idx <- which(as.character(raw)=="0d")
> table(as.character(raw)[idx+1])

 0a 
116 
```

Are you sure this is the root of the problem? This seems like the result I would expect. If you do think this is still the problem, how would you suggest I go about fixing it? Manually going into skeleton.Rmd, deleting every new line and pressing "Enter" to replace it?

By the way, I am running this on Windows.

**Comment by kevinushey** [comment] 2016-02-19 02:49
Thanks for looking into this further!

I'm still reasonably certain this is the cause, although it might be more subtle (e.g. perhaps RStudio is accidentally mixing CR+LF linefeeds from one document with LF linefeeds from another document behind the scenes, when constructing the template -- e.g. perhaps the YAML header is treated with regular LF, but the Rmd itself is treated with CR + LF, and those CRs don't get stripped out?).

Either way, we should have a candidate fix for this soon.

**Comment by jgellar** [comment] 2016-02-19 16:28
@kevinushey - if I pull the new version of the rstudio package from Github, does that contain the bug fix?

I have been given permission to post the package on github as a private repo, and gave you permission to access it so you can see the bug. Remember the bug might only be occurring on Windows.

Some updates on things I discovered this morning:

* We have 5 R Markdown templates in the package, and it turns out the bug occurs in any of the 5 templates. So it is not specific to any one skeleton.Rmd file
* I replaced the skeleton.Rmd file from the MPR Report template with the default template for HTML documents from R Markdown. To do this I deleted my old skeleton.Rmd file, created a new R Markdown document from the HTML document template, and simply saved it (with no changes) as skeleton.Rmd in the appropriate folder. The error still occurs. This indicates that it doesn't have anything to do with my mpr_report output format.
* Recall, though, if I create a new .Rmd document direct from rmarkdown's HTML document template, I do not get an error. So it does have something to do with the templates in our package.

**Comment by yihui** [comment] 2017-09-01 05:53
Closing since this is an RStudio IDE issue, but please feel free to let us know if the latest version of RStudio does not fix your issue.

**Closed by yihui** 2017-09-01 05:53 UTC
Labels: rstudio ide
