### ISSUE TITLE
HTML output of Stan chunks can be malformed

### ISSUE THREAD

**Issue by bgoodri** [rstudio/rmarkdown#907] opened 2016-12-13 20:47 UTC
With RStudio >= 1.0, when knitting a RMarkdown file to HTML, a chunk with Stan code can render improperly unless extra spacing is included. 

For example, this chunk

    ```{stan output.var="test", eval = FALSE}
    parameters {real < lower = 0 > theta;}
    model {target += exponential_lpdf(theta | 1);}
    ```

looks okay when knit to HTML. 

However, without the extra space before and after the angle brackets, as in

    ```{stan output.var="test", eval = FALSE}
    parameters {real<lower = 0> theta;}
    model {target += exponential_lpdf(theta | 1);}
    ```

the HTML file omits the <. 

Similarly, without the extra spaces before and after the equal sign, as in

    ```{stan output.var="test", eval = FALSE}
    parameters {real < lower=0 > theta;}
    model {target += exponential_lpdf(theta | 1);}
    ```

the HTML omits the first =.

If you knit to PDF, none of these problems occur, so I think it is probably as issue that `<` and `>` need to be interpreted literally in the HTML. The Stan language is whitespace insensitive, so it is a bit odd to have to add extra whitespace to get decent HTML output.

**Comment by jjallaire** [comment] 2016-12-13 21:44
@yihui Any idea why this might be the case?

**Comment by jmcphers** [comment] 2016-12-13 21:50
FWIW I was able to repro this trivially (had rmarkdown 1.2.9000 and knitr 1.15.1 locally). I wonder if it's actually a bug in the highlighter as the output from knitr looks fine prior to the highlight pass (HTML entities properly escaped):

    <pre class="stan"><code>parameters {real &lt;lower = 0&gt; theta;}
    model {target += exponential_lpdf(theta | 1);}</code></pre>

**Comment by yihui** [comment] 2016-12-13 21:51
I just tested it, and I think it is a highlight.js bug. We are still using 1.1, and the official version is 9.8.0 now: https://highlightjs.org/ I tested 9.8.0 and it works fine.

**Comment by jjallaire** [comment] 2016-12-13 21:51
We could test this by changing the highligher to one of the pandoc based
ones (the "default" and "textmate" highlighters use highlight.js, the other
highlighters use pandoc)

**Comment by jjallaire** [comment] 2016-12-14 12:59
For now I'd say the workaround is to change the highlighter to "tango", "pygments", "kate", "monochrome", "espresso", "zenburn", or "haddock"

**Comment by yihui** [comment] 2017-09-02 03:19
Duplicate of #988.

**Closed by yihui** 2017-09-02 03:19 UTC
