### ISSUE TITLE
ioslides_presentation ignores the template option

### ISSUE THREAD

**Issue by ignacio82** [rstudio/rmarkdown#460] opened 2015-06-27 00:53 UTC
I have a presentation with a personalized template

```
output: 
    ioslides_presentation:
       template: ./templates/mytemplate.html
```

But rmarkdown is ignoring that option and using the default template

```
/usr/lib/rstudio-server/bin/pandoc/pandoc /tmp/RtmpP2Yo3D/EdCenter.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output /tmp/RtmpP2Yo3D/file6f62a7095b9.html --smart --email-obfuscation none --variable widescreen --variable transition=0 --css styles/MPR_Ioslides_Styles.css --template /usr/local/lib/R/site-library/rmarkdown/rmd/ioslides/default.html --mathjax --variable ioslides-url=file6f62a7095b9_files/ioslides-13.5.1 
/usr/lib/rstudio-server/bin/pandoc/pandoc /tmp/RtmpP2Yo3D/EdCenter.utf8.md --to ioslides_presentation.lua --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output /tmp/RtmpP2Yo3D/ioslides-output6f66dbcb94b.html 
```

Is this a bug or am I doing something wrong?

Thanks a lot!

**Comment by jjallaire** [comment] 2015-06-27 07:26
It's because the template is a property of the ioslides_presentation format
(and therefore needs to be indented below it rather than at the same level).

**Comment by ignacio82** [comment] 2015-06-27 09:14
@jjallaire it is indented, makes no difference 

[Imgur](http://i.imgur.com/b7qeTgW.png)

**Comment by jjallaire** [comment] 2015-06-27 09:23
Okay, sorry about the mixup there.

ioslides_presentation doesn't actually support custom templates (it doesn't
have a template argument). This is mostly because ioslides is not a format
natively supported by pandoc so the built in template has a lot of special
sauce.

All of that said, you could workaround this by creating a new format that
just calls ioslides_presentation and then modifies the pandoc args to point
to your template.

**Comment by ignacio82** [comment] 2015-06-27 09:34
@jjallaire I think http://rmarkdown.rstudio.com/ioslides_presentation_format.html says that ioslide supports template: "You can also replace the underlying pandoc template using the template option:" 

If that is incorrect, can you point me in the right direction to create a new format? If I go that route, will I be able to upload the presentation to shinyapps.io ??

Right now what I'm doing is replacing `/usr/local/lib/R/site-library/rmarkdown/rmd/ioslides/default.html` in my computer with my file. But, that workaround does not work with shinyapps.io nor is very convinient for most users

Thanks!

**Comment by jjallaire** [comment] 2015-06-27 09:37
Unfortunately the docs are wrong there (I'll update them).

Here are the docs on creating a custom format:
http://rmarkdown.rstudio.com/developer_custom_formats.html

Hopefully you can sort out what you need from there (the resulting template
should indeed work on shinyapps.io).

**Comment by ignacio82** [comment] 2015-06-27 09:40
one more question. Can you point me to the ioslide format file? It will probably make sense to use it as my starting point.

Thanks a lot!

**Comment by ignacio82** [comment] 2015-06-27 20:34
I was able to use this repository as my starting point and modify `ioslides_presentation.R` to change the theme. Right now I'm using an absolute path instead of a relative path. That is:

     args <- c(args,
                "--template",
                pandoc_path_arg("/home/ignacio/MySlides/inst/rmd/ioslides/template.html"))

Where MySlides is the package that I created based on this one. Can you tell me how to change that to a relative path?  

Thanks a lot!

**Comment by jjallaire** [comment] 2015-06-27 22:18
You can use the system.file function as a way of creating a relative path:

system.file("rmd/ioslides/template.html", package="MySlides")

**Comment by ignacio82** [comment] 2015-07-01 02:28
@jjallaire Inside 'skeleton' I have a folder 'images' and inside that folder 'partner.png'. So when I create a rmarkdown using my template that folder and file are automatically created. is there a way of using relative path to that file? 

Basically, I'm trying to modify this part of the default.html:

    $if(logo)$
        slides > slide:not(.nobackground):before {
          font-size: 12pt;
          content: "";
          position: absolute;
          bottom: 20px;
          left: 60px;
          background: url($logo$) no-repeat 0 50%;
          -webkit-background-size: 30px 30px;
          -moz-background-size: 30px 30px;
          -o-background-size: 30px 30px;
          background-size: 30px 30px;
          padding-left: 40px;
          height: 30px;
          line-height: 1.9;
        }
    $endif$

My goal is to have partnet.png in the bottom right corner and $logo$ in the bottom left.

Thanks a lot!

**Comment by jjallaire** [comment] 2015-07-01 06:04
Yes, just set the URL to images/partner.png rather than $logo$

**Comment by ignacio82** [comment] 2015-07-01 10:14
It doesn' t work. Can you recommend me a way to debug this? Sorry to be a pain, this is very new to me

**Comment by jjallaire** [comment] 2015-07-01 11:26
Sorry I don't have time to debug this right now :-\

**Comment by ignacio82** [comment] 2015-07-01 11:29
I understand, thanks for all the help!

**Comment by jgellar** [comment] 2015-11-13 13:39
@jjallaire sorry to revive an old thread, i am having the same issue. In your second reply above, you seem to indicate that you can choose a new template by setting the `pandoc_args`, i.e.,
```
  temp <- rmarkdown::pandoc_path_arg(system.file("rmd/ioslides/default.html",
                                                 package="mypackage"))
  rmarkdown::ioslides_presentation(pandoc_args = c("--template", temp), ...)
```
However, the problem is that ioslides_presentation adds its own "--template" to the pandoc call, so now two "--template" options are specified. Is there a way to avoid this without re-writing a new ioslides_presentation?

**Comment by jjallaire** [comment] 2015-11-13 13:47
No, you can't create your own template for ioslides_presentation because
that is a custom format written with Lua (it's not a built-in pandoc
format).

**Comment by yihui** [comment] 2017-08-31 19:44
Closing since the original issue seems to have been resolved. There are a couple of of more issues, but I guess they are unlikely to be addressed in the future. You may try some other packages such as [xaringan](/yihui/xaringan) and [revealjs](/rstudio/revealjs) and see if you like them. More info: https://github.com/rstudio/rmarkdown/pull/404#issuecomment-326354500

**Closed by yihui** 2017-08-31 19:44 UTC
