### ISSUE TITLE
Inline R code with function call not working when rendering PDF

### ISSUE THREAD

**Issue by brechtdv** [rstudio/rmarkdown#2144] opened 2021-05-22 17:14 UTC
A call to `function()` within inline R code gives an error message when rendering to PDF, but works well for HTML and Word.

This is the error message:

```
Error in as.character(x) : 
  cannot coerce type 'closure' to vector of type 'character'
Calls: <Anonymous> ... paste -> hook -> .inline.hook.tex -> .inline.hook -> paste
Execution halted
```

This is some example Rmd code:

```
---
output:
  pdf_document: default
  html_document: default
---
Sentence with inline `r function() "function"`.
```

This is my sessionInfo:

```
> sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_Belgium.1252  LC_CTYPE=English_Belgium.1252    LC_MONETARY=English_Belgium.1252
[4] LC_NUMERIC=C                     LC_TIME=English_Belgium.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_4.1.0    htmltools_0.5.1.1 tools_4.1.0       yaml_2.2.1        rmarkdown_2.8     knitr_1.33       
 [7] xfun_0.23         digest_0.6.27     rlang_0.4.11      evaluate_0.14
```

Many thanks!

**Comment by yihui** [comment] 2021-05-25 17:20
It should not work for any output format. The inline expression should return a character string, or an object that could be coerced into character (a function cannot be coerced). I don't know why it worked for HTML and Word. @cderv When you have a chance, you may take a look.

**Comment by brechtdv** [comment] 2021-05-25 18:18
Thanks for looking into this!

Just for my info, does not `function() "function"` return a character string?

So it would give the same result as this, but shorter (and less efficient if `f()` were to be used multiple times):

````
---
output:
  pdf_document: default
---

```{r}
f <- function() "function"
```

Sentence with inline `r f()`.
````

**Comment by yihui** [comment] 2021-05-25 18:24
> Just for my info, does not `function() "function"` return a character string?

It returns a string, but itself is a function (an anonymous function), not a string. The function needs to be _called_ to return the string. To call it, you'd need `(function() "function")()`.

**Comment by cderv** [comment] 2021-05-25 20:28
@yihui I believe this is a **knitr** issue. This is because LaTeX and non LaTeX output does not have the same inline hook process. More specifically, non LaTeX inline is process through a intermediate function that modifies it in a way that the error is avoided.

``` r
res <- function() "dummy"

# this is the hook used
knitr::hooks_markdown()$inline
#> function (x) 
#> {
#>     if (is_latex_output()) 
#>         .inline.hook.tex(x)
#>     else {
#>         .inline.hook(format_sci(x, if (length(pandoc_to()) == 
#>             1L) 
#>             "latex"
#>         else "html"))
#>     }
#> }
#> <bytecode: 0x00000000144017f8>
#> <environment: 0x0000000013f98150>

# should error
knitr:::.inline.hook.tex(res)
#> Error in as.character(x): cannot coerce type 'closure' to vector of type 'character'
knitr:::.inline.hook(res)
#> Error in as.character(x): cannot coerce type 'closure' to vector of type 'character'

# but it does not because of this function
knitr:::format_sci(res)
#> [1] "dummy"
knitr:::format_sci
#> function (x, ...) 
#> {
#>     if (inherits(x, "roman")) 
#>         return(as.character(x))
#>     vapply(x, format_sci_one, character(1L), ..., USE.NAMES = FALSE)
#> }
#> <bytecode: 0x0000000014fdc2f0>
#> <environment: namespace:knitr>

# oddly this error
knitr:::format_sci_one(res)
#> Error in as.character(x): cannot coerce type 'closure' to vector of type 'character'

# So it seems vapply is doing coercion
vapply(res, knitr:::format_sci_one, character(1))
#> [1] "dummy"
```

<sup>Created on 2021-05-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

So for non PDF output, the inline result gets process and the function gets evaluated somehow.

Not sure why those two differents inline hook but it is something to change in **knitr**

**Comment by cderv** [comment] 2021-05-28 14:44
I'll close this here because the issue is now reported in knitr and it will be fix in https://github.com/yihui/knitr/pull/2007

**Closed by cderv** 2021-05-28 14:44 UTC
Labels: bug

**Comment by cderv** [comment] 2021-05-31 10:35
@brechtdv this should have now been fixed in last dev version of knitr

````r
remotes::install_github("yihui/knitr")
````
