### ISSUE TITLE
Error in R Markdown : Knit HTML (Object Not found )

### ISSUE THREAD

**Issue by LucianoSP** [rstudio/rmarkdown#463] opened 2015-07-03 14:07 UTC
Im having a problem (I believe related to encoding). When I run my code in Rstudio it works and outputs the expected result. When I try to knit HTML document, it gives an error (object not found). The object name (variable) has characters like çãó...)

Here is the code:

``` r
library(dplyr)
library(knitr)
setwd("~/GitHub/Servidores/Servidores")
camara = read.table("camara.csv", sep = ";", header = TRUE, fill = TRUE,  quote = "", dec = ",", fileEncoding = 'ISO8859-1')

camara$Cargo.Individualizado.do.Servidor = as.character(camara$Cargo.Individualizado.do.Servidor)
camara$Cargo = gsub("[0-9]*$", "", camara$Cargo.Individualizado.do.Servidor)
camara = camara %>% mutate(REMUNERACAO_BRUTA = Remuneração.Fixa + Vantagens.de.Natureza.Pessoal + Função.ou.Cargo.em.Comissão + Outras.Remunerações.Eventuais.Provisórias... + Abono.de.Permanência)

```

``` r kable
a = camara %>% group_by(Cargo) %>% filter(Remuneração.Fixa != 0 & !is.na(Remuneração.Fixa)) %>% summarise(N_Servidores = n(), Rem_Bruta_Media = mean(REMUNERACAO_BRUTA), Rem_Liq_Media = mean(Remuneração.Após.Descontos.Obrigatórios))
kable(a)
```

Then it gives the error:

``` r
processing file: camara.Rmd |.............
| 20% ordinary text without R code

|.......................... | 40% label: unnamed-chunk-1 |....................................... | 60% ordinary text without R code

|.................................................... | 80% label: kable

Quitting from lines 24-26 (camara.Rmd) Error in eval(expr, envir, enclos) : objeto 'Remuneração.Fixa' não encontrado Calls: ... filter -> filter_ -> filter_.tbl_df -> filter_impl -> .Call Execução interrompida

Translating -> Object 'Remuneração.Fixa' not found.
```

I would greatly appreciate some help with this.

**Comment by LucianoSP** [comment] 2015-07-03 14:09
```{r}
sessionInfo()
R version 3.2.1 (2015-06-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=Portuguese_Brazil.1252  LC_CTYPE=Portuguese_Brazil.1252    LC_MONETARY=Portuguese_Brazil.1252
[4] LC_NUMERIC=C                       LC_TIME=Portuguese_Brazil.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] knitr_1.10.5 dplyr_0.4.2 

loaded via a namespace (and not attached):
 [1] Rcpp_0.11.6     digest_0.6.8    assertthat_0.1  R6_2.0.1        DBI_0.3.1       magrittr_1.5    evaluate_0.7   
 [8] highr_0.5       stringi_0.5-5   lazyeval_0.1.10 rmarkdown_0.7   tools_3.2.1     stringr_1.0.0   yaml_2.1.13    
[15] parallel_3.2.1  htmltools_0.2.6
```

**Comment by LucianoSP** [comment] 2015-07-03 15:11
I just noticed that an old markdown documento, which used to work, doesn´t work anynome. For some reason, R Markdown complains if I use any character with accent (â, á) in the code, even though the same code runs fine in Rstudio console. I haven´t changed anything. What can be wrong?

**Comment by yihui** [comment] 2015-07-06 02:32
It is not clear to me whether this is due to changes in knitr, rmarkdown, or dplyr. Do you know the encoding of your Rmd file? If it is UTF-8, can you try to do this in the R console after setting the working directory to the directory of the Rmd file?

```r
library(knitr)
knit('camara.Rmd', encoding = 'UTF-8')
```

If this gives the same error, the problem may come from knitr or dplyr (we can rule out rmarkdown).

**Comment by LucianoSP** [comment] 2015-07-06 14:01
I saved the RMD with encoding (UTF-8)... It gives me this error:

 ```{r}
> knit('Relatorio.Rmd', encoding = 'UTF-8')


processing file: Relatorio.Rmd
  |.................................................................| 100%
  ordinary text without R code


output file: Relatorio.md

[1] "Relatorio.md"
Warning message:
invalid input found on input connection 'Relatorio.Rmd' 
 ```

**Comment by yihui** [comment] 2015-07-06 19:28
That is a warning instead of an error. Could you test your original `camara.Rmd` since that was the document that led to errors? This `Relatorio.Rmd` seems to be different with `camara.Rmd`.

**Comment by LucianoSP** [comment] 2015-07-06 20:15
Relatorio.cmd and camara.Rmd are very similar and lead to the same errors. Ive rewritten the camara.Rmd to exclude all accents (also renamed the columns of the dataset) because I needed it working. 

This is the error it produces (Note the same error: Object Título not found)
 ```{r}
The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

  |.......................................                          |  60%
  ordinary text without R code

  |....................................................             |  80%
label: unnamed-chunk-2 (with options) 
List of 3
 $ echo   : logi FALSE
 $ comment: logi NA
 $ cache  : logi FALSE


Quitting from lines 40-92 (relatorio.Rmd) 
Error in eval(expr, envir, enclos) : objeto 'Título' não encontrado
Calls: <Anonymous> ... as.data.frame -> filter_ -> filter_.tbl_df -> filter_impl -> .Call
Além disso: Warning message:
In in_dir(opts_knit$get("root.dir") %n% input_dir(), evaluate::evaluate(code,  :
  You changed the working directory to C:/documentos/PPA 2016-2019/tabelas (probably via setwd()). It will be restored to C:/R. See the Note section in ?knitr::knit
Execução interrompida
```

the code is (works in Rstudio but not in Rmarkdown):

```{r, echo=FALSE, warning=FALSE, message=FALSE}
setwd("C:/documentos/PPA 2016-2019/tabelas")
library(dplyr)

programas = read.csv(file = "programas.csv", header = TRUE, sep = ";")
metas = read.csv(file = "metas.csv", header = TRUE, sep = ";")
iniciativas = read.csv(file = "iniciativas.csv", header = TRUE, sep = ";")
objetivos = read.csv(file = "objetivos.csv", header = TRUE, sep = ";")
metas = metas %>% select(Programa, Objetivo, Codigo_Meta = Meta.do.Objetivo, Descricao_Meta = Descrição)
iniciativas = iniciativas %>% select(Programa, Objetivo, Iniciativa, Titulo_Iniciativa = Título)
objetivos = objetivos %>% select(Programa, Objetivo, Enunciado, Órgão)
objetivos = left_join(objetivos, programas, by="Programa" )
programas = programas %>% select(Programa, Titulo_Programa = Título)
tabela_metas = left_join(metas, objetivos, by="Objetivo")
tabela_metas = tabela_metas %>% select(Programa = Programa.x, Objetivo, Orgao = Órgão, Enunciado, Codigo_Meta, Descricao_Meta)
tabela_metas =  left_join(tabela_metas, programas, by="Programa")
tabela_metas =  tabela_metas %>% select(Programa, Titulo_Programa, Objetivo, Enunciado, Orgao, Codigo_Meta, Descricao_Meta)
tabela_metas = tabela_metas %>% arrange(Programa, Objetivo)
tabela_metas = tabela_metas %>% filter(!is.na(Enunciado))
tabela_iniciativas = left_join(iniciativas, programas, by="Programa")
tabela_iniciativas = left_join(tabela_iniciativas, objetivos, by="Objetivo")
tabela_iniciativas = tabela_iniciativas %>% select(Titulo_Programa, Objetivo, Enunciado, Iniciativa, Titulo_Iniciativa)
tabela_iniciativas =  tabela_iniciativas %>% arrange(Titulo_Programa, Enunciado)
tabela_iniciativas = tabela_iniciativas %>% filter(!is.na(Enunciado))
```

**Comment by LucianoSP** [comment] 2015-07-13 21:17
Hi yihui,
Is there anything else I can do to help figure this out?

**Comment by lzamparo** [comment] 2015-07-17 22:55
I'm having a similar problem with interaction between dplyr & knitr.  See this [gist](https://gist.github.com/lzamparo/d7b9f09354de12864d2c) that barfs with error: 
```
Error in eval(expr, envir, enclos) : unknown column 'region'
Calls: <Anonymous> ... group_by_.data.frame -> grouped_df -> grouped_df_impl -> .Call"
```

I can evaluate a block like so without any complaints:

```{r, echo=FALSE}
### Now compute the count totals for each band
all_chrs_dt_with_totals <- all_chrs_50kb %>% 
  group_by(region, test_name) %>%  
  summarise(totals = sum(counts)) 
```

But when I try to use `mutate` on the result of the last computation, I get the following error:

```{r, echo=FALSE}
### Now compute the proportion for each band
all_chrs_dt_with_proportions <- all_chrs_dt_with_totals %>%
  group_by(region) %>%
  mutate(proportion = 100 * (totals / sum(totals)))
```
 
^ this block fails with: "Quitting from lines 86-90 (genomic_anotation.rmd) 
Error in eval(expr, envir, enclos) : unknown column 'region'
Calls: <Anonymous> ... group_by_.data.frame -> grouped_df -> grouped_df_impl -> .Call"

At first I thought maybe it was a problem with how knitr performs evaluation (c.f [SO issue](http://stackoverflow.com/questions/29119052/r-using-dplyr-inside-a-function-exception-in-evalexpr-envir-enclos-unknow), [Hadley's book](http://adv-r.had.co.nz/Computing-on-the-language.html) ) but now I don't know.  Not entirely sure if my problem shares a cause with this issue, but the error messages looked similar enough to tack on to this thread.  Hope it helps you shed some light on this.

**Comment by yihui** [comment] 2015-07-18 05:36
@lzamparo I believe that is a different issue. The original issue in this thread was about character encoding. That said, if you can provide a minimal reproducible example, we can certainly take a look at it.

@LucianoSP Sorry, I have not got time to investigate this issue. A minimal reproducible example will help speed up the investigation.

**Comment by englianhu** [comment] 2015-09-29 23:43
I also faced same issue. Its working fine on R Console but not in **knit** button which similar with last month, the KNIT2HTML button suddenly changed to knit button again yesterday. Well, the KNIT2HTML button is working fine before changed to knit button yesterday.
```diff
- knitr terminated with status 1
```
After that I tried to run the `rmarkdown::render()` but there is another error prompt me. https://github.com/yihui/knitr/issues/1107
http://goobbe.com/questions/7035641/running-knitr-and-pandoc-for-html5-slides
```diff
> rmarkdown::render('Natural Language Analysis.Rmd')
- Error in system(paste(which, shQuote(names[i])), intern = TRUE, ignore.stderr = TRUE) : 
-  cannot popen '/usr/bin/which 'pandoc' 2>/dev/null', probable reason 'Cannot allocate memory'
```
Its working fine in knit but has no YAML header.
```diff
> knitr::knit2html('Natural Language Analysis.Rmd')
> devtools::session_info()
Session info ----------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.2 (2015-08-14)
 system   x86_64, linux-gnu           
 ui       RStudio (0.99.484)          
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2015-09-29
```

**Comment by yihui** [comment] 2015-09-30 03:08
@englianhu I have not heard of a "KNIT2HTML" button. What is that button? There is only a knit2html() function in knitr, and it only deals with R Markdown v1 as its help page has clarified.

Please post the full session info (you happen to have stripped off the most important part):

```r
library(knitr)
library(rmarkdown)
devtools::session_info()
```

**Comment by englianhu** [comment] 2015-10-01 08:22
wonder if this https://github.com/rstudio/rticles/issues/9#issuecomment-144649687 related?

**Comment by yihui** [comment] 2017-08-31 19:47
Closing since a minimal reproducible example has not been received yet.

**Closed by yihui** 2017-08-31 19:47 UTC

**Comment by annlaurawalker** [comment] 2017-09-01 13:38
I'm having some difficulty with knitr too

```
```{r, results='asis'}
library(knitr)
library(dplyr)
library(rmarkdown)
knitr::kable(table1)

```
```

produces
`Error in inherits(x, "list"): object 'table1' not found Calls: <Anonymous> ... withVisible -> eval -> eval -> <Anonymous> -> inherits`

**Comment by TanyaMurphy** [comment] 2017-10-01 22:43
I also got a similar error ("...cannot find function efaUnrotate...") **when using the knitr button** (windows 10, RStudio v.1.1.138, R v.3.4.1 64-bit, knitr v.1.17, rmarkdown v.1.6, semTools v.0.4-14), but it worked when I used rmarkdown::render([file with yaml block for output specifications]).

**Comment by TanyaMurphy** [comment] 2017-10-01 23:24
(Sorry, I was that the issue was closed due to there having been no minimal reproducible example provided after my first post. But it led to good things.)

While trying to create a minimal reproducible example, I think I narrowed the problem down to it being something about the R file I source in the real case (mentioned above). When I saved the R file to be sourced - because I was simplifying it for the min. example -  it worked! I had first tested it, line by line, before simplifying it so I think it has something to do with the encoding in the original sourced file (it was a little old ) and not any code I removed from the file. I think the solution is simply re-saving your files (whether a new name is necessary, I don't know).

**Comment by TanyaMurphy** [comment] 2017-10-01 23:53
Sorry, before my first posting (above), I didn't see that the issue had been closed due to no minimal reproducible example being provided. I've been trying to create a minimal reproducible example, but no luck -- it doesn't seem to be related to lines of R or markdown code and I'm not authorized to provide my real dataset. Will keep trying.

**Comment by svenku** [comment] 2017-10-02 19:56
Try clearing knitr cache, last item in knit dropdown menu. It helped me.

**Comment by grammilo** [comment] 2017-12-20 03:25
Clearing cache is not helping me

**Comment by ekapti** [comment] 2018-04-07 19:31
I am having a similar problem too. It gives an 'object not found' error when it comes to 'chained' functions. For example on this line: 

`mercury.speed <- mercury %>%
  group_by(speed) %>%
  summarise(fatalities_mean = mean(Fatalities),
            fatalities_n = length(Fatalities),
            vehicle_mean = mean(Vehicles),
            vehicle_n = length(Vehicles),
            crash = n())`

It says 'vehicle_mean' not found...

**Comment by mguideng** [comment] 2018-04-16 05:33
For "error in eval" errors in Rmd, the issue may be from the `knitr` evaluation option that styles the output of a chunk:
 ` ```{r eval=FALSE}`

or for the global option:
` knitr::opts_chunk$set(eval = FALSE)`

Try removing this option or setting it to `(eval = TRUE)`  before you press the Knit button and see if this helps. For alternatives to control the chunk output, look into the `include=F` or `results = "hide` options.

**Comment by Danidutch** [comment] 2018-11-25 16:04
Hi, 
I am having this error: 
Error in enorm(fit, mean = Tmean, sd =Esd) : object 'Tmean' not found calls: <Anonymous> ... withCallingHandlers -> withvisible -> eval -> eval -> dnorm Execution halted

On this line: 

fit <- set(min(mean_simulation), max(mean_simulation), lenght=100)
standard_fit <- norm(fit, mean=Tmean, sd=Esd)
hist(mean_simulation, breaks= n, prob=T, xlab = "means" , ylab =  "Count" , main = "Density of  Means")
lines(fit, standard_fit, pch= 2, col= "darkblue" , lty=5)

Thank you to help me. I do appreciate it!

**Comment by DeLaRiva** [comment] 2019-12-04 10:15
I have the following issue:

When I perform 

```
vars <- colnames(df)
id<- 1:nrow(df)

loess.filter <- function (x, span) loess(formula = paste(x, "id", sep = "~"),
                                         data = df,
                                         degree = 1,
                                         span = span)$fitted 
```
in the console, it works flawless. When I wrap```
 ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) ```
``` around that, I receive Warnung: _Error in model.frame.default: invalidTyp (closure) for the variable 'id'_
