### ISSUE TITLE
Code folding for chunks with different engines

### ISSUE THREAD

**Issue by Welliton309** [rstudio/rmarkdown#887] opened 2016-11-24 12:02 UTC
I would like to know if it is possible to use the option `code_folding: hide` for chunk with [different engies](http://rmarkdown.rstudio.com/authoring_knitr_engines.html). The generated HTML file of the example below only hides R code.

    ---
    title: "Code folding"
    output:
      html_document: 
        code_folding: hide
    ---
    
    R
    ```{r}
    dir()
    ```
    
    Bash
    ```{bash}
    ls
    ```
    
    Python
    ```{python}
    import os
    print(os.listdir("."))
    ```

**Comment by AlexAxthelm** [comment] 2017-03-28 15:41
This is related to #914

**Comment by yihui** [comment] 2017-10-16 21:49
Indeed. Duplicate of #914. We will see if we can support other engines in the future. Thanks for the report!

**Closed by yihui** 2017-10-16 21:49 UTC
