### ISSUE TITLE
Problem rendering document from R cmd while rendering from R-studio is working.

### ISSUE THREAD

**Issue by wolski** [rstudio/rmarkdown#1294] opened 2018-03-21 13:47 UTC
I do have a new installation of R and Rstudio (about one week old). While I am able to render documents with knit-> knit to pdf from R studios menu the compilation fails when I try to run the rendering from R console in the same R studio instance. with `rmarkdown::render`

The file I am trying to render is the Rmd template file produced by rstudio with open->new file-> R markdown.

I have no clue where even start looking for answers (where is the latex log file etc etc?)
I have a freshly installed Miktex 2.9
What follows is the error message and session info.
Help,  would be highly appreciated.

```
> rmarkdown::render("test.Rmd", output_format="pdf_document")


processing file: test.Rmd
  |.........                                                        |  14%
  ordinary text without R code

  |...................                                              |  29%
label: setup (with options) 
List of 1
 $ include: logi FALSE

  |............................                                     |  43%
  ordinary text without R code

  |.....................................                            |  57%
label: cars
  |..............................................                   |  71%
  ordinary text without R code

  |........................................................         |  86%
label: pressure (with options) 
List of 1
 $ echo: logi FALSE

  |.................................................................| 100%
  ordinary text without R code


output file: test.knit.md

"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS test.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output test.tex --template "C:\Users\wewol\OneDrive\Documents\R\win-library\3.4\rmarkdown\rmd\latex\default-1.17.0.2.tex" --highlight-style tango --latex-engine pdflatex --variable graphics=yes --variable "geometry:margin=1in" 
Error: Failed to compile test.tex.
In addition: Warning message:
running command '"pdflatex" -halt-on-error -interaction=batchmode "test.tex"' had status 1 
> 

```

```{r}
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] bookdown_0.7      Rcpp_0.12.15      rprojroot_1.3-2   digest_0.6.15     grid_3.4.3        plyr_1.8.4        backports_1.1.2   gtable_0.2.0     
 [9] magrittr_1.5      evaluate_0.10.1   scales_0.5.0      ggplot2_2.2.1     pillar_1.2.1      stringi_1.1.6     rlang_0.2.0       lazyeval_0.2.1   
[17] rmarkdown_1.9     tools_3.4.3       stringr_1.3.0     tinytex_0.4       munsell_0.4.3     xfun_0.1          yaml_2.1.18       compiler_3.4.3   
[25] DiceKriging_1.5.5 colorspace_1.3-2  htmltools_0.3.6   knitr_1.20        tibble_1.4.2     
> 
```

**Comment by rich-iannone** [comment] 2018-03-21 14:40
@wolski could you try knitting a PDF after an installation of tinytex via a `tinytex` package?

**Comment by rich-iannone** [comment] 2018-03-21 14:41
And I think that log files would appear here in your system:

`C:/Users/AppData/Local/MiKTeX/2.9/miktex/log/`

**Comment by yihui** [comment] 2018-03-21 16:04
Duplicate of #1285 

Please see solutions at https://github.com/rstudio/rmarkdown/issues/1285#issuecomment-374340175

**Comment by rich-iannone** [comment] 2018-03-21 16:19
@wolski given that this is a duplicate issue and that there are solutions available, I'm going to close this issue.

**Closed by rich-iannone** 2018-03-21 16:19 UTC

**Comment by wolski** [comment] 2018-03-22 20:01
Thank you. Problem solved.
