### ISSUE TITLE
[Weird behavior] Rstudio interface shakes when running a chunk of code from a Rmarkdown file

### ISSUE THREAD

**Issue by sibojan** [rstudio/rmarkdown#1143] opened 2017-09-14 06:29 UTC
Hi,
I have posted this issue on stackoverflow but got no reply yet. So I am re-posting here.

When Rstudio is running a chunk of code from a Rmarkdown file, we can see the move of the progress bar next to the line numbers.  However, all the line numbers will shake once. In addition, if some variables are assigned with certain values, the environment window will shake as well. Is there any way to disable this unnecessary behavior of  Rstudio? I found it quite distracting and annoying, especially with repetitive runs of chunks.

Thanks

**Comment by jjallaire** [comment] 2017-09-14 10:22
@jmcphers

**Comment by sibojan** [comment] 2017-09-25 22:59
Wonderful. That issue has been process by Rstudio Support at (https://support.rstudio.com/hc/en-us/community/posts/115007429027-Rstudio-shakes-when-running-a-chunk-of-code-from-a-Rmarkdown-file?page=1#community_comment_115005236188).

**Comment by kevinushey** [comment] 2017-09-25 23:01
We're now tracking this on RStudio's own internal tracker -- since the issue is independent of the `rmarkdown` package, I will close the issue here. Thanks for reporting @sibojan!

**Closed by kevinushey** 2017-09-25 23:01 UTC
