### ISSUE TITLE
citation_package: biblatex not working on windows platform

### ISSUE THREAD

**Issue by thiyangt** [rstudio/rmarkdown#1262] opened 2018-02-18 16:27 UTC
Here is a reproducible example of the problem:

# step 1

```
devtools::install_github("robjhyndman/MonashEBSTemplates")
library(MonashEBSTemplates)
```

# step 2

Then when you create a new Rmarkdown document, click "From Template",
Monash EBS Working Paper.

I uninstall my existing LaTeX distribution, and use
`tinytex::install_tinytex()`

Without the option 'citation_package: biblatex', bookdown is using the default citeproc. However, when this option is used, the referencing is not working anymore and my document contains only the refnames in bold instead of inline citations. So I really need to know why the citation-package: biblatex is not working.

This is similar to the question raised in here:
https://stackoverflow.com/q/44633939/559676

**Comment by yihui** [comment] 2018-02-20 16:51
Do you know if this is reproducible on other platforms (Linux or macOS)?

**Comment by thiyangt** [comment] 2018-02-20 19:36
Yes, this is reproducible on Linux and macOS.

**Comment by yihui** [comment] 2018-02-20 20:05
Okay. For now I don't have time and can only point you to the right direction to debug the issue by yourself:
https://github.com/yihui/tinytex/blob/02801b8fd926fb4144bb802fd1e9e5d8ef774222/R/latex.R#L169-L172

**Comment by thiyangt** [comment] 2018-02-21 03:50
Thanks Yihui, I'll work on it.

**Comment by cderv** [comment] 2020-10-23 14:47
I think this is fixed now. I can't reproduce. 
There is also the solution in https://stackoverflow.com/a/44677041/3436535
and the pandoc template for Latex now respect the option.

Please reopen or open a new issue if there is still a problem.

**Closed by cderv** 2020-10-23 14:47 UTC
Labels: Bug
