### ISSUE TITLE
Images in Power Point template load, but with error box

### ISSUE THREAD

**Issue by timdisher** [rstudio/rmarkdown#1419] opened 2018-08-01 02:05 UTC
I am using a powerpoint custom template that includes images in the slide master. When rendered in markdown these load as expected, but also have a box around them with the error message "The picture can't be displayed." I can delete this and everything looks fine, but it's a bit of a weird extra step.

**Comment by MartinInFrankfurtAM** [comment] 2018-08-02 11:35
Same here. 
In my first baby step I recreated the title page from the company template.potx 
within the potx-template produced from the pptx output of the Markup example.Rmd.
I got "The picture can't be displayed...." just like you.
For my next presentation, I will stay with knitting WORD output and handcraft my powerpoint.
The pain is at least predictable.

**Comment by rich-iannone** [comment] 2018-08-07 23:59
I can replicate the issue, using a valid custom template and an image in the master. Screenshot of this is below, where I dragged an image box to the bottom right to show the text. It can be deleted safely (and the image in the master slide is still there) but this is a (pandoc) bug.

As mentioned in another issue, Powerpoint support for R Markdown is for the most part handled by pandoc. There is another image issue dealing with Powerpoint output at [`jgm/pandoc`](https://github.com/jgm/pandoc/issues) so it seems like that is a better place to file the issue (although we are glad to hear of this, and, we can also communicate the problem to any pandoc developers we may work with in the future). Could you move this issue to that repo? This one will be closed since we really cannot directly act on it.

<img width="1224" alt="powerpoint_image_master" src="https://user-images.githubusercontent.com/5612024/43808551-6b5f229a-9a62-11e8-8abe-730ca96dc4e4.png">

**Comment by yihui** [comment] 2018-08-08 02:59
@rich-iannone It will be great if you can minimize the reproducible example to show that R Markdown is innocent. You may take a look at a few examples on [how I transferred issues](https://github.com/jgm/pandoc/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Ayihui) from our repositories to Pandoc, e.g., https://github.com/jgm/pandoc/issues/4055 and https://github.com/jgm/pandoc/issues/2878. When you ask an R Markdown user to file an issue to Pandoc, chances are he/she will use Rmd examples, and the Pandoc maintainer will need evidence to show the problem really belongs to Pandoc.

**Comment by rich-iannone** [comment] 2018-08-08 03:09
Yihui, thanks for the examples. @timdisher I will transfer this issue (and the other one) myself and produce a minimal code example and post in here and also in `jgm/pandoc`. The same example should show that the issue is with pandoc and also be easily interpretable/useful for Pandoc maintainers.

**Comment by yihui** [comment] 2018-08-08 03:12
Excellent. Thanks!

**Comment by rich-iannone** [comment] 2018-08-09 18:17
Now posted in https://github.com/jgm/pandoc/issues/4827.

**Closed by rich-iannone** 2018-08-09 18:17 UTC
