### ISSUE TITLE
Shiny backend does not load on subsequent calls to run() with flexdashboard

### ISSUE THREAD

**Issue by beansrowning** [rstudio/rmarkdown#1428] opened 2018-08-09 19:39 UTC
## Problem  

I have had frequent issues with a shiny dashboard (flexdashboard) loading properly after it is first rendered.
 
If I call `rmarkdown::run()` once, it will load perfectly, but any subsequent calls seem to have no shiny backend. 

If I manually delete the temp files (`%TEMP%/<user_id>/rmarkdown/...`), it starts working again.  

## Example  

Using the minimal example from #1193, changed to flexdashboard instead of html_document:  
`````markdown
---
title: "Rmd Bug"
flexdashboard::flex_dashboard:
  runtime: shiny
---

```{r}
textInput("days", "Days", 100)
```

```{r}
renderPrint(input$days)
```
`````

**The first run works as intended, and prints the number:**

![image](https://user-images.githubusercontent.com/25888380/43921032-957e1446-9be8-11e8-92c6-b9690f9caca7.png)

**After exiting and re-running, there isn't even an output box and changing input has no effect:**

![image](https://user-images.githubusercontent.com/25888380/43921095-c95d2e28-9be8-11e8-8327-87bb4aabbdd6.png)

## Locale  
```
Session info ------------------------------------------------------------------
 setting  value
 version  R version 3.5.0 (2018-04-23)
 system   x86_64, mingw32
 ui       RTerm
 language (EN)
 collate  English_United States.1252
 tz       America/New_York
 date     2018-08-09

Packages ----------------------------------------------------------------------
 package   * version date       source
 backports   1.1.2   2017-12-13 CRAN (R 3.5.0)
 base64enc   0.1-3   2015-07-28 CRAN (R 3.5.0)
 digest      0.6.15  2018-01-28 CRAN (R 3.5.0)
 evaluate    0.10.1  2017-06-24 CRAN (R 3.5.0)
 glue        1.2.0   2017-10-29 CRAN (R 3.5.0)
 graphics  * 3.5.0   2018-04-23 local
 grDevices * 3.5.0   2018-04-23 local
 highr       0.6     2016-05-09 CRAN (R 3.5.0)
 htmltools   0.3.6   2017-04-28 CRAN (R 3.5.0)
 jsonlite    1.5     2017-06-01 CRAN (R 3.5.0)
 knitr       1.20    2018-02-20 CRAN (R 3.5.0)
 magrittr    1.5     2014-11-22 CRAN (R 3.5.0)
 markdown    0.8     2017-04-20 CRAN (R 3.5.0)
 methods   * 3.5.0   2018-04-23 local
 mime        0.5     2016-07-07 CRAN (R 3.5.0)
 Rcpp        0.12.18 2018-07-24 Github (RcppCore/Rcpp@12f3c03)
 rmarkdown   1.10    2018-06-11 CRAN (R 3.5.0)
 rprojroot   1.3-2   2018-01-03 CRAN (R 3.5.0)
 stats     * 3.5.0   2018-04-23 local
 stringi     1.2.2   2018-05-02 CRAN (R 3.5.0)
 stringr     1.3.1   2018-05-10 CRAN (R 3.5.0)
 tinytex     0.5     2018-04-16 CRAN (R 3.5.0)
 tools       3.5.0   2018-04-23 local
 utils     * 3.5.0   2018-04-23 local
 yaml        2.1.19  2018-05-01 CRAN (R 3.5.0)
```  

Also tried the current dev version as of adb0279 and flexdashboard@024baff to no avail.

**Comment by cderv** [comment] 2020-10-28 16:36
Hi, 

thanks for the report and sorry for the delay. 

The syntax of your yaml header is incorrect. You are missing `output` which should contains the flexdashboard format, and the `runtime: shiny` should be at first level of the yaml; 

````md
---
title: "Rmd Bug"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r}
textInput("days", "Days", 100)
```

```{r}
renderPrint(input$days)
```
````

This works as expected. 

I'll close this. 

If you still have issue with flexdashboard, please open an issue there.

Thanks;

**Closed by cderv** 2020-10-28 16:36 UTC

**Comment by beansrowning** [comment] 2020-10-28 19:20
Thanks.  

I believe the YAML error was introduced in pasting into GitHub and not the source of the error I mentioned, but it's been a few years and my interim solution was just to delete the cached files in TEMP to force it to render again as I mentioned.

**Comment by cderv** [comment] 2020-10-29 09:25
> This was an issue with the shiny runtime attempting to use a stale cache instead of re-rendering, which was why it was posted here.

Is it still an issue ? If so, we may need to fix to avoid the pain of the workaround. I am willing to look into it. I just need more details as I was not able to reproduce on my own.

**Comment by beansrowning** [comment] 2020-10-29 17:18
I tried a few different setups but wasn't able to replicate--makes me think it might have been something on the shiny side that has since been fixed, in that case. Not too certain.

At any rate, thanks for following up!
