### ISSUE TITLE
Interleaving gridextra objects with plotly charts

### ISSUE THREAD

**Issue by ashleych** [rstudio/rmarkdown#1438] opened 2018-09-02 03:50 UTC
I want to  interleave GridExtra objects with a plotly chart using a for-loop or lapply. I have read several posts on this, including the very useful post on top-level expressions, and I believe I have tried them all. 
I am fairly sure this isnt an Issue and I am doing something wrong, as my knowledge of HTML and rmarkdown is limited. However,  I am posting here as my stackoverflow question hasnt received any responses https://stackoverflow.com/questions/52128100/interleaving-gridextra-objects-with-ploty-objects-in-rmarkdown
Here is the minimum reproducible code

````
---
title: "test_SO"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
library(plotly)
library(olsrr)
library(car)
library(htmltools)
```
```{r pressure, results='asis',echo=FALSE}

u_m <- lm(speed ~ dist, data = cars)
ols_plot<-  ols_plot_diagnostics(u_m) #grid arrange plot

line_plot <- plot_ly(cars, x = ~speed, y = ~dist, type = 'scatter', mode = 'lines') #plotly chart
plot_list<-list(ols_plot=ols_plot,line_plot=line_plot,ols_plot=ols_plot,line_plot=line_plot ) #creating a dummy list of plot objects

# the below code works
# plot_list[[1]] # using tagList on the gridextra plot doesnt work
# htmltools::tagList(plot_list[[2]])
# plot_list[[3]] 
# htmltools::tagList(plot_list[[4]])

#the for loop doesnt work
for (i in 1:4){

  if(names(plot_list[i])=="ols_plot")
  {
    print(plot_list[[1]])}
else
   if(names(plot_list[i])=="line_plot")
  {
  htmltools::tagList(plot_list[[2]])
  }
}

#htmltools::tagList(plot_list) # doesnt work either

```
````

**Comment by atusy** [comment] 2019-09-02 04:22
Let me minimize example, and introduce a workaround.

## Minimized example

````
```{r setup, include=FALSE}
library(ggplot2)
library(htmltools)
library(plotly)
```

```{r}
g <- ggplot2::qplot(1, 1)
p <- plotly::ggplotly(g)
list(g, p)
```
````

The above will print a raster plot (`ggplot2`) but not an htmlwidget (`plotly`).

## Workaruond

I tried several hacks but only one that worked is below (continued after the above example).
Here, the raster plot is explicitly saved as an image, and then sourced via `htmltools::tags$img()` so that it can be combined together with an htmlwidget via `htmltools::tagList()`.

````
```{r, message = FALSE}
f <- knitr::fig_path("png")
ggsave(f, g)
htmltools::tagList(htmltools::tags$img(src = f), p)
```
````

**Comment by atusy** [comment] 2019-09-02 05:15
You can also use implicit saving of plots.
This is easier for authors but more difficult for readers.

````
---
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(htmltools)
library(plotly)
```

```{r plots, fig.show='hide', results='hide'}
g <- lapply(1:4, ggplot2::qplot, 1)
p <- ggplotly(g[[2]])
g[-2]
```

```{r}
knitr::fig_chunk("plots", ext = "png", number = seq_along(g[-2])) %>%
  lapply(function(src) tags$img(src = src)) %>%
  append(list(p), 1) %>%
  tagList()
```
````

**Comment by cderv** [comment] 2020-11-02 10:24
I took another look at this to understand the why. 

In fact, I think the issue is here that htmlwidget can't be used inside a for loop natively. This is because the `knit_print` method will end up using internally `knitr::asis_output` (in `htmltools:::knit_print.shiny.tag.list`), and when not used in top level (like in a for loop) it won't work (see https://github.com/yihui/knitr/issues/1137).

That is why I believe the htmlwidgets are not showing. Usually, when you just have htmlwidgets, you can have them in a list and use `htmltools::tagList()` to show them (since [a long time now](https://github.com/ramnathv/htmlwidgets/pull/110). 
Here, `htmltools::tagList(plot_list)` does not work because you have regular plot, and htmlwidgets in the same list! 

You would need to either not build them with the same list and show them separately , or be more advanced and generate Rmd content programmatically to make them work at top level. Using knitr templating would work I think. Here is how: 

You would make a template Rmd containing only a chunk like this
````md
```{r, echo = FALSE}
plot_list[[{{i}}]]
```
````
then in your main Rmd, you would combine `knit_expand` and `knit_child` to get the content into your document. 
````md
---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plotly)
library(olsrr)
library(car)
```

```{r pressure, echo=FALSE}
u_m <- lm(speed ~ dist, data = cars)
ols_plot<-  ols_plot_diagnostics(u_m) #grid arrange plot

#plotly chart
line_plot <- plot_ly(cars, x = ~speed, y = ~dist, type = 'scatter', mode = 'lines') 
# creating a dummy list of plot objects
plot_list <- list(ols_plot=ols_plot,line_plot=line_plot,ols_plot=ols_plot,line_plot=line_plot )
```

```{r, results='asis'}
src <- lapply(seq_along(plot_list), function(i) knitr::knit_expand("template.Rmd"))
res = knitr::knit_child(text = unlist(src), quiet = TRUE)
cat(res, sep = '\n')
```
````

This has the effect to loop over your list by filling a template that would create for chunks with the correct `plot_list[[i]]`call. Then `knit_child` would evaluate this in the context of your document. The htmlwidgets will show because then call has become first level and not from within a for loop. 

This advanced method is described in there : https://bookdown.org/yihui/rmarkdown-cookbook/knit-expand.html

I'll close this issue as you have now several solutions.

**Closed by cderv** 2020-11-02 10:24 UTC
Labels: Question
