### ISSUE TITLE
ioslides: images with width not inlined

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rmarkdown#1689] opened 2019-11-06 22:17 UTC
The following R Markdown document does not inline the `logo.svg` image when rendering.

```markdown
---
title: image without inlining
output:
  ioslides_presentation: {}
---

![](logo.svg){width=20%}
```

This is because of how the `width` argument is rendered. 

Here is a Markdown document using two HTML image tags. The first (where `width` is before `src`) does not get the image inlined. The second (with `src` after the tag opens) has its image inlined.

```markdown
---
title: image without inlining
output:
  ioslides_presentation: {}
---

<img width="20%" src='logo.svg'>

<img src='logo.svg' width="20%">
```

The shape of the HTML is what prevents inlining; both Markdown and HTML input cause the same problem.

Content rendered to the ioslides output uses image inlining from in the `rmarkdown` package and appears to not rely on `pandoc` for inlining.

https://github.com/rstudio/rmarkdown/blob/d9e4b4583b9b3d2fb5efc09c7409c1945b6220af/R/base64.R#L25-L30

The `base64.R` regular expression is pretty narrow; it expects `src` immediately after the `img` tag.

I built this small patch to verify the cause -- it adds inlining when `width` is between `img` and `src`. It's probably not flexible enough.

```r
process_images <- function(html, processor) {
  html <- process_html_res(
    html,
    "<\\s*[Ii][Mm][Gg]\\s+[Ss][Rr][Cc]\\s*=\\s*[\"']([^\"']+)[\"']",
    processor)
  process_html_res(
    html,
    "<\\s*[Ii][Mm][Gg]\\s+width=\".+?\"\\s+[Ss][Rr][Cc]\\s*=\\s*[\"']([^\"']+)[\"']",
    processor)
}
```

**Comment by yihui** [comment] 2019-11-06 22:23
Duplicate of #1687

**Closed** 2019-11-06 22:26 UTC
