### ISSUE TITLE
TOC issue that headline with chinese characters only No links generated 

### ISSUE THREAD

**Issue by heavenzone** [rstudio/rmarkdown#1241] opened 2018-01-10 04:50 UTC
I don't know if this is an issue.

If the headline has chinese characters only, the output htmldocument's source code of this position `#TOC ul li a` does not create the href attribute. And the div wrapping the headline `<h2></h2>` does not create the id attribute.

here's the result.

## test env

i'v tested for both version 1.8 and version 1.8.5.
both of them caused this issue.

```
> packageVersion("rmarkdown")
[1] ‘1.8’
```

```
> packageVersion("rmarkdown")
[1] ‘1.8.5’
```

## rmarkdown file  

	---
	title: "rmarkdown toc that headline with chinese characters only issue"
	author:
	  - test
	output:
	  html_document:
		toc: true
	---

	## 中文标题

	chinese characters only

	## 标题headline

	mix

	## headline

	english only

## output html source code 

	<div id="TOC">
	<ul>
	<li><a>中文标题</a></li>
	<li><a href="#headline">标题headline</a></li>
	<li><a href="#headline-1">headline</a></li>
	</ul>
	</div>

	<div class="section level2">
	<h2>中文标题</h2>
	<p>chinese characters only</p>
	</div>
	<div id="headline" class="section level2">
	<h2>标题headline</h2>
	<p>mix</p>
	</div>
	<div id="headline-1" class="section level2">
	<h2>headline</h2>
	<p>english only</p>
	</div>
	
	
blogdown has the same issue.

**Comment by yihui** [comment] 2018-01-10 16:11
Duplicate of #1149

**Closed** 2018-01-10 16:12 UTC

**Comment by heavenzone** [comment] 2018-01-11 06:32
@yihui thanks for pointing out the details of this issue.
I think this issue could solve by javascript easily. so i searched "markdown toc" for another solution.
then I found this two repos:

- <https://github.com/yijian166/md-toc.js>
- <https://gist.github.com/cloudsben/6059930>

now i just easily paste these codes into rmarkdown files, Then the toc with pure Chinese makes sense.

```javascript
<script type="text/javascript">
 $(document).ready(function(){
      $("h2,h3,h4,h5,h6").each(function(i,item){
        var tag = $(item).get(0).localName;
        $(item).attr("id","wow"+i);
        $("#category").append('<a class="new'+tag+'" href="#wow'+i+'">'+$(this).text()+'</a></br>');
        $(".newh2").css("margin-left",0);
        $(".newh3").css("margin-left",20);
        $(".newh4").css("margin-left",40);
        $(".newh5").css("margin-left",60);
        $(".newh6").css("margin-left",80);
      });
 });
</script>
<div id="category"></div>
```
