### ISSUE TITLE
Running an rmarkdown with runtime shiny threw 'input' not found error on version 1.7 but it works fine on 1.6

### ISSUE THREAD

**Issue by ashraaghav** [rstudio/rmarkdown#1201] opened 2017-11-14 15:08 UTC
The YAML header of the Rmarkdown I was running

```
title: "TestMarkdownShiny"
author: "Ashwin Raaghav"
date: "30 August 2017"
output: html_document
runtime: shiny
```

Shiny version: 1.0.5
R version: 3.4.2

After I downgraded the package to 1.6, it started working again. I could not point out what exactly went wrong though and just wanted to bring this up.

**Comment by yihui** [comment] 2017-11-14 19:04
Duplicate of #1193

**Closed by yihui** 2017-11-14 19:04 UTC
Labels: duplicate
