### ISSUE TITLE
update pandoc in linux centos

### ISSUE THREAD

**Issue by Bryant-zhu** [rstudio/rmarkdown#1219] opened 2017-12-13 11:38 UTC
hi there, I was having a  hard time on updating pandoc in my centos Linux machine,
there is rarely tips or help about installing on Centos.

I need using R and flex dashboard in Linux to generate a daily data analysis report ...no ..I could not using render function in R.
 thanks

**Comment by yihui** [comment] 2017-12-14 02:46
Duplicate of #851

**Comment by Bryant-zhu** [comment] 2017-12-14 02:50
@yihui  hi yihui, as I  already checked #851, the situation is little different , after march 2017, Rstudio is not able to work in centos 6, so now it is a problem for me to install Rstudio in order to use pandoc...

was there a good detailed way of installing pandoc? I have check pandoc website and your tutorial.. and I still can't figure out ..

**Comment by yihui** [comment] 2017-12-14 02:53
I have replied you there. Let's keep it in a single issue. Thanks!

**Closed by yihui** 2017-12-14 02:53 UTC
Labels: question
