### ISSUE TITLE
Can't find local Rmd file

### ISSUE THREAD

**Issue by trestletech** [rstudio/rmarkdown#100] opened 2014-05-14 16:52 UTC
Windows 7, latest builds from master of knitr, rmarkdown, and shiny. Latest RStudio preview release.

I first encountered this when trying to use "Run document" in RStudio. I'm now trying the commands manually and getting the same issue.

```
> list.files(pattern="an-introduction-to-rstudio-shiny.Rmd")
[1] "an-introduction-to-rstudio-shiny.Rmd"
> rmarkdown::run("an-introduction-to-rstudio-shiny.Rmd")
Error in rmarkdown::run("an-introduction-to-rstudio-shiny.Rmd") : 
  The file 'an-introduction-to-rstudio-shiny.Rmd' does not exist in the directory 'C:\Users\jalle6\Dropbox'
> getwd()
[1] "C:/Users/jalle6/Dropbox"
```

I'm using the default Shiny presentation template with this YAML:

```

---
title: "An Introduction to RStudio Shiny"
author: "Jeff Allen"
date: "Wednesday, May 14, 2014"
output: ioslides_presentation
runtime: shiny

---
```

**Comment by yihui** [comment] 2017-08-30 21:28
I cannot reproduce this issue on Windows 7. Closing now and please feel free to reopen if it still exists.

**Closed by yihui** 2017-08-30 21:28 UTC
