### ISSUE TITLE
Cannot Knit Pdf(beamer)

### ISSUE THREAD

**Issue by gingershuying** [rstudio/rmarkdown#606] opened 2016-01-30 09:18 UTC
Hi everyone,
     When I try to knit a pdf (beamer) file, the screen shows the following message
**Error in sub(paste(patch, collapse = "\n"), "", paste(tpl, collapse = "\n"),  : 
  input string 1 is invalid in this locale
Calls: <Anonymous> ... do.call -> <Anonymous> -> patch_beamer_template -> sub**
However, no problem knit other kind of documents, even knitting a pdf_document is fine. 
I can't figure out any solutions. Could you please help me to solve the issues. 

Thanks in advance!

**Comment by yihui** [comment] 2016-01-30 17:48
What is your `devtools::session_info()` (after `library(rmarkdown)`)?

I guess you can use `template = NULL`, e.g.

```yaml
output:
  beamer_presentation:
    template: null
```

**Comment by gingershuying** [comment] 2016-01-31 02:44
Dear Yihui, 
          You are brilliant! The problem has been solved. Thank you very much! However, could I please ask why should  "template: null" be added? I used the Knit pdf (beamer) for several years and on several computers, this is the first time I should add this. So I am wondering why is this? Also, will the custom template instead of null template work?

My session_info is as following:

**Session info -------------------------------------------------------------------------------
 setting  value                           
 version  R version 3.2.3 (2015-12-10)    
 system   x86_64, mingw32                 
 ui       RStudio (0.99.491)              
 language (EN)                            
 collate  Chinese (Traditional)_Taiwan.950
 tz       Asia/Taipei                     
 date     2016-01-31                      

Packages -----------------------------------------------------------------------------------
 package   * version date       source                            
 curl        0.9.5   2016-01-23 CRAN (R 3.2.3)                    
 devtools  * 1.10.0  2016-01-23 CRAN (R 3.2.3)                    
 digest      0.6.9   2016-01-08 CRAN (R 3.2.3)                    
 git2r       0.13.1  2015-12-10 CRAN (R 3.2.3)                    
 htmltools   0.3     2015-12-29 CRAN (R 3.2.3)                    
 httr        1.1.0   2016-01-28 CRAN (R 3.2.3)                    
 memoise     1.0.0   2016-01-29 CRAN (R 3.2.3)                    
 R6          2.1.2   2016-01-26 CRAN (R 3.2.3)                    
 rmarkdown * 0.9.5   2016-01-30 Github (rstudio/rmarkdown@041aee2)
 withr       1.0.0   2015-09-23 CRAN (R 3.2.3)                    
 yaml        2.1.13  2014-06-12 CRAN (R 3.2.3)   
 **                

Thank you very much!

**Comment by yihui** [comment] 2016-02-04 06:16
I introduced the problem in a recent version of rmarkdown (#541). It will be fixed (#612). Sorry about that.

**Closed** 2016-02-04 10:44 UTC

**Comment by yihui** [comment] 2016-02-04 17:12
You can test the current development version of rmarkdown to see if the problem is still there without `template = NULL`: `devtools::install_github('rstudio/rmarkdown')`
